"""
Bundled team logos for nflstandings. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/ari-674792fd-10.png", LOGO_ARI_674792FD_10 = "file")
load("images/logos/atl-d2130c71-10.png", LOGO_ATL_D2130C71_10 = "file")
load("images/logos/bal-6ba45911-10.png", LOGO_BAL_6BA45911_10 = "file")
load("images/logos/buf-415a11b6-10.png", LOGO_BUF_415A11B6_10 = "file")
load("images/logos/car-3ae2523f-10.png", LOGO_CAR_3AE2523F_10 = "file")
load("images/logos/chi-740e583f-10.png", LOGO_CHI_740E583F_10 = "file")
load("images/logos/cin-1d55bc0d-10.png", LOGO_CIN_1D55BC0D_10 = "file")
load("images/logos/cle-71711e99-10.png", LOGO_CLE_71711E99_10 = "file")
load("images/logos/dal-e409cfb8-10.png", LOGO_DAL_E409CFB8_10 = "file")
load("images/logos/den-72daa7a8-10.png", LOGO_DEN_72DAA7A8_10 = "file")
load("images/logos/det-6917cd7f-10.png", LOGO_DET_6917CD7F_10 = "file")
load("images/logos/gb-a7b6e88d-10.png", LOGO_GB_A7B6E88D_10 = "file")
load("images/logos/hou-d70cdab6-10.png", LOGO_HOU_D70CDAB6_10 = "file")
load("images/logos/ind-2e85dcf0-10.png", LOGO_IND_2E85DCF0_10 = "file")
load("images/logos/jax-53599b70-10.png", LOGO_JAX_53599B70_10 = "file")
load("images/logos/kc-ee5a99b1-10.png", LOGO_KC_EE5A99B1_10 = "file")
load("images/logos/lac-e55546fb-10.png", LOGO_LAC_E55546FB_10 = "file")
load("images/logos/lar-71183ae8-10.png", LOGO_LAR_71183AE8_10 = "file")
load("images/logos/lv-a41f170a-10.png", LOGO_LV_A41F170A_10 = "file")
load("images/logos/mia-a8ef4f1e-10.png", LOGO_MIA_A8EF4F1E_10 = "file")
load("images/logos/min-c56c30fb-10.png", LOGO_MIN_C56C30FB_10 = "file")
load("images/logos/ne-df24b248-10.png", LOGO_NE_DF24B248_10 = "file")
load("images/logos/no-161a155d-10.png", LOGO_NO_161A155D_10 = "file")
load("images/logos/nyg-78a74ff1-10.png", LOGO_NYG_78A74FF1_10 = "file")
load("images/logos/nyj-e75307ce-10.png", LOGO_NYJ_E75307CE_10 = "file")
load("images/logos/phi-483eda76-10.png", LOGO_PHI_483EDA76_10 = "file")
load("images/logos/pit-fc5b64c6-10.png", LOGO_PIT_FC5B64C6_10 = "file")
load("images/logos/sea-66fd11bb-10.png", LOGO_SEA_66FD11BB_10 = "file")
load("images/logos/sf-b90e72ab-10.png", LOGO_SF_B90E72AB_10 = "file")
load("images/logos/tb-fef2fef1-10.png", LOGO_TB_FEF2FEF1_10 = "file")
load("images/logos/ten-0739837f-10.png", LOGO_TEN_0739837F_10 = "file")
load("images/logos/wsh-de3187c9-10.png", LOGO_WSH_DE3187C9_10 = "file")

BUNDLED_LOGOS = {
    # ARI; source sha256 c34624684a4dfcc9a8ea326f545cbd06a8380292760b4a50d117ab25114fd3c4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/ari.png&h=50&w=50": {
        10: LOGO_ARI_674792FD_10,
    },
    # ATL; source sha256 a4267ec18142b444958fedc1f8de236eaeec5e24a14bea88b0a07e9afe31da8c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/atl.png&h=50&w=50": {
        10: LOGO_ATL_D2130C71_10,
    },
    # BAL; source sha256 a01d67b34359d4eb9bdf8693997f58ccc19d5fba35d310343ff74886fc3a72ee
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/bal.png&h=50&w=50": {
        10: LOGO_BAL_6BA45911_10,
    },
    # BUF; source sha256 4635a704a8923b3c2f0588af87e1609d0910e41a36fe46a0ed016d5ab347ac34
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/buf.png&h=50&w=50": {
        10: LOGO_BUF_415A11B6_10,
    },
    # CAR; source sha256 90f39bb28504ff6612e562f36a7459a411fa93509a73fa60bcd762a57bae41bd
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/car.png&h=50&w=50": {
        10: LOGO_CAR_3AE2523F_10,
    },
    # CHI; source sha256 577f7e492cb84e864ac0a2c27ce12824615c9954df29fa923dfa41d3a95afc43
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/chi.png&h=50&w=50": {
        10: LOGO_CHI_740E583F_10,
    },
    # CIN; source sha256 ae93d5782253408a627462b3994b52055182b0396a66fa2c24969be950c5fdd2
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/cin.png&h=50&w=50": {
        10: LOGO_CIN_1D55BC0D_10,
    },
    # CLE; source sha256 a14166bac30295a48ea6f0120b1807e3efab5b220c54a96cee39db7efd6c6c7f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/cle.png&h=50&w=50": {
        10: LOGO_CLE_71711E99_10,
    },
    # DAL; source sha256 c02dc121473e93ef7d1bef5e79caa52bbb28957d2dc2bc3ee66b4641413f2954
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/dal.png&h=50&w=50": {
        10: LOGO_DAL_E409CFB8_10,
    },
    # DEN; source sha256 1d550499e2339bc268d3f3965ab0d302c3255faf383306323c7eee304802e48e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/den.png&h=50&w=50": {
        10: LOGO_DEN_72DAA7A8_10,
    },
    # DET; source sha256 b7c10d75f27ba1328b9bf612dc3673d2859c088b7923a8e46fe1eca255c29ed8
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/det.png&h=50&w=50": {
        10: LOGO_DET_6917CD7F_10,
    },
    # GB; source sha256 a1dbb99506303e72e28252c0440ed3abe99a800157d0d84c6ac12542c4363939
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/gb.png&h=50&w=50": {
        10: LOGO_GB_A7B6E88D_10,
    },
    # HOU; source sha256 17ecd62d86c444dc4556f37ea509eb24fc005aa266f93386679c9b3ececd31f4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/hou.png&h=50&w=50": {
        10: LOGO_HOU_D70CDAB6_10,
    },
    # JAX; source sha256 c8ae06f055b387ad2ef54031939dce898ffd268a59fb19624d24e8be864bee51
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/jax.png&h=50&w=50": {
        10: LOGO_JAX_53599B70_10,
    },
    # KC; source sha256 738b1f127d1756294b64a4823d1aa79dc6685003a6674f69f9b07e3951c536c3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/kc.png&h=50&w=50": {
        10: LOGO_KC_EE5A99B1_10,
    },
    # LAC; source sha256 e3813324e26edeb657c5062ee4ea29d577c2f440c802e7121552d67faf61e09a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/lac.png&h=50&w=50": {
        10: LOGO_LAC_E55546FB_10,
    },
    # LAR; source sha256 cdfcf3dbd765774a4838d824ae553ea65a84d70ebcc7cf657711bd17362cc97c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/lar.png&h=50&w=50": {
        10: LOGO_LAR_71183AE8_10,
    },
    # LV; source sha256 f4caba786fd1ad3934ab3986d0db98e29ea8e596713cedf11ccae65a542ff396
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/lv.png&h=50&w=50": {
        10: LOGO_LV_A41F170A_10,
    },
    # MIA; source sha256 6396bbf92bc5be54bc1adeb189a8f7353c297a4aa30a4f38328714167bc196c9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/mia.png&h=50&w=50": {
        10: LOGO_MIA_A8EF4F1E_10,
    },
    # MIN; source sha256 b7ea8966899cb2ffe6a715ae8da3a237e75fc5dd728d3e4668344e659ba8aa1f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/min.png&h=50&w=50": {
        10: LOGO_MIN_C56C30FB_10,
    },
    # NE; source sha256 d755706bbe3e23cfa1dc62576d9f79e38fb3b7562d199147162a176db2d907c6
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/ne.png&h=50&w=50": {
        10: LOGO_NE_DF24B248_10,
    },
    # NO; source sha256 db07a4ad7d4c5a1adcfec6d2218885c5f3108186d081e45687b34383fc3ccac1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/no.png&h=50&w=50": {
        10: LOGO_NO_161A155D_10,
    },
    # NYG; source sha256 1608d32e45afa462bd82fda1a84a285ef5b977ad0fa0e03b785b6f2c746d2330
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/nyg.png&h=50&w=50": {
        10: LOGO_NYG_78A74FF1_10,
    },
    # NYJ; source sha256 82708d50b24c1ad73dcddff8173be44d3f105ba537bd32a0475d35a8ba1edfd9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/nyj.png&h=50&w=50": {
        10: LOGO_NYJ_E75307CE_10,
    },
    # PHI; source sha256 b5b6de048f2d1dc6e904a69baa90cc444bf13bb994b79681e39eb443b4146e57
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/phi.png&h=50&w=50": {
        10: LOGO_PHI_483EDA76_10,
    },
    # PIT; source sha256 a47bd5902f90b5f03178522541b2491921024b95ea0c6b7279cea62d8a754d30
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/pit.png&h=50&w=50": {
        10: LOGO_PIT_FC5B64C6_10,
    },
    # SEA; source sha256 a26148a8bace1539eb5b3b3530669ce8683f18b33fc61b6686d08d68dfec027b
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/sea.png&h=50&w=50": {
        10: LOGO_SEA_66FD11BB_10,
    },
    # SF; source sha256 57ed3d0bbc3e5d1d1ce55dc61fa9a2db99993a13c4b15dda0c085b5fa8c19e18
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/sf.png&h=50&w=50": {
        10: LOGO_SF_B90E72AB_10,
    },
    # TB; source sha256 4f8c0ecba48a153dee5392ef283d9d8fc2176c0960c6ba6949d4c84f1b75bbfb
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/tb.png&h=50&w=50": {
        10: LOGO_TB_FEF2FEF1_10,
    },
    # TEN; source sha256 9cfcd9dcf91556dc05c43f60e044419b082b67759c1d7b6252205400f87fdbd4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/ten.png&h=50&w=50": {
        10: LOGO_TEN_0739837F_10,
    },
    # WSH; source sha256 171b3de9f8757f3c538434e329b39ee6cf32a1c4d020bf373820de2516a886e4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nfl/500-dark/scoreboard/wsh.png&h=50&w=50": {
        10: LOGO_WSH_DE3187C9_10,
    },
    # IND; source sha256 c59105ddaf13f73f07b5db09ddc3b542278a71f6a3a88024efa31241e27e6e4e
    "https://i.ibb.co/jzMc7SB/colts.png": {
        10: LOGO_IND_2E85DCF0_10,
    },
}
