"""
Bundled team logos for nbascores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/atl-ba15ab80-16.png", LOGO_ATL_BA15AB80_16 = "file")
load("images/logos/atl-ba15ab80-30.png", LOGO_ATL_BA15AB80_30 = "file")
load("images/logos/atl-ba15ab80-32.png", LOGO_ATL_BA15AB80_32 = "file")
load("images/logos/atl-ba15ab80-60.png", LOGO_ATL_BA15AB80_60 = "file")
load("images/logos/atl-ba15ab80-64.png", LOGO_ATL_BA15AB80_64 = "file")
load("images/logos/bkn-2ea304b5-16.png", LOGO_BKN_2EA304B5_16 = "file")
load("images/logos/bkn-2ea304b5-30.png", LOGO_BKN_2EA304B5_30 = "file")
load("images/logos/bkn-2ea304b5-32.png", LOGO_BKN_2EA304B5_32 = "file")
load("images/logos/bkn-2ea304b5-60.png", LOGO_BKN_2EA304B5_60 = "file")
load("images/logos/bkn-2ea304b5-64.png", LOGO_BKN_2EA304B5_64 = "file")
load("images/logos/bos-1f08d3a2-18.png", LOGO_BOS_1F08D3A2_18 = "file")
load("images/logos/bos-1f08d3a2-30.png", LOGO_BOS_1F08D3A2_30 = "file")
load("images/logos/bos-1f08d3a2-32.png", LOGO_BOS_1F08D3A2_32 = "file")
load("images/logos/bos-1f08d3a2-36.png", LOGO_BOS_1F08D3A2_36 = "file")
load("images/logos/bos-1f08d3a2-60.png", LOGO_BOS_1F08D3A2_60 = "file")
load("images/logos/bos-1f08d3a2-64.png", LOGO_BOS_1F08D3A2_64 = "file")
load("images/logos/cha-e5aa7e29-18.png", LOGO_CHA_E5AA7E29_18 = "file")
load("images/logos/cha-e5aa7e29-30.png", LOGO_CHA_E5AA7E29_30 = "file")
load("images/logos/cha-e5aa7e29-32.png", LOGO_CHA_E5AA7E29_32 = "file")
load("images/logos/cha-e5aa7e29-36.png", LOGO_CHA_E5AA7E29_36 = "file")
load("images/logos/cha-e5aa7e29-60.png", LOGO_CHA_E5AA7E29_60 = "file")
load("images/logos/cha-e5aa7e29-64.png", LOGO_CHA_E5AA7E29_64 = "file")
load("images/logos/chi-4d72ecba-16.png", LOGO_CHI_4D72ECBA_16 = "file")
load("images/logos/chi-4d72ecba-30.png", LOGO_CHI_4D72ECBA_30 = "file")
load("images/logos/chi-4d72ecba-32.png", LOGO_CHI_4D72ECBA_32 = "file")
load("images/logos/chi-4d72ecba-60.png", LOGO_CHI_4D72ECBA_60 = "file")
load("images/logos/chi-4d72ecba-64.png", LOGO_CHI_4D72ECBA_64 = "file")
load("images/logos/cle-398f5431-16.png", LOGO_CLE_398F5431_16 = "file")
load("images/logos/cle-398f5431-30.png", LOGO_CLE_398F5431_30 = "file")
load("images/logos/cle-398f5431-32.png", LOGO_CLE_398F5431_32 = "file")
load("images/logos/cle-398f5431-60.png", LOGO_CLE_398F5431_60 = "file")
load("images/logos/cle-398f5431-64.png", LOGO_CLE_398F5431_64 = "file")
load("images/logos/dal-b6f9161a-16.png", LOGO_DAL_B6F9161A_16 = "file")
load("images/logos/dal-b6f9161a-30.png", LOGO_DAL_B6F9161A_30 = "file")
load("images/logos/dal-b6f9161a-32.png", LOGO_DAL_B6F9161A_32 = "file")
load("images/logos/dal-b6f9161a-60.png", LOGO_DAL_B6F9161A_60 = "file")
load("images/logos/dal-b6f9161a-64.png", LOGO_DAL_B6F9161A_64 = "file")
load("images/logos/den-7e361872-14.png", LOGO_DEN_7E361872_14 = "file")
load("images/logos/den-7e361872-28.png", LOGO_DEN_7E361872_28 = "file")
load("images/logos/den-7e361872-30.png", LOGO_DEN_7E361872_30 = "file")
load("images/logos/den-7e361872-32.png", LOGO_DEN_7E361872_32 = "file")
load("images/logos/den-7e361872-60.png", LOGO_DEN_7E361872_60 = "file")
load("images/logos/den-7e361872-64.png", LOGO_DEN_7E361872_64 = "file")
load("images/logos/det-777ced85-16.png", LOGO_DET_777CED85_16 = "file")
load("images/logos/det-777ced85-30.png", LOGO_DET_777CED85_30 = "file")
load("images/logos/det-777ced85-32.png", LOGO_DET_777CED85_32 = "file")
load("images/logos/det-777ced85-60.png", LOGO_DET_777CED85_60 = "file")
load("images/logos/det-777ced85-64.png", LOGO_DET_777CED85_64 = "file")
load("images/logos/gs-766f1c19-16.png", LOGO_GS_766F1C19_16 = "file")
load("images/logos/gs-766f1c19-30.png", LOGO_GS_766F1C19_30 = "file")
load("images/logos/gs-766f1c19-32.png", LOGO_GS_766F1C19_32 = "file")
load("images/logos/gs-766f1c19-60.png", LOGO_GS_766F1C19_60 = "file")
load("images/logos/gs-766f1c19-64.png", LOGO_GS_766F1C19_64 = "file")
load("images/logos/hou-4f592b68-16.png", LOGO_HOU_4F592B68_16 = "file")
load("images/logos/hou-4f592b68-30.png", LOGO_HOU_4F592B68_30 = "file")
load("images/logos/hou-4f592b68-32.png", LOGO_HOU_4F592B68_32 = "file")
load("images/logos/hou-4f592b68-60.png", LOGO_HOU_4F592B68_60 = "file")
load("images/logos/hou-4f592b68-64.png", LOGO_HOU_4F592B68_64 = "file")
load("images/logos/ind-4fc23489-16.png", LOGO_IND_4FC23489_16 = "file")
load("images/logos/ind-4fc23489-30.png", LOGO_IND_4FC23489_30 = "file")
load("images/logos/ind-4fc23489-32.png", LOGO_IND_4FC23489_32 = "file")
load("images/logos/ind-4fc23489-60.png", LOGO_IND_4FC23489_60 = "file")
load("images/logos/ind-4fc23489-64.png", LOGO_IND_4FC23489_64 = "file")
load("images/logos/lac-55e51ad0-16.png", LOGO_LAC_55E51AD0_16 = "file")
load("images/logos/lac-55e51ad0-30.png", LOGO_LAC_55E51AD0_30 = "file")
load("images/logos/lac-55e51ad0-32.png", LOGO_LAC_55E51AD0_32 = "file")
load("images/logos/lac-55e51ad0-60.png", LOGO_LAC_55E51AD0_60 = "file")
load("images/logos/lac-55e51ad0-64.png", LOGO_LAC_55E51AD0_64 = "file")
load("images/logos/lal-5ab19ea3-18.png", LOGO_LAL_5AB19EA3_18 = "file")
load("images/logos/lal-5ab19ea3-30.png", LOGO_LAL_5AB19EA3_30 = "file")
load("images/logos/lal-5ab19ea3-32.png", LOGO_LAL_5AB19EA3_32 = "file")
load("images/logos/lal-5ab19ea3-36.png", LOGO_LAL_5AB19EA3_36 = "file")
load("images/logos/lal-5ab19ea3-60.png", LOGO_LAL_5AB19EA3_60 = "file")
load("images/logos/lal-5ab19ea3-64.png", LOGO_LAL_5AB19EA3_64 = "file")
load("images/logos/mem-93587f1a-16.png", LOGO_MEM_93587F1A_16 = "file")
load("images/logos/mem-93587f1a-30.png", LOGO_MEM_93587F1A_30 = "file")
load("images/logos/mem-93587f1a-32.png", LOGO_MEM_93587F1A_32 = "file")
load("images/logos/mem-93587f1a-60.png", LOGO_MEM_93587F1A_60 = "file")
load("images/logos/mem-93587f1a-64.png", LOGO_MEM_93587F1A_64 = "file")
load("images/logos/mia-cd4abee5-16.png", LOGO_MIA_CD4ABEE5_16 = "file")
load("images/logos/mia-cd4abee5-30.png", LOGO_MIA_CD4ABEE5_30 = "file")
load("images/logos/mia-cd4abee5-32.png", LOGO_MIA_CD4ABEE5_32 = "file")
load("images/logos/mia-cd4abee5-60.png", LOGO_MIA_CD4ABEE5_60 = "file")
load("images/logos/mia-cd4abee5-64.png", LOGO_MIA_CD4ABEE5_64 = "file")
load("images/logos/mil-23fc6fac-18.png", LOGO_MIL_23FC6FAC_18 = "file")
load("images/logos/mil-23fc6fac-30.png", LOGO_MIL_23FC6FAC_30 = "file")
load("images/logos/mil-23fc6fac-32.png", LOGO_MIL_23FC6FAC_32 = "file")
load("images/logos/mil-23fc6fac-36.png", LOGO_MIL_23FC6FAC_36 = "file")
load("images/logos/mil-23fc6fac-60.png", LOGO_MIL_23FC6FAC_60 = "file")
load("images/logos/mil-23fc6fac-64.png", LOGO_MIL_23FC6FAC_64 = "file")
load("images/logos/min-5896cbe2-16.png", LOGO_MIN_5896CBE2_16 = "file")
load("images/logos/min-5896cbe2-30.png", LOGO_MIN_5896CBE2_30 = "file")
load("images/logos/min-5896cbe2-32.png", LOGO_MIN_5896CBE2_32 = "file")
load("images/logos/min-5896cbe2-60.png", LOGO_MIN_5896CBE2_60 = "file")
load("images/logos/min-5896cbe2-64.png", LOGO_MIN_5896CBE2_64 = "file")
load("images/logos/no-1bfbe29e-24.png", LOGO_NO_1BFBE29E_24 = "file")
load("images/logos/no-1bfbe29e-30.png", LOGO_NO_1BFBE29E_30 = "file")
load("images/logos/no-1bfbe29e-32.png", LOGO_NO_1BFBE29E_32 = "file")
load("images/logos/no-1bfbe29e-48.png", LOGO_NO_1BFBE29E_48 = "file")
load("images/logos/no-1bfbe29e-60.png", LOGO_NO_1BFBE29E_60 = "file")
load("images/logos/no-1bfbe29e-64.png", LOGO_NO_1BFBE29E_64 = "file")
load("images/logos/ny-4744f6a1-18.png", LOGO_NY_4744F6A1_18 = "file")
load("images/logos/ny-4744f6a1-30.png", LOGO_NY_4744F6A1_30 = "file")
load("images/logos/ny-4744f6a1-32.png", LOGO_NY_4744F6A1_32 = "file")
load("images/logos/ny-4744f6a1-36.png", LOGO_NY_4744F6A1_36 = "file")
load("images/logos/ny-4744f6a1-60.png", LOGO_NY_4744F6A1_60 = "file")
load("images/logos/ny-4744f6a1-64.png", LOGO_NY_4744F6A1_64 = "file")
load("images/logos/okc-8d721def-24.png", LOGO_OKC_8D721DEF_24 = "file")
load("images/logos/okc-8d721def-30.png", LOGO_OKC_8D721DEF_30 = "file")
load("images/logos/okc-8d721def-32.png", LOGO_OKC_8D721DEF_32 = "file")
load("images/logos/okc-8d721def-48.png", LOGO_OKC_8D721DEF_48 = "file")
load("images/logos/okc-8d721def-60.png", LOGO_OKC_8D721DEF_60 = "file")
load("images/logos/okc-8d721def-64.png", LOGO_OKC_8D721DEF_64 = "file")
load("images/logos/orl-bdec3217-18.png", LOGO_ORL_BDEC3217_18 = "file")
load("images/logos/orl-bdec3217-30.png", LOGO_ORL_BDEC3217_30 = "file")
load("images/logos/orl-bdec3217-32.png", LOGO_ORL_BDEC3217_32 = "file")
load("images/logos/orl-bdec3217-36.png", LOGO_ORL_BDEC3217_36 = "file")
load("images/logos/orl-bdec3217-60.png", LOGO_ORL_BDEC3217_60 = "file")
load("images/logos/orl-bdec3217-64.png", LOGO_ORL_BDEC3217_64 = "file")
load("images/logos/phi-b5ce26fc-source.png", LOGO_PHI_B5CE26FC_SOURCE = "file")
load("images/logos/phx-aff914ab-18.png", LOGO_PHX_AFF914AB_18 = "file")
load("images/logos/phx-aff914ab-30.png", LOGO_PHX_AFF914AB_30 = "file")
load("images/logos/phx-aff914ab-32.png", LOGO_PHX_AFF914AB_32 = "file")
load("images/logos/phx-aff914ab-36.png", LOGO_PHX_AFF914AB_36 = "file")
load("images/logos/phx-aff914ab-60.png", LOGO_PHX_AFF914AB_60 = "file")
load("images/logos/phx-aff914ab-64.png", LOGO_PHX_AFF914AB_64 = "file")
load("images/logos/por-db7e6dd5-16.png", LOGO_POR_DB7E6DD5_16 = "file")
load("images/logos/por-db7e6dd5-30.png", LOGO_POR_DB7E6DD5_30 = "file")
load("images/logos/por-db7e6dd5-32.png", LOGO_POR_DB7E6DD5_32 = "file")
load("images/logos/por-db7e6dd5-60.png", LOGO_POR_DB7E6DD5_60 = "file")
load("images/logos/por-db7e6dd5-64.png", LOGO_POR_DB7E6DD5_64 = "file")
load("images/logos/sa-7c55bf73-18.png", LOGO_SA_7C55BF73_18 = "file")
load("images/logos/sa-7c55bf73-30.png", LOGO_SA_7C55BF73_30 = "file")
load("images/logos/sa-7c55bf73-32.png", LOGO_SA_7C55BF73_32 = "file")
load("images/logos/sa-7c55bf73-36.png", LOGO_SA_7C55BF73_36 = "file")
load("images/logos/sa-7c55bf73-60.png", LOGO_SA_7C55BF73_60 = "file")
load("images/logos/sa-7c55bf73-64.png", LOGO_SA_7C55BF73_64 = "file")
load("images/logos/sac-529fcec8-16.png", LOGO_SAC_529FCEC8_16 = "file")
load("images/logos/sac-529fcec8-30.png", LOGO_SAC_529FCEC8_30 = "file")
load("images/logos/sac-529fcec8-32.png", LOGO_SAC_529FCEC8_32 = "file")
load("images/logos/sac-529fcec8-60.png", LOGO_SAC_529FCEC8_60 = "file")
load("images/logos/sac-529fcec8-64.png", LOGO_SAC_529FCEC8_64 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/tor-c37cb97d-source.png", LOGO_TOR_C37CB97D_SOURCE = "file")
load("images/logos/utah-fd22bc0f-16.png", LOGO_UTAH_FD22BC0F_16 = "file")
load("images/logos/utah-fd22bc0f-30.png", LOGO_UTAH_FD22BC0F_30 = "file")
load("images/logos/utah-fd22bc0f-32.png", LOGO_UTAH_FD22BC0F_32 = "file")
load("images/logos/utah-fd22bc0f-60.png", LOGO_UTAH_FD22BC0F_60 = "file")
load("images/logos/utah-fd22bc0f-64.png", LOGO_UTAH_FD22BC0F_64 = "file")
load("images/logos/wsh-11db2bcc-14.png", LOGO_WSH_11DB2BCC_14 = "file")
load("images/logos/wsh-11db2bcc-28.png", LOGO_WSH_11DB2BCC_28 = "file")
load("images/logos/wsh-11db2bcc-30.png", LOGO_WSH_11DB2BCC_30 = "file")
load("images/logos/wsh-11db2bcc-32.png", LOGO_WSH_11DB2BCC_32 = "file")
load("images/logos/wsh-11db2bcc-60.png", LOGO_WSH_11DB2BCC_60 = "file")
load("images/logos/wsh-11db2bcc-64.png", LOGO_WSH_11DB2BCC_64 = "file")

BUNDLED_LOGOS = {
    # ATL; source sha256 6d2d78b1e655c5563767118e5a693ad99ec56aac27a857e032db5f2bdfaa7fa5
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/atl.png&h=50&w=50": {
        16: LOGO_ATL_BA15AB80_16,
        30: LOGO_ATL_BA15AB80_30,
        32: LOGO_ATL_BA15AB80_32,
        60: LOGO_ATL_BA15AB80_60,
        64: LOGO_ATL_BA15AB80_64,
    },
    # BKN; source sha256 1e91bb43507c03b288b868a9d7d8fe2281a0462e2ce66e888fd67000149b3d14
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/bkn.png&h=50&w=50": {
        16: LOGO_BKN_2EA304B5_16,
        30: LOGO_BKN_2EA304B5_30,
        32: LOGO_BKN_2EA304B5_32,
        60: LOGO_BKN_2EA304B5_60,
        64: LOGO_BKN_2EA304B5_64,
    },
    # BOS; source sha256 de7dc1eb792e4d5e25b9982264eb0536c90344e58cad157e53ad1bf94fcca30c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/bos.png&h=50&w=50": {
        18: LOGO_BOS_1F08D3A2_18,
        30: LOGO_BOS_1F08D3A2_30,
        32: LOGO_BOS_1F08D3A2_32,
        36: LOGO_BOS_1F08D3A2_36,
        60: LOGO_BOS_1F08D3A2_60,
        64: LOGO_BOS_1F08D3A2_64,
    },
    # CHA; source sha256 0df03231eace85957ec3e21b4e6c74b124ace8415f069b7db91abbfef06091ec
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/cha.png&h=50&w=50": {
        18: LOGO_CHA_E5AA7E29_18,
        30: LOGO_CHA_E5AA7E29_30,
        32: LOGO_CHA_E5AA7E29_32,
        36: LOGO_CHA_E5AA7E29_36,
        60: LOGO_CHA_E5AA7E29_60,
        64: LOGO_CHA_E5AA7E29_64,
    },
    # CHI; source sha256 910bfc0a0c7f0455dd0517b96fe14588fe459f367279941b84b99cc6a119e020
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/chi.png&h=50&w=50": {
        16: LOGO_CHI_4D72ECBA_16,
        30: LOGO_CHI_4D72ECBA_30,
        32: LOGO_CHI_4D72ECBA_32,
        60: LOGO_CHI_4D72ECBA_60,
        64: LOGO_CHI_4D72ECBA_64,
    },
    # CLE; source sha256 63a8f54ee5a16938460e001d11a96bf34dfeb69e3f0d0c7e54e2574173265b6c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/cle.png&h=50&w=50": {
        16: LOGO_CLE_398F5431_16,
        30: LOGO_CLE_398F5431_30,
        32: LOGO_CLE_398F5431_32,
        60: LOGO_CLE_398F5431_60,
        64: LOGO_CLE_398F5431_64,
    },
    # DAL; source sha256 97767280b970fd1dc32caf2e6f55319f136c8638c8c5187296019096b4c35941
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/dal.png&h=50&w=50": {
        16: LOGO_DAL_B6F9161A_16,
        30: LOGO_DAL_B6F9161A_30,
        32: LOGO_DAL_B6F9161A_32,
        60: LOGO_DAL_B6F9161A_60,
        64: LOGO_DAL_B6F9161A_64,
    },
    # DEN; source sha256 6b52e77fdd0562deca9119bf4bc0cdd93e9f68bf4b56734e360313061deb32b3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/den.png&h=50&w=50": {
        14: LOGO_DEN_7E361872_14,
        28: LOGO_DEN_7E361872_28,
        30: LOGO_DEN_7E361872_30,
        32: LOGO_DEN_7E361872_32,
        60: LOGO_DEN_7E361872_60,
        64: LOGO_DEN_7E361872_64,
    },
    # DET; source sha256 3f35034fb4c03a8a2b812b4dcf7ba2c93c84ee8f300e29beb16d193a245831a3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/det.png&h=50&w=50": {
        16: LOGO_DET_777CED85_16,
        30: LOGO_DET_777CED85_30,
        32: LOGO_DET_777CED85_32,
        60: LOGO_DET_777CED85_60,
        64: LOGO_DET_777CED85_64,
    },
    # GS; source sha256 cfe943505590877100969a1a6921aa3e8ed33aa761a98a8b36155a38370fdc81
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/gs.png&h=50&w=50": {
        16: LOGO_GS_766F1C19_16,
        30: LOGO_GS_766F1C19_30,
        32: LOGO_GS_766F1C19_32,
        60: LOGO_GS_766F1C19_60,
        64: LOGO_GS_766F1C19_64,
    },
    # IND; source sha256 8216c090ab24564c38ca866a108ac2eedeacb8713cbfc5bc213d38d984d94f2d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/ind.png&h=50&w=50": {
        16: LOGO_IND_4FC23489_16,
        30: LOGO_IND_4FC23489_30,
        32: LOGO_IND_4FC23489_32,
        60: LOGO_IND_4FC23489_60,
        64: LOGO_IND_4FC23489_64,
    },
    # LAC; source sha256 14c30cb87adcc3bd1f7ca43cfe3aa3f6bae2118e426da55310db2965b9303b15
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/lac.png&h=50&w=50": {
        16: LOGO_LAC_55E51AD0_16,
        30: LOGO_LAC_55E51AD0_30,
        32: LOGO_LAC_55E51AD0_32,
        60: LOGO_LAC_55E51AD0_60,
        64: LOGO_LAC_55E51AD0_64,
    },
    # LAL; source sha256 c048a8100305c1340e18089007827f1d2a54eae254336522c27f225bf4c232e1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/lal.png&h=50&w=50": {
        18: LOGO_LAL_5AB19EA3_18,
        30: LOGO_LAL_5AB19EA3_30,
        32: LOGO_LAL_5AB19EA3_32,
        36: LOGO_LAL_5AB19EA3_36,
        60: LOGO_LAL_5AB19EA3_60,
        64: LOGO_LAL_5AB19EA3_64,
    },
    # MEM; source sha256 4147eb3d2aaa0513f722f2a4c2a6854c8d7205ed5a8da38fd5815c7ede8b04ef
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mem.png&h=50&w=50": {
        16: LOGO_MEM_93587F1A_16,
        30: LOGO_MEM_93587F1A_30,
        32: LOGO_MEM_93587F1A_32,
        60: LOGO_MEM_93587F1A_60,
        64: LOGO_MEM_93587F1A_64,
    },
    # MIA; source sha256 0fb0f982d3dcfeb3fb599d385605cb6e15275db7f7ea060dd46ff1cd48564975
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mia.png&h=50&w=50": {
        16: LOGO_MIA_CD4ABEE5_16,
        30: LOGO_MIA_CD4ABEE5_30,
        32: LOGO_MIA_CD4ABEE5_32,
        60: LOGO_MIA_CD4ABEE5_60,
        64: LOGO_MIA_CD4ABEE5_64,
    },
    # MIL; source sha256 b6c796073ae4ed03d7816adee9198aa5027749015907dea5c31c219f88d7e7fa
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mil.png&h=50&w=50": {
        18: LOGO_MIL_23FC6FAC_18,
        30: LOGO_MIL_23FC6FAC_30,
        32: LOGO_MIL_23FC6FAC_32,
        36: LOGO_MIL_23FC6FAC_36,
        60: LOGO_MIL_23FC6FAC_60,
        64: LOGO_MIL_23FC6FAC_64,
    },
    # MIN; source sha256 400630b0d3b9b7e113d9c3f495693b432d6494a3ba96ff53a305914b9bfaaaff
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/min.png&h=50&w=50": {
        16: LOGO_MIN_5896CBE2_16,
        30: LOGO_MIN_5896CBE2_30,
        32: LOGO_MIN_5896CBE2_32,
        60: LOGO_MIN_5896CBE2_60,
        64: LOGO_MIN_5896CBE2_64,
    },
    # NO; source sha256 f579a9ddd5ebbe52cb7ae9667d6eaeacb83938efee8a368b9b1b21a83c917588
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/no.png&h=50&w=50": {
        24: LOGO_NO_1BFBE29E_24,
        30: LOGO_NO_1BFBE29E_30,
        32: LOGO_NO_1BFBE29E_32,
        48: LOGO_NO_1BFBE29E_48,
        60: LOGO_NO_1BFBE29E_60,
        64: LOGO_NO_1BFBE29E_64,
    },
    # NY; source sha256 8e38916af8d9e0cb997e3c30ded2c82dd52a046d250e1dfd3342b50a6cceb523
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/ny.png&h=50&w=50": {
        18: LOGO_NY_4744F6A1_18,
        30: LOGO_NY_4744F6A1_30,
        32: LOGO_NY_4744F6A1_32,
        36: LOGO_NY_4744F6A1_36,
        60: LOGO_NY_4744F6A1_60,
        64: LOGO_NY_4744F6A1_64,
    },
    # OKC; source sha256 e90a1b5d9162fec2acd1e2439936aa557281d540d9184bbdf7646028a5e04a1d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/okc.png&h=50&w=50": {
        24: LOGO_OKC_8D721DEF_24,
        30: LOGO_OKC_8D721DEF_30,
        32: LOGO_OKC_8D721DEF_32,
        48: LOGO_OKC_8D721DEF_48,
        60: LOGO_OKC_8D721DEF_60,
        64: LOGO_OKC_8D721DEF_64,
    },
    # ORL; source sha256 3b05ddc52b36f694bac1033651fe502a8dbdbfbf82d05ce4c67bacaac935a89e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/orl.png&h=50&w=50": {
        18: LOGO_ORL_BDEC3217_18,
        30: LOGO_ORL_BDEC3217_30,
        32: LOGO_ORL_BDEC3217_32,
        36: LOGO_ORL_BDEC3217_36,
        60: LOGO_ORL_BDEC3217_60,
        64: LOGO_ORL_BDEC3217_64,
    },
    # PHX; source sha256 d48a6a862b6aa2a0ff1d14c8e101a8b3b9d92ee0dadab36be46ec0c48e8410ad
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/phx.png&h=50&w=50": {
        18: LOGO_PHX_AFF914AB_18,
        30: LOGO_PHX_AFF914AB_30,
        32: LOGO_PHX_AFF914AB_32,
        36: LOGO_PHX_AFF914AB_36,
        60: LOGO_PHX_AFF914AB_60,
        64: LOGO_PHX_AFF914AB_64,
    },
    # POR; source sha256 c6a0374db957e34891eb8ad10cbffb0435b677fa441be60d338553e818f1f23e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/por.png&h=50&w=50": {
        16: LOGO_POR_DB7E6DD5_16,
        30: LOGO_POR_DB7E6DD5_30,
        32: LOGO_POR_DB7E6DD5_32,
        60: LOGO_POR_DB7E6DD5_60,
        64: LOGO_POR_DB7E6DD5_64,
    },
    # SA; source sha256 e33cdb9d11762dce6ce6ef3b8996912a19260860d8b6a20679c1bc423b97260d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/sa.png&h=50&w=50": {
        18: LOGO_SA_7C55BF73_18,
        30: LOGO_SA_7C55BF73_30,
        32: LOGO_SA_7C55BF73_32,
        36: LOGO_SA_7C55BF73_36,
        60: LOGO_SA_7C55BF73_60,
        64: LOGO_SA_7C55BF73_64,
    },
    # SAC; source sha256 04705e41155cff001ef665e245cedeb00a6be81e664c538c0ef6e74ae79990d6
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/sac.png&h=50&w=50": {
        16: LOGO_SAC_529FCEC8_16,
        30: LOGO_SAC_529FCEC8_30,
        32: LOGO_SAC_529FCEC8_32,
        60: LOGO_SAC_529FCEC8_60,
        64: LOGO_SAC_529FCEC8_64,
    },
    # UTAH; source sha256 c847ab8eb931fe34b8164ddf952ca3cf30af3a80142d1b127bdddd24d60c787c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/utah.png&h=50&w=50": {
        16: LOGO_UTAH_FD22BC0F_16,
        30: LOGO_UTAH_FD22BC0F_30,
        32: LOGO_UTAH_FD22BC0F_32,
        60: LOGO_UTAH_FD22BC0F_60,
        64: LOGO_UTAH_FD22BC0F_64,
    },
    # WSH; source sha256 763465997fc4b5c7c27f53d72470a66cfac7ac81e5e822e89450e9047408c7d8
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/wsh.png&h=50&w=50": {
        14: LOGO_WSH_11DB2BCC_14,
        28: LOGO_WSH_11DB2BCC_28,
        30: LOGO_WSH_11DB2BCC_30,
        32: LOGO_WSH_11DB2BCC_32,
        60: LOGO_WSH_11DB2BCC_60,
        64: LOGO_WSH_11DB2BCC_64,
    },
    # PHI; source sha256 75f6476b7befdba60297a04dc6883fec5379e018271994ea7a931c1257e5f701
    "https://b.fssta.com/uploads/application/nba/team-logos/76ers.png": {
        14: LOGO_PHI_B5CE26FC_SOURCE,
        28: LOGO_PHI_B5CE26FC_SOURCE,
        30: LOGO_PHI_B5CE26FC_SOURCE,
        32: LOGO_PHI_B5CE26FC_SOURCE,
        60: LOGO_PHI_B5CE26FC_SOURCE,
        64: LOGO_PHI_B5CE26FC_SOURCE,
    },
    # TOR; source sha256 259619887eadba585d51ffa0d824c64825a37a9e9240c633afdc97cfe34b23d7
    "https://b.fssta.com/uploads/application/nba/team-logos/Raptors-alternate.png": {
        13: LOGO_TOR_C37CB97D_SOURCE,
        26: LOGO_TOR_C37CB97D_SOURCE,
        30: LOGO_TOR_C37CB97D_SOURCE,
        32: LOGO_TOR_C37CB97D_SOURCE,
        60: LOGO_TOR_C37CB97D_SOURCE,
        64: LOGO_TOR_C37CB97D_SOURCE,
    },
    # HOU; source sha256 e62f9abe43ddb7ac0aa67669f433f8e7f0e4a790b363a497eb1df781217ce34b
    "https://b.fssta.com/uploads/application/nba/team-logos/Rockets-alternate.png": {
        16: LOGO_HOU_4F592B68_16,
        30: LOGO_HOU_4F592B68_30,
        32: LOGO_HOU_4F592B68_32,
        60: LOGO_HOU_4F592B68_60,
        64: LOGO_HOU_4F592B68_64,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        13: LOGO_SHARED_BE6D5AAC_SOURCE,
        14: LOGO_SHARED_BE6D5AAC_SOURCE,
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        18: LOGO_SHARED_BE6D5AAC_SOURCE,
        24: LOGO_SHARED_BE6D5AAC_SOURCE,
        26: LOGO_SHARED_BE6D5AAC_SOURCE,
        28: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
        36: LOGO_SHARED_BE6D5AAC_SOURCE,
        48: LOGO_SHARED_BE6D5AAC_SOURCE,
        60: LOGO_SHARED_BE6D5AAC_SOURCE,
        64: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        13: LOGO_SHARED_3FDF1951_SOURCE,
        14: LOGO_SHARED_3FDF1951_SOURCE,
        16: LOGO_SHARED_3FDF1951_SOURCE,
        18: LOGO_SHARED_3FDF1951_SOURCE,
        24: LOGO_SHARED_3FDF1951_SOURCE,
        26: LOGO_SHARED_3FDF1951_SOURCE,
        28: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
        36: LOGO_SHARED_3FDF1951_SOURCE,
        48: LOGO_SHARED_3FDF1951_SOURCE,
        60: LOGO_SHARED_3FDF1951_SOURCE,
        64: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
