"""
Bundled team logos for nbastandings. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/atl-ba15ab80-10.png", LOGO_ATL_BA15AB80_10 = "file")
load("images/logos/bkn-2ea304b5-10.png", LOGO_BKN_2EA304B5_10 = "file")
load("images/logos/bos-1f08d3a2-10.png", LOGO_BOS_1F08D3A2_10 = "file")
load("images/logos/cha-e5aa7e29-10.png", LOGO_CHA_E5AA7E29_10 = "file")
load("images/logos/chi-4d72ecba-10.png", LOGO_CHI_4D72ECBA_10 = "file")
load("images/logos/cle-398f5431-10.png", LOGO_CLE_398F5431_10 = "file")
load("images/logos/dal-b6f9161a-10.png", LOGO_DAL_B6F9161A_10 = "file")
load("images/logos/den-7e361872-10.png", LOGO_DEN_7E361872_10 = "file")
load("images/logos/det-777ced85-10.png", LOGO_DET_777CED85_10 = "file")
load("images/logos/gs-766f1c19-10.png", LOGO_GS_766F1C19_10 = "file")
load("images/logos/hou-4f592b68-10.png", LOGO_HOU_4F592B68_10 = "file")
load("images/logos/ind-4fc23489-10.png", LOGO_IND_4FC23489_10 = "file")
load("images/logos/lac-55e51ad0-10.png", LOGO_LAC_55E51AD0_10 = "file")
load("images/logos/lal-5ab19ea3-10.png", LOGO_LAL_5AB19EA3_10 = "file")
load("images/logos/mem-93587f1a-10.png", LOGO_MEM_93587F1A_10 = "file")
load("images/logos/mia-cd4abee5-10.png", LOGO_MIA_CD4ABEE5_10 = "file")
load("images/logos/mil-23fc6fac-10.png", LOGO_MIL_23FC6FAC_10 = "file")
load("images/logos/min-5896cbe2-10.png", LOGO_MIN_5896CBE2_10 = "file")
load("images/logos/no-1bfbe29e-10.png", LOGO_NO_1BFBE29E_10 = "file")
load("images/logos/ny-4744f6a1-10.png", LOGO_NY_4744F6A1_10 = "file")
load("images/logos/okc-8d721def-10.png", LOGO_OKC_8D721DEF_10 = "file")
load("images/logos/orl-bdec3217-10.png", LOGO_ORL_BDEC3217_10 = "file")
load("images/logos/phi-b5ce26fc-source.png", LOGO_PHI_B5CE26FC_SOURCE = "file")
load("images/logos/phx-aff914ab-10.png", LOGO_PHX_AFF914AB_10 = "file")
load("images/logos/por-db7e6dd5-10.png", LOGO_POR_DB7E6DD5_10 = "file")
load("images/logos/sa-7c55bf73-10.png", LOGO_SA_7C55BF73_10 = "file")
load("images/logos/sac-529fcec8-10.png", LOGO_SAC_529FCEC8_10 = "file")
load("images/logos/tor-c37cb97d-source.png", LOGO_TOR_C37CB97D_SOURCE = "file")
load("images/logos/utah-fd22bc0f-10.png", LOGO_UTAH_FD22BC0F_10 = "file")
load("images/logos/wsh-11db2bcc-10.png", LOGO_WSH_11DB2BCC_10 = "file")

BUNDLED_LOGOS = {
    # ATL; source sha256 6d2d78b1e655c5563767118e5a693ad99ec56aac27a857e032db5f2bdfaa7fa5
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/atl.png&h=50&w=50": {
        10: LOGO_ATL_BA15AB80_10,
    },
    # BKN; source sha256 1e91bb43507c03b288b868a9d7d8fe2281a0462e2ce66e888fd67000149b3d14
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/bkn.png&h=50&w=50": {
        10: LOGO_BKN_2EA304B5_10,
    },
    # BOS; source sha256 de7dc1eb792e4d5e25b9982264eb0536c90344e58cad157e53ad1bf94fcca30c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/bos.png&h=50&w=50": {
        10: LOGO_BOS_1F08D3A2_10,
    },
    # CHA; source sha256 0df03231eace85957ec3e21b4e6c74b124ace8415f069b7db91abbfef06091ec
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/cha.png&h=50&w=50": {
        10: LOGO_CHA_E5AA7E29_10,
    },
    # CHI; source sha256 910bfc0a0c7f0455dd0517b96fe14588fe459f367279941b84b99cc6a119e020
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/chi.png&h=50&w=50": {
        10: LOGO_CHI_4D72ECBA_10,
    },
    # CLE; source sha256 63a8f54ee5a16938460e001d11a96bf34dfeb69e3f0d0c7e54e2574173265b6c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/cle.png&h=50&w=50": {
        10: LOGO_CLE_398F5431_10,
    },
    # DAL; source sha256 97767280b970fd1dc32caf2e6f55319f136c8638c8c5187296019096b4c35941
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/dal.png&h=50&w=50": {
        10: LOGO_DAL_B6F9161A_10,
    },
    # DEN; source sha256 6b52e77fdd0562deca9119bf4bc0cdd93e9f68bf4b56734e360313061deb32b3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/den.png&h=50&w=50": {
        10: LOGO_DEN_7E361872_10,
    },
    # DET; source sha256 3f35034fb4c03a8a2b812b4dcf7ba2c93c84ee8f300e29beb16d193a245831a3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/det.png&h=50&w=50": {
        10: LOGO_DET_777CED85_10,
    },
    # GS; source sha256 cfe943505590877100969a1a6921aa3e8ed33aa761a98a8b36155a38370fdc81
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/gs.png&h=50&w=50": {
        10: LOGO_GS_766F1C19_10,
    },
    # IND; source sha256 8216c090ab24564c38ca866a108ac2eedeacb8713cbfc5bc213d38d984d94f2d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/ind.png&h=50&w=50": {
        10: LOGO_IND_4FC23489_10,
    },
    # LAC; source sha256 14c30cb87adcc3bd1f7ca43cfe3aa3f6bae2118e426da55310db2965b9303b15
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/lac.png&h=50&w=50": {
        10: LOGO_LAC_55E51AD0_10,
    },
    # LAL; source sha256 c048a8100305c1340e18089007827f1d2a54eae254336522c27f225bf4c232e1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/lal.png&h=50&w=50": {
        10: LOGO_LAL_5AB19EA3_10,
    },
    # MEM; source sha256 4147eb3d2aaa0513f722f2a4c2a6854c8d7205ed5a8da38fd5815c7ede8b04ef
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mem.png&h=50&w=50": {
        10: LOGO_MEM_93587F1A_10,
    },
    # MIA; source sha256 0fb0f982d3dcfeb3fb599d385605cb6e15275db7f7ea060dd46ff1cd48564975
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mia.png&h=50&w=50": {
        10: LOGO_MIA_CD4ABEE5_10,
    },
    # MIL; source sha256 b6c796073ae4ed03d7816adee9198aa5027749015907dea5c31c219f88d7e7fa
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/mil.png&h=50&w=50": {
        10: LOGO_MIL_23FC6FAC_10,
    },
    # MIN; source sha256 400630b0d3b9b7e113d9c3f495693b432d6494a3ba96ff53a305914b9bfaaaff
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/min.png&h=50&w=50": {
        10: LOGO_MIN_5896CBE2_10,
    },
    # NO; source sha256 f579a9ddd5ebbe52cb7ae9667d6eaeacb83938efee8a368b9b1b21a83c917588
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/no.png&h=50&w=50": {
        10: LOGO_NO_1BFBE29E_10,
    },
    # NY; source sha256 8e38916af8d9e0cb997e3c30ded2c82dd52a046d250e1dfd3342b50a6cceb523
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/ny.png&h=50&w=50": {
        10: LOGO_NY_4744F6A1_10,
    },
    # OKC; source sha256 e90a1b5d9162fec2acd1e2439936aa557281d540d9184bbdf7646028a5e04a1d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/okc.png&h=50&w=50": {
        10: LOGO_OKC_8D721DEF_10,
    },
    # ORL; source sha256 3b05ddc52b36f694bac1033651fe502a8dbdbfbf82d05ce4c67bacaac935a89e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/orl.png&h=50&w=50": {
        10: LOGO_ORL_BDEC3217_10,
    },
    # PHX; source sha256 d48a6a862b6aa2a0ff1d14c8e101a8b3b9d92ee0dadab36be46ec0c48e8410ad
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/phx.png&h=50&w=50": {
        10: LOGO_PHX_AFF914AB_10,
    },
    # POR; source sha256 c6a0374db957e34891eb8ad10cbffb0435b677fa441be60d338553e818f1f23e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/por.png&h=50&w=50": {
        10: LOGO_POR_DB7E6DD5_10,
    },
    # SA; source sha256 e33cdb9d11762dce6ce6ef3b8996912a19260860d8b6a20679c1bc423b97260d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/sa.png&h=50&w=50": {
        10: LOGO_SA_7C55BF73_10,
    },
    # SAC; source sha256 04705e41155cff001ef665e245cedeb00a6be81e664c538c0ef6e74ae79990d6
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/sac.png&h=50&w=50": {
        10: LOGO_SAC_529FCEC8_10,
    },
    # UTAH; source sha256 c847ab8eb931fe34b8164ddf952ca3cf30af3a80142d1b127bdddd24d60c787c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/utah.png&h=50&w=50": {
        10: LOGO_UTAH_FD22BC0F_10,
    },
    # WSH; source sha256 763465997fc4b5c7c27f53d72470a66cfac7ac81e5e822e89450e9047408c7d8
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nba/500-dark/scoreboard/wsh.png&h=50&w=50": {
        10: LOGO_WSH_11DB2BCC_10,
    },
    # PHI; source sha256 75f6476b7befdba60297a04dc6883fec5379e018271994ea7a931c1257e5f701
    "https://b.fssta.com/uploads/application/nba/team-logos/76ers.png": {
        10: LOGO_PHI_B5CE26FC_SOURCE,
    },
    # TOR; source sha256 259619887eadba585d51ffa0d824c64825a37a9e9240c633afdc97cfe34b23d7
    "https://b.fssta.com/uploads/application/nba/team-logos/Raptors-alternate.png": {
        10: LOGO_TOR_C37CB97D_SOURCE,
    },
    # HOU; source sha256 e62f9abe43ddb7ac0aa67669f433f8e7f0e4a790b363a497eb1df781217ce34b
    "https://b.fssta.com/uploads/application/nba/team-logos/Rockets-alternate.png": {
        10: LOGO_HOU_4F592B68_10,
    },
}
