"""
Bundled team logos for nflscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/afc-a3bb1a23-16.png", LOGO_AFC_A3BB1A23_16 = "file")
load("images/logos/afc-a3bb1a23-30.png", LOGO_AFC_A3BB1A23_30 = "file")
load("images/logos/afc-a3bb1a23-32.png", LOGO_AFC_A3BB1A23_32 = "file")
load("images/logos/ari-82b3b730-16.png", LOGO_ARI_82B3B730_16 = "file")
load("images/logos/ari-82b3b730-30.png", LOGO_ARI_82B3B730_30 = "file")
load("images/logos/ari-82b3b730-32.png", LOGO_ARI_82B3B730_32 = "file")
load("images/logos/atl-e352bb0f-16.png", LOGO_ATL_E352BB0F_16 = "file")
load("images/logos/atl-e352bb0f-30.png", LOGO_ATL_E352BB0F_30 = "file")
load("images/logos/atl-e352bb0f-32.png", LOGO_ATL_E352BB0F_32 = "file")
load("images/logos/bal-a082919e-18.png", LOGO_BAL_A082919E_18 = "file")
load("images/logos/bal-a082919e-30.png", LOGO_BAL_A082919E_30 = "file")
load("images/logos/bal-a082919e-32.png", LOGO_BAL_A082919E_32 = "file")
load("images/logos/buf-09bbc869-16.png", LOGO_BUF_09BBC869_16 = "file")
load("images/logos/buf-09bbc869-30.png", LOGO_BUF_09BBC869_30 = "file")
load("images/logos/buf-09bbc869-32.png", LOGO_BUF_09BBC869_32 = "file")
load("images/logos/car-d0db149b-20.png", LOGO_CAR_D0DB149B_20 = "file")
load("images/logos/car-d0db149b-30.png", LOGO_CAR_D0DB149B_30 = "file")
load("images/logos/car-d0db149b-32.png", LOGO_CAR_D0DB149B_32 = "file")
load("images/logos/chi-e1900515-16.png", LOGO_CHI_E1900515_16 = "file")
load("images/logos/chi-e1900515-30.png", LOGO_CHI_E1900515_30 = "file")
load("images/logos/chi-e1900515-32.png", LOGO_CHI_E1900515_32 = "file")
load("images/logos/cin-d229b496-16.png", LOGO_CIN_D229B496_16 = "file")
load("images/logos/cin-d229b496-30.png", LOGO_CIN_D229B496_30 = "file")
load("images/logos/cin-d229b496-32.png", LOGO_CIN_D229B496_32 = "file")
load("images/logos/cle-f92238aa-16.png", LOGO_CLE_F92238AA_16 = "file")
load("images/logos/cle-f92238aa-30.png", LOGO_CLE_F92238AA_30 = "file")
load("images/logos/cle-f92238aa-32.png", LOGO_CLE_F92238AA_32 = "file")
load("images/logos/dal-401e4fff-18.png", LOGO_DAL_401E4FFF_18 = "file")
load("images/logos/dal-401e4fff-30.png", LOGO_DAL_401E4FFF_30 = "file")
load("images/logos/dal-401e4fff-32.png", LOGO_DAL_401E4FFF_32 = "file")
load("images/logos/den-ee4ea5af-18.png", LOGO_DEN_EE4EA5AF_18 = "file")
load("images/logos/den-ee4ea5af-30.png", LOGO_DEN_EE4EA5AF_30 = "file")
load("images/logos/den-ee4ea5af-32.png", LOGO_DEN_EE4EA5AF_32 = "file")
load("images/logos/det-aaaa9778-18.png", LOGO_DET_AAAA9778_18 = "file")
load("images/logos/det-aaaa9778-30.png", LOGO_DET_AAAA9778_30 = "file")
load("images/logos/det-aaaa9778-32.png", LOGO_DET_AAAA9778_32 = "file")
load("images/logos/gb-cb1a7315-18.png", LOGO_GB_CB1A7315_18 = "file")
load("images/logos/gb-cb1a7315-30.png", LOGO_GB_CB1A7315_30 = "file")
load("images/logos/gb-cb1a7315-32.png", LOGO_GB_CB1A7315_32 = "file")
load("images/logos/hou-0d8f15b3-16.png", LOGO_HOU_0D8F15B3_16 = "file")
load("images/logos/hou-0d8f15b3-30.png", LOGO_HOU_0D8F15B3_30 = "file")
load("images/logos/hou-0d8f15b3-32.png", LOGO_HOU_0D8F15B3_32 = "file")
load("images/logos/ind-71d6d189-14.png", LOGO_IND_71D6D189_14 = "file")
load("images/logos/ind-71d6d189-30.png", LOGO_IND_71D6D189_30 = "file")
load("images/logos/ind-71d6d189-32.png", LOGO_IND_71D6D189_32 = "file")
load("images/logos/jax-6bd08128-16.png", LOGO_JAX_6BD08128_16 = "file")
load("images/logos/jax-6bd08128-30.png", LOGO_JAX_6BD08128_30 = "file")
load("images/logos/jax-6bd08128-32.png", LOGO_JAX_6BD08128_32 = "file")
load("images/logos/kc-b99d7560-16.png", LOGO_KC_B99D7560_16 = "file")
load("images/logos/kc-b99d7560-30.png", LOGO_KC_B99D7560_30 = "file")
load("images/logos/kc-b99d7560-32.png", LOGO_KC_B99D7560_32 = "file")
load("images/logos/lac-ca5e6115-16.png", LOGO_LAC_CA5E6115_16 = "file")
load("images/logos/lac-ca5e6115-30.png", LOGO_LAC_CA5E6115_30 = "file")
load("images/logos/lac-ca5e6115-32.png", LOGO_LAC_CA5E6115_32 = "file")
load("images/logos/lar-a0fee72c-16.png", LOGO_LAR_A0FEE72C_16 = "file")
load("images/logos/lar-a0fee72c-30.png", LOGO_LAR_A0FEE72C_30 = "file")
load("images/logos/lar-a0fee72c-32.png", LOGO_LAR_A0FEE72C_32 = "file")
load("images/logos/lv-66992606-16.png", LOGO_LV_66992606_16 = "file")
load("images/logos/lv-66992606-30.png", LOGO_LV_66992606_30 = "file")
load("images/logos/lv-66992606-32.png", LOGO_LV_66992606_32 = "file")
load("images/logos/mia-30426be1-16.png", LOGO_MIA_30426BE1_16 = "file")
load("images/logos/mia-30426be1-30.png", LOGO_MIA_30426BE1_30 = "file")
load("images/logos/mia-30426be1-32.png", LOGO_MIA_30426BE1_32 = "file")
load("images/logos/min-61c472e6-16.png", LOGO_MIN_61C472E6_16 = "file")
load("images/logos/min-61c472e6-30.png", LOGO_MIN_61C472E6_30 = "file")
load("images/logos/min-61c472e6-32.png", LOGO_MIN_61C472E6_32 = "file")
load("images/logos/ne-ebfe8e52-16.png", LOGO_NE_EBFE8E52_16 = "file")
load("images/logos/ne-ebfe8e52-30.png", LOGO_NE_EBFE8E52_30 = "file")
load("images/logos/ne-ebfe8e52-32.png", LOGO_NE_EBFE8E52_32 = "file")
load("images/logos/nfc-184044a0-16.png", LOGO_NFC_184044A0_16 = "file")
load("images/logos/nfc-184044a0-30.png", LOGO_NFC_184044A0_30 = "file")
load("images/logos/nfc-184044a0-32.png", LOGO_NFC_184044A0_32 = "file")
load("images/logos/no-fd471dc4-16.png", LOGO_NO_FD471DC4_16 = "file")
load("images/logos/no-fd471dc4-30.png", LOGO_NO_FD471DC4_30 = "file")
load("images/logos/no-fd471dc4-32.png", LOGO_NO_FD471DC4_32 = "file")
load("images/logos/nyg-d1b15716-14.png", LOGO_NYG_D1B15716_14 = "file")
load("images/logos/nyg-d1b15716-30.png", LOGO_NYG_D1B15716_30 = "file")
load("images/logos/nyg-d1b15716-32.png", LOGO_NYG_D1B15716_32 = "file")
load("images/logos/nyj-b496c15e-16.png", LOGO_NYJ_B496C15E_16 = "file")
load("images/logos/nyj-b496c15e-30.png", LOGO_NYJ_B496C15E_30 = "file")
load("images/logos/nyj-b496c15e-32.png", LOGO_NYJ_B496C15E_32 = "file")
load("images/logos/phi-9fdf7516-16.png", LOGO_PHI_9FDF7516_16 = "file")
load("images/logos/phi-9fdf7516-30.png", LOGO_PHI_9FDF7516_30 = "file")
load("images/logos/phi-9fdf7516-32.png", LOGO_PHI_9FDF7516_32 = "file")
load("images/logos/pit-96886765-16.png", LOGO_PIT_96886765_16 = "file")
load("images/logos/pit-96886765-30.png", LOGO_PIT_96886765_30 = "file")
load("images/logos/pit-96886765-32.png", LOGO_PIT_96886765_32 = "file")
load("images/logos/sea-b953b6d4-16.png", LOGO_SEA_B953B6D4_16 = "file")
load("images/logos/sea-b953b6d4-30.png", LOGO_SEA_B953B6D4_30 = "file")
load("images/logos/sea-b953b6d4-32.png", LOGO_SEA_B953B6D4_32 = "file")
load("images/logos/sf-6ecde21b-18.png", LOGO_SF_6ECDE21B_18 = "file")
load("images/logos/sf-6ecde21b-30.png", LOGO_SF_6ECDE21B_30 = "file")
load("images/logos/sf-6ecde21b-32.png", LOGO_SF_6ECDE21B_32 = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/tb-ffe055f4-16.png", LOGO_TB_FFE055F4_16 = "file")
load("images/logos/tb-ffe055f4-30.png", LOGO_TB_FFE055F4_30 = "file")
load("images/logos/tb-ffe055f4-32.png", LOGO_TB_FFE055F4_32 = "file")
load("images/logos/ten-bb0019b3-14.png", LOGO_TEN_BB0019B3_14 = "file")
load("images/logos/ten-bb0019b3-30.png", LOGO_TEN_BB0019B3_30 = "file")
load("images/logos/ten-bb0019b3-32.png", LOGO_TEN_BB0019B3_32 = "file")
load("images/logos/wsh-a8f4b4df-16.png", LOGO_WSH_A8F4B4DF_16 = "file")
load("images/logos/wsh-a8f4b4df-30.png", LOGO_WSH_A8F4B4DF_30 = "file")
load("images/logos/wsh-a8f4b4df-32.png", LOGO_WSH_A8F4B4DF_32 = "file")

BUNDLED_LOGOS = {
    # ARI; source sha256 f870b58b43585a5b7717d578dd433b0b1e0c462d64ef4bea2aeb8c03f4ae7854
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/ari.png": {
        16: LOGO_ARI_82B3B730_16,
        30: LOGO_ARI_82B3B730_30,
        32: LOGO_ARI_82B3B730_32,
    },
    # ATL; source sha256 fe566e9da6f7986b2bac321571bd751247ff93af15c51ae555486fb1bee90c91
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/atl.png": {
        16: LOGO_ATL_E352BB0F_16,
        30: LOGO_ATL_E352BB0F_30,
        32: LOGO_ATL_E352BB0F_32,
    },
    # BAL; source sha256 67796023c172c9aeab5bcdac9204823d3590097246ad1cb92971134b5f26dcc0
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/bal.png": {
        18: LOGO_BAL_A082919E_18,
        30: LOGO_BAL_A082919E_30,
        32: LOGO_BAL_A082919E_32,
    },
    # BUF; source sha256 79b71e2f536ee29f9d23834e89828883af2d95bf6968cbd07a505444229cdd20
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/buf.png": {
        16: LOGO_BUF_09BBC869_16,
        30: LOGO_BUF_09BBC869_30,
        32: LOGO_BUF_09BBC869_32,
    },
    # CAR; source sha256 2cebc1bbdcfd89f28c1578b397f440d229d93fa9a30bfa1193cc286482c82298
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/car.png": {
        20: LOGO_CAR_D0DB149B_20,
        30: LOGO_CAR_D0DB149B_30,
        32: LOGO_CAR_D0DB149B_32,
    },
    # CHI; source sha256 fd7b5a207b9ad443f950b384d43dba6cb367c5737ad50a51a15e3893fa31753b
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/chi.png": {
        16: LOGO_CHI_E1900515_16,
        30: LOGO_CHI_E1900515_30,
        32: LOGO_CHI_E1900515_32,
    },
    # CIN; source sha256 8e549c0ecac92453140370b2aef3e4a140139b50d16e92507532e8ee49930d4e
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/cin.png": {
        16: LOGO_CIN_D229B496_16,
        30: LOGO_CIN_D229B496_30,
        32: LOGO_CIN_D229B496_32,
    },
    # CLE; source sha256 9b286fc4286dc39b1b5a6a08aab042b456ba5fdce99e45e49a4d1e2672411fa2
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/cle.png": {
        16: LOGO_CLE_F92238AA_16,
        30: LOGO_CLE_F92238AA_30,
        32: LOGO_CLE_F92238AA_32,
    },
    # DAL; source sha256 a4612d560386298a5fe5dbb9d1f62e208933b9442782a623bd4a6695e952db00
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/dal.png": {
        18: LOGO_DAL_401E4FFF_18,
        30: LOGO_DAL_401E4FFF_30,
        32: LOGO_DAL_401E4FFF_32,
    },
    # DEN; source sha256 6e7fd6ff89d3fa7f4ad4c914a49d71248144be3a86ee252dba4231db8c3897aa
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/den.png": {
        18: LOGO_DEN_EE4EA5AF_18,
        30: LOGO_DEN_EE4EA5AF_30,
        32: LOGO_DEN_EE4EA5AF_32,
    },
    # DET; source sha256 9776b567ebab0bd3640165e915d948d8e736e35967dfc19ce62b967cfe7b4eb1
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/det.png": {
        18: LOGO_DET_AAAA9778_18,
        30: LOGO_DET_AAAA9778_30,
        32: LOGO_DET_AAAA9778_32,
    },
    # GB; source sha256 d1eda281e4c4ff5bcb45a9186bbc906bc62262d4c30ac26950951e5f983319b7
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/gb.png": {
        18: LOGO_GB_CB1A7315_18,
        30: LOGO_GB_CB1A7315_30,
        32: LOGO_GB_CB1A7315_32,
    },
    # HOU; source sha256 54b0fe559761860e4953851c197d995b2f9c0c4e278164edda7b608ffd64f39b
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/hou.png": {
        16: LOGO_HOU_0D8F15B3_16,
        30: LOGO_HOU_0D8F15B3_30,
        32: LOGO_HOU_0D8F15B3_32,
    },
    # JAX; source sha256 15cb9a1c77ebfaea885d0d3a34f33dabc4e6a00eb7d5462148fceed641d49397
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/jax.png": {
        16: LOGO_JAX_6BD08128_16,
        30: LOGO_JAX_6BD08128_30,
        32: LOGO_JAX_6BD08128_32,
    },
    # KC; source sha256 3d77958dc6373768919bb2681cbe1b143f56c07a1f013460def665a5026a7f3d
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/kc.png": {
        16: LOGO_KC_B99D7560_16,
        30: LOGO_KC_B99D7560_30,
        32: LOGO_KC_B99D7560_32,
    },
    # LAC; source sha256 5400f85bd93129c056717a771da57a97225e15f39c0022107ce89ef993f15bb0
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/lac.png": {
        16: LOGO_LAC_CA5E6115_16,
        30: LOGO_LAC_CA5E6115_30,
        32: LOGO_LAC_CA5E6115_32,
    },
    # LV; source sha256 bf304e45470927517802cbfc53d38b167491f00ea0d007b38f3bd506fc53c7d2
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/lv.png": {
        16: LOGO_LV_66992606_16,
        30: LOGO_LV_66992606_30,
        32: LOGO_LV_66992606_32,
    },
    # MIA; source sha256 b9631269a82abda39bd748afc82390679ca67bfc167bc3581665e237407de8e0
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/mia.png": {
        16: LOGO_MIA_30426BE1_16,
        30: LOGO_MIA_30426BE1_30,
        32: LOGO_MIA_30426BE1_32,
    },
    # MIN; source sha256 ad12c95cdc282ff5f1ab1aa1005accc4ddd7d456e3b00c116a67478df1f5a600
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/min.png": {
        16: LOGO_MIN_61C472E6_16,
        30: LOGO_MIN_61C472E6_30,
        32: LOGO_MIN_61C472E6_32,
    },
    # NE; source sha256 dac19aa9a573dcf9075e2422bee3e35a4955b9ab494bb3191ab3bacfd3609729
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/ne.png": {
        16: LOGO_NE_EBFE8E52_16,
        30: LOGO_NE_EBFE8E52_30,
        32: LOGO_NE_EBFE8E52_32,
    },
    # NO; source sha256 68ddfdf1d7ee8317f1af083a0c6d59142a11e8af4dad73c3c50bbafc338e0a94
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/no.png": {
        16: LOGO_NO_FD471DC4_16,
        30: LOGO_NO_FD471DC4_30,
        32: LOGO_NO_FD471DC4_32,
    },
    # NYG; source sha256 5a772c3ec7eb3ebb22a521d67b6ec3a6892feabf46a1b80a74765c351a400a8f
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/nyg.png": {
        14: LOGO_NYG_D1B15716_14,
        30: LOGO_NYG_D1B15716_30,
        32: LOGO_NYG_D1B15716_32,
    },
    # NYJ; source sha256 3a3dee610cf5a74de8ab92c07349a938b6a76140ad8c8a4c4ab0065714eff246
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/nyj.png": {
        16: LOGO_NYJ_B496C15E_16,
        30: LOGO_NYJ_B496C15E_30,
        32: LOGO_NYJ_B496C15E_32,
    },
    # PHI; source sha256 2875f50f8b756ed5ea3866105b4683f5c603aa542e2c7f7870287e1d3d006100
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/phi.png": {
        16: LOGO_PHI_9FDF7516_16,
        30: LOGO_PHI_9FDF7516_30,
        32: LOGO_PHI_9FDF7516_32,
    },
    # PIT; source sha256 806bcb72e75ed184a99bea34df458e6cd87145fc9a863945f3356b01122aeb6f
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/pit.png": {
        16: LOGO_PIT_96886765_16,
        30: LOGO_PIT_96886765_30,
        32: LOGO_PIT_96886765_32,
    },
    # SEA; source sha256 2546b1d4fe5cf6c2d75cda53d3fb56bbc4dd43c6b00200586dab5a85df8fa492
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/sea.png": {
        16: LOGO_SEA_B953B6D4_16,
        30: LOGO_SEA_B953B6D4_30,
        32: LOGO_SEA_B953B6D4_32,
    },
    # SF; source sha256 82ae812f6c15718ce5abdd402863e8b4553fa9971e4baa5d45ff585c52948a45
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/sf.png": {
        18: LOGO_SF_6ECDE21B_18,
        30: LOGO_SF_6ECDE21B_30,
        32: LOGO_SF_6ECDE21B_32,
    },
    # TB; source sha256 bcc5d267024650938c9f35558077fe00a31913b89c61768d4ebb63d1ea31fbfd
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/tb.png": {
        16: LOGO_TB_FFE055F4_16,
        30: LOGO_TB_FFE055F4_30,
        32: LOGO_TB_FFE055F4_32,
    },
    # TEN; source sha256 27cf283fca5b2e9e1c5e995a465a54223424c157d2013b603a6491f99333cf45
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/ten.png": {
        14: LOGO_TEN_BB0019B3_14,
        30: LOGO_TEN_BB0019B3_30,
        32: LOGO_TEN_BB0019B3_32,
    },
    # WSH; source sha256 2f67805ef9e385a4c67adb0a9320706bd481a52e3aa0e0faea995dad2b501112
    "https://a.espncdn.com/i/teamlogos/nfl/500-dark/scoreboard/wsh.png": {
        16: LOGO_WSH_A8F4B4DF_16,
        30: LOGO_WSH_A8F4B4DF_30,
        32: LOGO_WSH_A8F4B4DF_32,
    },
    # AFC; source sha256 0fb1be8c7b9128044b418e8d32e9fe24fc1c5b50168423a248402ef46d108a59
    "https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/afc.png": {
        16: LOGO_AFC_A3BB1A23_16,
        30: LOGO_AFC_A3BB1A23_30,
        32: LOGO_AFC_A3BB1A23_32,
    },
    # NFC; source sha256 14d536fa549a484f22f7dab352b80cf069cd04c37b8f63e4efe51dfbbfe002dc
    "https://a.espncdn.com/i/teamlogos/nfl/500/scoreboard/nfc.png": {
        16: LOGO_NFC_184044A0_16,
        30: LOGO_NFC_184044A0_30,
        32: LOGO_NFC_184044A0_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        14: LOGO_SHARED_BE6D5AAC_SOURCE,
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        18: LOGO_SHARED_BE6D5AAC_SOURCE,
        20: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
    # IND; source sha256 c59105ddaf13f73f07b5db09ddc3b542278a71f6a3a88024efa31241e27e6e4e
    "images/colts.png": {
        14: LOGO_IND_71D6D189_14,
        30: LOGO_IND_71D6D189_30,
        32: LOGO_IND_71D6D189_32,
    },
    # LAR; source sha256 5fd379a7bbc4958605f66e512af89b8819cea8b81f19e9b0408b17bca2d0ba6b
    "images/lar.png": {
        16: LOGO_LAR_A0FEE72C_16,
        30: LOGO_LAR_A0FEE72C_30,
        32: LOGO_LAR_A0FEE72C_32,
    },
}
