"""
Bundled team logos for nhlscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/ana-d2bacf80-18.png", LOGO_ANA_D2BACF80_18 = "file")
load("images/logos/ana-d2bacf80-30.png", LOGO_ANA_D2BACF80_30 = "file")
load("images/logos/ana-d2bacf80-32.png", LOGO_ANA_D2BACF80_32 = "file")
load("images/logos/bos-5f1969ea-16.png", LOGO_BOS_5F1969EA_16 = "file")
load("images/logos/bos-5f1969ea-30.png", LOGO_BOS_5F1969EA_30 = "file")
load("images/logos/bos-5f1969ea-32.png", LOGO_BOS_5F1969EA_32 = "file")
load("images/logos/buf-5a8095ba-16.png", LOGO_BUF_5A8095BA_16 = "file")
load("images/logos/buf-5a8095ba-30.png", LOGO_BUF_5A8095BA_30 = "file")
load("images/logos/buf-5a8095ba-32.png", LOGO_BUF_5A8095BA_32 = "file")
load("images/logos/car-0a3c909b-18.png", LOGO_CAR_0A3C909B_18 = "file")
load("images/logos/car-0a3c909b-30.png", LOGO_CAR_0A3C909B_30 = "file")
load("images/logos/car-0a3c909b-32.png", LOGO_CAR_0A3C909B_32 = "file")
load("images/logos/cbj-138cb90c-18.png", LOGO_CBJ_138CB90C_18 = "file")
load("images/logos/cbj-138cb90c-30.png", LOGO_CBJ_138CB90C_30 = "file")
load("images/logos/cbj-138cb90c-32.png", LOGO_CBJ_138CB90C_32 = "file")
load("images/logos/cgy-f2b875a7-16.png", LOGO_CGY_F2B875A7_16 = "file")
load("images/logos/cgy-f2b875a7-30.png", LOGO_CGY_F2B875A7_30 = "file")
load("images/logos/cgy-f2b875a7-32.png", LOGO_CGY_F2B875A7_32 = "file")
load("images/logos/chi-c8b335e6-16.png", LOGO_CHI_C8B335E6_16 = "file")
load("images/logos/chi-c8b335e6-30.png", LOGO_CHI_C8B335E6_30 = "file")
load("images/logos/chi-c8b335e6-32.png", LOGO_CHI_C8B335E6_32 = "file")
load("images/logos/col-f964950e-16.png", LOGO_COL_F964950E_16 = "file")
load("images/logos/col-f964950e-30.png", LOGO_COL_F964950E_30 = "file")
load("images/logos/col-f964950e-32.png", LOGO_COL_F964950E_32 = "file")
load("images/logos/dal-483b1fdc-18.png", LOGO_DAL_483B1FDC_18 = "file")
load("images/logos/dal-483b1fdc-30.png", LOGO_DAL_483B1FDC_30 = "file")
load("images/logos/dal-483b1fdc-32.png", LOGO_DAL_483B1FDC_32 = "file")
load("images/logos/det-9ad8248f-18.png", LOGO_DET_9AD8248F_18 = "file")
load("images/logos/det-9ad8248f-30.png", LOGO_DET_9AD8248F_30 = "file")
load("images/logos/det-9ad8248f-32.png", LOGO_DET_9AD8248F_32 = "file")
load("images/logos/edm-1a7c2be6-16.png", LOGO_EDM_1A7C2BE6_16 = "file")
load("images/logos/edm-1a7c2be6-30.png", LOGO_EDM_1A7C2BE6_30 = "file")
load("images/logos/edm-1a7c2be6-32.png", LOGO_EDM_1A7C2BE6_32 = "file")
load("images/logos/fla-a4e46dc0-16.png", LOGO_FLA_A4E46DC0_16 = "file")
load("images/logos/fla-a4e46dc0-30.png", LOGO_FLA_A4E46DC0_30 = "file")
load("images/logos/fla-a4e46dc0-32.png", LOGO_FLA_A4E46DC0_32 = "file")
load("images/logos/la-58d8986d-16.png", LOGO_LA_58D8986D_16 = "file")
load("images/logos/la-58d8986d-30.png", LOGO_LA_58D8986D_30 = "file")
load("images/logos/la-58d8986d-32.png", LOGO_LA_58D8986D_32 = "file")
load("images/logos/min-0fc5df48-18.png", LOGO_MIN_0FC5DF48_18 = "file")
load("images/logos/min-0fc5df48-30.png", LOGO_MIN_0FC5DF48_30 = "file")
load("images/logos/min-0fc5df48-32.png", LOGO_MIN_0FC5DF48_32 = "file")
load("images/logos/mtl-c4003a06-16.png", LOGO_MTL_C4003A06_16 = "file")
load("images/logos/mtl-c4003a06-30.png", LOGO_MTL_C4003A06_30 = "file")
load("images/logos/mtl-c4003a06-32.png", LOGO_MTL_C4003A06_32 = "file")
load("images/logos/nj-ab49a0db-16.png", LOGO_NJ_AB49A0DB_16 = "file")
load("images/logos/nj-ab49a0db-30.png", LOGO_NJ_AB49A0DB_30 = "file")
load("images/logos/nj-ab49a0db-32.png", LOGO_NJ_AB49A0DB_32 = "file")
load("images/logos/nsh-a5ffd95c-18.png", LOGO_NSH_A5FFD95C_18 = "file")
load("images/logos/nsh-a5ffd95c-30.png", LOGO_NSH_A5FFD95C_30 = "file")
load("images/logos/nsh-a5ffd95c-32.png", LOGO_NSH_A5FFD95C_32 = "file")
load("images/logos/nyi-8b7b0673-16.png", LOGO_NYI_8B7B0673_16 = "file")
load("images/logos/nyi-8b7b0673-30.png", LOGO_NYI_8B7B0673_30 = "file")
load("images/logos/nyi-8b7b0673-32.png", LOGO_NYI_8B7B0673_32 = "file")
load("images/logos/nyr-ea22a428-16.png", LOGO_NYR_EA22A428_16 = "file")
load("images/logos/nyr-ea22a428-30.png", LOGO_NYR_EA22A428_30 = "file")
load("images/logos/nyr-ea22a428-32.png", LOGO_NYR_EA22A428_32 = "file")
load("images/logos/ott-5b89533a-16.png", LOGO_OTT_5B89533A_16 = "file")
load("images/logos/ott-5b89533a-30.png", LOGO_OTT_5B89533A_30 = "file")
load("images/logos/ott-5b89533a-32.png", LOGO_OTT_5B89533A_32 = "file")
load("images/logos/phi-0726e00f-16.png", LOGO_PHI_0726E00F_16 = "file")
load("images/logos/phi-0726e00f-30.png", LOGO_PHI_0726E00F_30 = "file")
load("images/logos/phi-0726e00f-32.png", LOGO_PHI_0726E00F_32 = "file")
load("images/logos/pit-1a9df964-16.png", LOGO_PIT_1A9DF964_16 = "file")
load("images/logos/pit-1a9df964-30.png", LOGO_PIT_1A9DF964_30 = "file")
load("images/logos/pit-1a9df964-32.png", LOGO_PIT_1A9DF964_32 = "file")
load("images/logos/sea-e7d2b461-18.png", LOGO_SEA_E7D2B461_18 = "file")
load("images/logos/sea-e7d2b461-30.png", LOGO_SEA_E7D2B461_30 = "file")
load("images/logos/sea-e7d2b461-32.png", LOGO_SEA_E7D2B461_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/sj-2fb514b6-18.png", LOGO_SJ_2FB514B6_18 = "file")
load("images/logos/sj-2fb514b6-30.png", LOGO_SJ_2FB514B6_30 = "file")
load("images/logos/sj-2fb514b6-32.png", LOGO_SJ_2FB514B6_32 = "file")
load("images/logos/stl-73ab8d16-16.png", LOGO_STL_73AB8D16_16 = "file")
load("images/logos/stl-73ab8d16-30.png", LOGO_STL_73AB8D16_30 = "file")
load("images/logos/stl-73ab8d16-32.png", LOGO_STL_73AB8D16_32 = "file")
load("images/logos/tb-fb91408c-16.png", LOGO_TB_FB91408C_16 = "file")
load("images/logos/tb-fb91408c-30.png", LOGO_TB_FB91408C_30 = "file")
load("images/logos/tb-fb91408c-32.png", LOGO_TB_FB91408C_32 = "file")
load("images/logos/tor-d6e51880-18.png", LOGO_TOR_D6E51880_18 = "file")
load("images/logos/tor-d6e51880-30.png", LOGO_TOR_D6E51880_30 = "file")
load("images/logos/tor-d6e51880-32.png", LOGO_TOR_D6E51880_32 = "file")
load("images/logos/uta-9c5afc2e-16.png", LOGO_UTA_9C5AFC2E_16 = "file")
load("images/logos/uta-9c5afc2e-30.png", LOGO_UTA_9C5AFC2E_30 = "file")
load("images/logos/uta-9c5afc2e-32.png", LOGO_UTA_9C5AFC2E_32 = "file")
load("images/logos/van-f4b04e31-16.png", LOGO_VAN_F4B04E31_16 = "file")
load("images/logos/van-f4b04e31-30.png", LOGO_VAN_F4B04E31_30 = "file")
load("images/logos/van-f4b04e31-32.png", LOGO_VAN_F4B04E31_32 = "file")
load("images/logos/vgk-ed607c3c-16.png", LOGO_VGK_ED607C3C_16 = "file")
load("images/logos/vgk-ed607c3c-30.png", LOGO_VGK_ED607C3C_30 = "file")
load("images/logos/vgk-ed607c3c-32.png", LOGO_VGK_ED607C3C_32 = "file")
load("images/logos/wpg-8ae12a63-16.png", LOGO_WPG_8AE12A63_16 = "file")
load("images/logos/wpg-8ae12a63-30.png", LOGO_WPG_8AE12A63_30 = "file")
load("images/logos/wpg-8ae12a63-32.png", LOGO_WPG_8AE12A63_32 = "file")
load("images/logos/wsh-d626503e-16.png", LOGO_WSH_D626503E_16 = "file")
load("images/logos/wsh-d626503e-30.png", LOGO_WSH_D626503E_30 = "file")
load("images/logos/wsh-d626503e-32.png", LOGO_WSH_D626503E_32 = "file")

BUNDLED_LOGOS = {
    # ANA; source sha256 d164d7a83e183bd1ba7591d5d8b10a4eb73572f5b10c59cb7a2f5cfc1022bf9e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/ana.png&h=50&w=50": {
        18: LOGO_ANA_D2BACF80_18,
        30: LOGO_ANA_D2BACF80_30,
        32: LOGO_ANA_D2BACF80_32,
    },
    # BOS; source sha256 2d16749a0d7ca74121787f2e574b206c56ac0c2362b73005df20135af5f3964f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/bos.png&h=50&w=50": {
        16: LOGO_BOS_5F1969EA_16,
        30: LOGO_BOS_5F1969EA_30,
        32: LOGO_BOS_5F1969EA_32,
    },
    # BUF; source sha256 a43a4398105cebe6965d97332c3973d7ece4b2ad85c50fdebd412613e6838b0e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/buf.png&h=50&w=50": {
        16: LOGO_BUF_5A8095BA_16,
        30: LOGO_BUF_5A8095BA_30,
        32: LOGO_BUF_5A8095BA_32,
    },
    # CAR; source sha256 03b5d330bc8d901400549b94edb950a1cad1ccc06d91cde1bdf57c9865bdb14c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/car.png&h=50&w=50": {
        18: LOGO_CAR_0A3C909B_18,
        30: LOGO_CAR_0A3C909B_30,
        32: LOGO_CAR_0A3C909B_32,
    },
    # CBJ; source sha256 cd269bc231d171038bdb1bc421527bdb7e69695bd427d88fcc71a583afb601bc
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/cbj.png&h=50&w=50": {
        18: LOGO_CBJ_138CB90C_18,
        30: LOGO_CBJ_138CB90C_30,
        32: LOGO_CBJ_138CB90C_32,
    },
    # CGY; source sha256 634da8e023ee12deec5590736019723526b8372054395fb2c5b5771549182de0
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/cgy.png&h=50&w=50": {
        16: LOGO_CGY_F2B875A7_16,
        30: LOGO_CGY_F2B875A7_30,
        32: LOGO_CGY_F2B875A7_32,
    },
    # CHI; source sha256 af74f3bdbd0a2bd756c22c02a493dda6456b0bf53552ed85a695521ba9a7083a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/chi.png&h=50&w=50": {
        16: LOGO_CHI_C8B335E6_16,
        30: LOGO_CHI_C8B335E6_30,
        32: LOGO_CHI_C8B335E6_32,
    },
    # COL; source sha256 0c712109c65dca4806f1b0bbec8f22c646abbd7fc09823cab5697a4cef62daa5
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/col.png&h=50&w=50": {
        16: LOGO_COL_F964950E_16,
        30: LOGO_COL_F964950E_30,
        32: LOGO_COL_F964950E_32,
    },
    # DAL; source sha256 26bf4a32559badf98c99133e925b600050b84e1f53e33137228011bc47148996
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/dal.png&h=50&w=50": {
        18: LOGO_DAL_483B1FDC_18,
        30: LOGO_DAL_483B1FDC_30,
        32: LOGO_DAL_483B1FDC_32,
    },
    # DET; source sha256 85f6bc381757e23beb39b3c7d8c53e3dc690a8a301b36ae03e211ebf3718fbe9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/det.png&h=50&w=50": {
        18: LOGO_DET_9AD8248F_18,
        30: LOGO_DET_9AD8248F_30,
        32: LOGO_DET_9AD8248F_32,
    },
    # EDM; source sha256 c342ffe6e9112e4efa475c325fac7b7a12ba36eb09cf8465a14712b6c8ff86cf
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/edm.png&h=50&w=50": {
        16: LOGO_EDM_1A7C2BE6_16,
        30: LOGO_EDM_1A7C2BE6_30,
        32: LOGO_EDM_1A7C2BE6_32,
    },
    # FLA; source sha256 ba4636d4567b5fe3bbdbaa39398afe9c404dcfd7e9e7ad4f042e978acc37db66
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/fla.png&h=50&w=50": {
        16: LOGO_FLA_A4E46DC0_16,
        30: LOGO_FLA_A4E46DC0_30,
        32: LOGO_FLA_A4E46DC0_32,
    },
    # LA; source sha256 f11c5bec153904b42bf31b17c473857211d44efabc412a4ec97f06f9c3138615
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/la.png&h=50&w=50": {
        16: LOGO_LA_58D8986D_16,
        30: LOGO_LA_58D8986D_30,
        32: LOGO_LA_58D8986D_32,
    },
    # MIN; source sha256 554d739c0ac58beac99e6c632b972a95a7a961f52457de04005963ae4fdd8e3d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/min.png&h=50&w=50": {
        18: LOGO_MIN_0FC5DF48_18,
        30: LOGO_MIN_0FC5DF48_30,
        32: LOGO_MIN_0FC5DF48_32,
    },
    # MTL; source sha256 9169e050e57c468468309203b8d09ddc15cd8a1b3a03207980830d7fb62f46ce
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/mtl.png&h=50&w=50": {
        16: LOGO_MTL_C4003A06_16,
        30: LOGO_MTL_C4003A06_30,
        32: LOGO_MTL_C4003A06_32,
    },
    # NJ; source sha256 749f26f5a1e1de08b76e19788c65583dcf3a38bb9f9b61e6688e34f897475975
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/nj.png&h=50&w=50": {
        16: LOGO_NJ_AB49A0DB_16,
        30: LOGO_NJ_AB49A0DB_30,
        32: LOGO_NJ_AB49A0DB_32,
    },
    # NSH; source sha256 d19dd091cbf537c8764735423a53f089b7fb2e874d1a8eda032e62e1684d4255
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/nsh.png&h=50&w=50": {
        18: LOGO_NSH_A5FFD95C_18,
        30: LOGO_NSH_A5FFD95C_30,
        32: LOGO_NSH_A5FFD95C_32,
    },
    # NYI; source sha256 43a13b16597eb6bc9d311ec0ab91ece65d71040abc47554c9fdfd52b4aa576d2
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/nyi.png&h=50&w=50": {
        16: LOGO_NYI_8B7B0673_16,
        30: LOGO_NYI_8B7B0673_30,
        32: LOGO_NYI_8B7B0673_32,
    },
    # NYR; source sha256 45cb0c7cbc756d227667faded804ff9edf4debb3b41b9979ba54d56c8d74b54c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/nyr.png&h=50&w=50": {
        16: LOGO_NYR_EA22A428_16,
        30: LOGO_NYR_EA22A428_30,
        32: LOGO_NYR_EA22A428_32,
    },
    # OTT; source sha256 2351f885512240a5a896162ecb2ef34c83055c41bd07cb116de6490f438a3774
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/ott.png&h=50&w=50": {
        16: LOGO_OTT_5B89533A_16,
        30: LOGO_OTT_5B89533A_30,
        32: LOGO_OTT_5B89533A_32,
    },
    # PHI; source sha256 62e7def3be5291feb325113afb01829bcc0d1816c33d207d5fe56f64f3283de3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/phi.png&h=50&w=50": {
        16: LOGO_PHI_0726E00F_16,
        30: LOGO_PHI_0726E00F_30,
        32: LOGO_PHI_0726E00F_32,
    },
    # PIT; source sha256 6dd798c9eb95e825ea92b297e06f1a3c149eb191cf86a1fd5af17f71fbdc0964
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/pit.png&h=50&w=50": {
        16: LOGO_PIT_1A9DF964_16,
        30: LOGO_PIT_1A9DF964_30,
        32: LOGO_PIT_1A9DF964_32,
    },
    # SEA; source sha256 d236ec262d39f63890c512e4cdd063b77398a5edc656741dc9492dc242f977ed
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/sea.png&h=50&w=50": {
        18: LOGO_SEA_E7D2B461_18,
        30: LOGO_SEA_E7D2B461_30,
        32: LOGO_SEA_E7D2B461_32,
    },
    # SJ; source sha256 c4979ac5ec95e8a7df15f94d9867076e95d6a44b6c65f21f9d57d00f3e7661d1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/sj.png&h=50&w=50": {
        18: LOGO_SJ_2FB514B6_18,
        30: LOGO_SJ_2FB514B6_30,
        32: LOGO_SJ_2FB514B6_32,
    },
    # STL; source sha256 055e5fac81f27a811fcee4c50f788bb92245a075f34d155eab5c9bd009d64653
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/stl.png&h=50&w=50": {
        16: LOGO_STL_73AB8D16_16,
        30: LOGO_STL_73AB8D16_30,
        32: LOGO_STL_73AB8D16_32,
    },
    # TB; source sha256 54e817c3ad171da5324fb3d54cd4c35d52555068f30074e9a0a2867f09bc1db9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/tb.png&h=50&w=50": {
        16: LOGO_TB_FB91408C_16,
        30: LOGO_TB_FB91408C_30,
        32: LOGO_TB_FB91408C_32,
    },
    # TOR; source sha256 656ac414536e5d817fcead3eb93ef73f11eaa83138da185fbb2f5701daa6a738
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/tor.png&h=50&w=50": {
        18: LOGO_TOR_D6E51880_18,
        30: LOGO_TOR_D6E51880_30,
        32: LOGO_TOR_D6E51880_32,
    },
    # UTA; source sha256 3796b67391cf22808cb5efa2f46068163870e4913c3798d853e7038d141188fb
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/uta.png&h=50&w=50": {
        16: LOGO_UTA_9C5AFC2E_16,
        30: LOGO_UTA_9C5AFC2E_30,
        32: LOGO_UTA_9C5AFC2E_32,
    },
    # VAN; source sha256 08778e606abf05fbf7effb7d28896c0dda2381ea959dfbe94c9fc0b12da56f2c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/van.png&h=50&w=50": {
        16: LOGO_VAN_F4B04E31_16,
        30: LOGO_VAN_F4B04E31_30,
        32: LOGO_VAN_F4B04E31_32,
    },
    # VGK; source sha256 d2e7eba6f3162a4d3bc7d39bab62e0ea2bb0b451d68a6055516fa4c6eb803eb0
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/vgk.png&h=50&w=50": {
        16: LOGO_VGK_ED607C3C_16,
        30: LOGO_VGK_ED607C3C_30,
        32: LOGO_VGK_ED607C3C_32,
    },
    # WPG; source sha256 f03c1877c2694bf3c8b33c379d759ece59dc626dd60e824522245c90b892fe19
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/wpg.png&h=50&w=50": {
        16: LOGO_WPG_8AE12A63_16,
        30: LOGO_WPG_8AE12A63_30,
        32: LOGO_WPG_8AE12A63_32,
    },
    # WSH; source sha256 de098f750ba2d4e79183f9ee3dd5e963271b4c491d0792932100acc28db2637e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/nhl/500-dark/scoreboard/wsh.png&h=50&w=50": {
        16: LOGO_WSH_D626503E_16,
        30: LOGO_WSH_D626503E_30,
        32: LOGO_WSH_D626503E_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        18: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        18: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
