#!/usr/bin/env python3
"""Bundle pre-resized team logos for the LunchBox8484 college sports apps.

    python3 tools/college_logos/build.py --runtime /path/to/niblet [--cache DIR] [app ...]

For each app this:

1. collects candidate teams (abbreviation and the logo URL the ESPN feed
   reports) from ESPN's team lists or sampled scoreboards;
2. asks the app itself, through the runtime, which URL it would fetch for each
   team (`get_logo_source`) and at which sizes it draws it;
3. downloads each original once and resizes it with the runtime's own image
   semantics (Go `image.Decode` plus `nfnt/resize` nearest neighbour, see
   `resize/main.go`), keeping only results whose decoded pixels are identical;
4. writes `apps/<app>/logos/logos.bin` (the PNGs back to back), `index.json`
   (URL -> drawn size -> [start, end) byte range in logos.bin) and
   `sources.json` (provenance: origin URL, SHA-256 of the original download and
   the bundled sizes). One pack and one index keep the per-render cost to two
   file loads.

Apps draw a bundled logo only when the requested URL and size match exactly,
and fall back to the original cached HTTP fetch otherwise.
"""
import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOOL = Path(__file__).resolve().parent
SEASON = "2026"
SITE = "https://site.api.espn.com/apis/site/v2/sports/"
CORE = "https://sports.core.api.espn.com/v2/sports/"

# kind "scores" draws logos at get_logoSize(team), 30 and 32 pixels;
# kind "standings" draws them at 10 pixels.
APPS = {
    "ncaafscores": ("scores", "football", "college-football", {"groups": ["80", "81"]},
                    "every FBS and FCS team (ESPN groups 80 and 81, 2026 season): the Top 25, FBS and FCS feeds and every conference option except Division II/III"),
    "ncaafstandings": ("standings", "football", "college-football", {"groups": ["80"]},
                       "every FBS team (ESPN group 80, 2026 season): all conference and Top 25 options"),
    "ncaamscores": ("scores", "basketball", "mens-college-basketball", {"groups": ["50"]},
                    "every Division I team (ESPN group 50, 2026 season): every conference option"),
    "ncaamstandings": ("standings", "basketball", "mens-college-basketball", {"groups": ["50"]},
                       "every Division I team (ESPN group 50, 2026 season): every conference and Top 25 option"),
    "ncaawscores": ("scores", "basketball", "womens-college-basketball", {"groups": ["50"]},
                    "every Division I team (ESPN group 50, 2026 season): every conference option"),
    "ncaawstandings": ("standings", "basketball", "womens-college-basketball", {"groups": ["50"]},
                       "every Division I team (ESPN group 50, 2026 season): every conference and Top 25 option"),
    # ESPN reports college baseball logos as per-team GUID URLs, so candidates
    # come from scoreboards sampled every third day of the 2026 season.
    "ncaabscores": ("scores", "baseball", "college-baseball", {"scoreboards": ("20260213", "20260621", 3, 2)},
                    "every team on at least two of the 2026 scoreboards sampled every third day from 13 February to 21 June"),
}
TRANSPARENT = "https://i.ibb.co/5LMp8T1/transparent.png"
README = """# Bundled team logos

Generated by `tools/college_logos/build.py` on %(date)s. Do not edit by hand.

`logos.bin` holds %(images)d PNGs (%(bytes)d bytes) for %(count)d logo URLs: %(selection)s,
plus the app's transparent placeholder. Each PNG is the image at a URL the app
already requested, resized to a size the app draws (%(sizes)s pixels) with the
runtime's own decoder and nearest-neighbour resize, so drawing it is
pixel-identical to fetching and resizing the URL. `index.json` maps each URL and
drawn size to a byte range of `logos.bin`; `sources.json` records each origin
URL and the SHA-256 of the downloaded original. Any other team, URL or size
still uses the app's original cached request.

These images are copies of the artwork the original app already displays, not
new or changed designs. Team names and logos are trademarks of their respective
institutions and remain their property; the copies are reproduced from ESPN's
and the other image hosts referenced by the original source. Bundling changes
where the images are stored, not whose they are: their trademark and licensing
status needs review before distribution and is not covered by this repository's
license.

To refresh after a rebrand, run `python3 tools/college_logos/build.py --runtime
<niblet> <app>` and verify the output as described in that script.
"""


class Store:
    """Content store keyed by SHA-256 of the URL (same layout as the parity fixtures)."""

    def __init__(self, path):
        self.path = Path(path)
        self.path.mkdir(parents=True, exist_ok=True)
        self.index_path = self.path / "index.json"
        self.index = json.loads(self.index_path.read_text()) if self.index_path.exists() else {}

    def get(self, url):
        key = hashlib.sha256(url.encode()).hexdigest()
        if key not in self.index:
            request = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
            try:
                with urllib.request.urlopen(request, timeout=30) as response:
                    status, body, kind = response.status, response.read(), response.headers.get("Content-Type", "")
            except urllib.error.HTTPError as error:
                status, body, kind = error.code, error.read(), error.headers.get("Content-Type", "")
            (self.path / key).write_bytes(body)
            self.index[key] = {"url": url, "fetched": url, "status": status, "type": kind}
            self.index_path.write_text(json.dumps(self.index, indent=1, sort_keys=True))
        meta = self.index[key]
        return meta["status"], self.path / key


def fetch_json(store, url):
    status, path = store.get(url)
    if status != 200:
        raise SystemExit("%s returned %d" % (url, status))
    return json.loads(path.read_bytes())


def group_candidates(store, sport, league, groups):
    teams = fetch_json(store, SITE + "%s/%s/teams?limit=1000" % (sport, league))
    by_id = {t["team"]["id"]: t["team"] for t in teams["sports"][0]["leagues"][0]["teams"]}
    candidates = []
    for group in groups:
        listing = fetch_json(store, CORE + "%s/leagues/%s/seasons/%s/types/2/groups/%s/teams?limit=500" % (sport, league, SEASON, group))
        for item in listing["items"]:
            team = by_id.get(item["$ref"].split("/teams/")[1].split("?")[0])
            if team and team.get("logos"):
                candidates.append((team["abbreviation"], team["logos"][0]["href"]))
    return candidates


def scoreboard_candidates(store, sport, league, spec):
    start, end, step_days, minimum = spec
    day = time.mktime(time.strptime(start, "%Y%m%d"))
    last = time.mktime(time.strptime(end, "%Y%m%d"))
    seen = Counter()
    while day <= last:
        stamp = time.strftime("%Y%m%d", time.localtime(day))
        feed = fetch_json(store, SITE + "%s/%s/scoreboard?limit=300&dates=%s" % (sport, league, stamp))
        for event in feed.get("events", []):
            for competitor in event["competitions"][0]["competitors"]:
                team = competitor["team"]
                if team.get("logo") and team.get("abbreviation"):
                    seen[(team["abbreviation"], team["logo"])] += 1
        day += step_days * 86400
    return [candidate for candidate, count in seen.most_common() if count >= minimum]


def app_logo_requests(runtime, app, kind, candidates):
    """Evaluate the app's own get_logo_source/get_logoSize for every candidate."""
    app_dir = ROOT / "apps" / app
    source = next(p for p in app_dir.glob("*.star"))
    text = source.read_text().replace("def main(config):", "def original_main(config):", 1)
    sizes = "[get_logoSize(c[0]), 30, 32]" if kind == "scores" else "[10]"
    text += """
LOGO_CANDIDATES = json.decode(%r)
def main(config):
    out = []
    for c in LOGO_CANDIDATES:
        out.append([get_logo_source(c[0], c[1])[0], %s])
    print("LOGO-REQUESTS " + json.encode(out))
    return []
""" % (json.dumps(candidates), sizes)
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / app
        (work / "logos").mkdir(parents=True)
        (work / "logos" / "index.json").write_text("{}\n")
        (work / "logos" / "logos.bin").write_bytes(b"")
        (work / source.name).write_text(text)
        out = subprocess.run([runtime, "render", str(work / source.name), "-o", str(Path(tmp) / "x.webp")],
                             capture_output=True, text=True, check=True)
    line = next(l for l in (out.stdout + out.stderr).splitlines() if "LOGO-REQUESTS " in l)
    return json.loads(line.split("LOGO-REQUESTS ", 1)[1])


def slug(url):
    match = re.search(r"teamlogos/ncaa/500(?:-dark)?/(\d+)\.png", url)
    if match:
        return match.group(1)
    match = re.search(r"guid/([0-9a-f-]+)/logos/", url)
    if match:
        return match.group(1).replace("-", "")[:12]
    host = re.match(r"https://([^/]+)/", url).group(1).split(".")[-2]
    name = url.split("?")[0].rsplit("/", 1)[1].rsplit(".png", 1)[0]
    name = re.sub(r"\.vresize\..*$", "", name)
    return re.sub(r"[^a-z0-9]+", "-", (host + "-" + name).lower()).strip("-")


def build(app, runtime, store, resizer):
    kind, sport, league, spec, selection = APPS[app]
    if "groups" in spec:
        candidates = group_candidates(store, sport, league, spec["groups"])
    else:
        candidates = scoreboard_candidates(store, sport, league, spec["scoreboards"])
    candidates.append(("", TRANSPARENT))
    requests = {}
    for url, sizes in app_logo_requests(runtime, app, kind, candidates):
        requests.setdefault(url, set()).update(sizes)

    out_dir = ROOT / "apps" / app / "logos"
    if out_dir.exists():
        shutil.rmtree(out_dir)
    out_dir.mkdir()
    with tempfile.TemporaryDirectory() as tmp:
        jobs, names = [], {}
        for url in sorted(requests):
            status, original = store.get(url)
            if status != 200:
                print("skip %s: HTTP %d" % (url, status), file=sys.stderr)
                continue
            name = slug(url)
            if names.setdefault(name, url) != url:
                raise SystemExit("logo name collision: %s for %s and %s" % (name, names[name], url))
            for size in sorted(requests[url]):
                jobs.append({"src": str(original), "size": size, "out": str(Path(tmp) / ("%s-%d.png" % (name, size))), "url": url})
        results = json.loads(subprocess.run([str(resizer)], input=json.dumps(jobs), capture_output=True, text=True, check=True).stdout)

        # One pack file keeps the per-render cost to a single file load; the
        # index maps each URL and drawn size to the byte range of its PNG.
        pack, bundle, sources = bytearray(), {}, {}
        for job, result in zip(jobs, results):
            if not result["ok"]:
                print("skip %s @%d: %s" % (job["url"], job["size"], result["reason"]), file=sys.stderr)
                continue
            png = Path(result["out"]).read_bytes()
            span = (len(pack), len(pack) + len(png))
            pack += png
            bundle.setdefault(job["url"], {})[job["size"]] = span
            entry = sources.setdefault(job["url"], {"original_sha256": hashlib.sha256(Path(job["src"]).read_bytes()).hexdigest(), "sizes": []})
            entry["sizes"].append(job["size"])

    (out_dir / "logos.bin").write_bytes(bytes(pack))
    # A JSON index (decoded once per load) avoids compiling a generated module.
    entries = ["%s:{%s}" % (json.dumps(url), ",".join('"%d":[%d,%d]' % (size, span[0], span[1]) for size, span in sorted(bundle[url].items())))
               for url in sorted(bundle)]
    (out_dir / "index.json").write_text("{\n" + ",\n".join(entries) + "\n}\n")
    lines = ["  %s: %s" % (json.dumps(url), json.dumps(sources[url], sort_keys=True)) for url in sorted(sources)]
    (out_dir / "sources.json").write_text('{\n "generated": "%s",\n "pack": "logos.bin",\n "logos": {\n%s\n }\n}\n'
                                          % (time.strftime("%Y-%m-%d"), ",\n".join(lines)))
    sizes = sorted({size for spans in bundle.values() for size in spans})
    (out_dir / "README.md").write_text(README % {
        "count": len(bundle), "images": sum(len(v) for v in bundle.values()), "bytes": len(pack),
        "selection": selection, "sizes": ", ".join(map(str, sizes)), "date": time.strftime("%Y-%m-%d")})
    total = sum(p.stat().st_size for p in out_dir.rglob("*") if p.is_file())
    print("%s: %d logos, %d images, %d pack bytes, %d bytes total" % (app, len(bundle), sum(len(v) for v in bundle.values()), len(pack), total))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--runtime", required=True)
    parser.add_argument("--cache", default=str(Path(tempfile.gettempdir()) / "college-logos-cache"))
    parser.add_argument("apps", nargs="*", default=list(APPS))
    args = parser.parse_args()
    store = Store(args.cache)
    with tempfile.TemporaryDirectory() as tmp:
        resizer = Path(tmp) / "resize"
        subprocess.run(["go", "build", "-o", str(resizer), "."], cwd=TOOL / "resize", check=True)
        for app in args.apps:
            build(app, args.runtime, store, resizer)


if __name__ == "__main__":
    main()
