"""
Bundled team logos for wbcscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/aus-8c5950f2-16.png", LOGO_AUS_8C5950F2_16 = "file")
load("images/logos/aus-8c5950f2-30.png", LOGO_AUS_8C5950F2_30 = "file")
load("images/logos/aus-8c5950f2-32.png", LOGO_AUS_8C5950F2_32 = "file")
load("images/logos/bra-dd388b30-16.png", LOGO_BRA_DD388B30_16 = "file")
load("images/logos/bra-dd388b30-30.png", LOGO_BRA_DD388B30_30 = "file")
load("images/logos/bra-dd388b30-32.png", LOGO_BRA_DD388B30_32 = "file")
load("images/logos/can-7e649de5-16.png", LOGO_CAN_7E649DE5_16 = "file")
load("images/logos/can-7e649de5-30.png", LOGO_CAN_7E649DE5_30 = "file")
load("images/logos/can-7e649de5-32.png", LOGO_CAN_7E649DE5_32 = "file")
load("images/logos/col-93a69c7c-16.png", LOGO_COL_93A69C7C_16 = "file")
load("images/logos/col-93a69c7c-30.png", LOGO_COL_93A69C7C_30 = "file")
load("images/logos/col-93a69c7c-32.png", LOGO_COL_93A69C7C_32 = "file")
load("images/logos/cub-1b8edc01-16.png", LOGO_CUB_1B8EDC01_16 = "file")
load("images/logos/cub-1b8edc01-30.png", LOGO_CUB_1B8EDC01_30 = "file")
load("images/logos/cub-1b8edc01-32.png", LOGO_CUB_1B8EDC01_32 = "file")
load("images/logos/cze-b6e5041d-16.png", LOGO_CZE_B6E5041D_16 = "file")
load("images/logos/cze-b6e5041d-30.png", LOGO_CZE_B6E5041D_30 = "file")
load("images/logos/cze-b6e5041d-32.png", LOGO_CZE_B6E5041D_32 = "file")
load("images/logos/dom-035236fb-16.png", LOGO_DOM_035236FB_16 = "file")
load("images/logos/dom-035236fb-30.png", LOGO_DOM_035236FB_30 = "file")
load("images/logos/dom-035236fb-32.png", LOGO_DOM_035236FB_32 = "file")
load("images/logos/gbr-a2c96d20-16.png", LOGO_GBR_A2C96D20_16 = "file")
load("images/logos/gbr-a2c96d20-30.png", LOGO_GBR_A2C96D20_30 = "file")
load("images/logos/gbr-a2c96d20-32.png", LOGO_GBR_A2C96D20_32 = "file")
load("images/logos/isr-043e4c4e-16.png", LOGO_ISR_043E4C4E_16 = "file")
load("images/logos/isr-043e4c4e-30.png", LOGO_ISR_043E4C4E_30 = "file")
load("images/logos/isr-043e4c4e-32.png", LOGO_ISR_043E4C4E_32 = "file")
load("images/logos/ita-4709daea-16.png", LOGO_ITA_4709DAEA_16 = "file")
load("images/logos/ita-4709daea-30.png", LOGO_ITA_4709DAEA_30 = "file")
load("images/logos/ita-4709daea-32.png", LOGO_ITA_4709DAEA_32 = "file")
load("images/logos/jpn-46cee9e1-16.png", LOGO_JPN_46CEE9E1_16 = "file")
load("images/logos/jpn-46cee9e1-30.png", LOGO_JPN_46CEE9E1_30 = "file")
load("images/logos/jpn-46cee9e1-32.png", LOGO_JPN_46CEE9E1_32 = "file")
load("images/logos/kor-90cfd592-16.png", LOGO_KOR_90CFD592_16 = "file")
load("images/logos/kor-90cfd592-30.png", LOGO_KOR_90CFD592_30 = "file")
load("images/logos/kor-90cfd592-32.png", LOGO_KOR_90CFD592_32 = "file")
load("images/logos/mex-65101acd-16.png", LOGO_MEX_65101ACD_16 = "file")
load("images/logos/mex-65101acd-30.png", LOGO_MEX_65101ACD_30 = "file")
load("images/logos/mex-65101acd-32.png", LOGO_MEX_65101ACD_32 = "file")
load("images/logos/nca-cd6f6524-16.png", LOGO_NCA_CD6F6524_16 = "file")
load("images/logos/nca-cd6f6524-30.png", LOGO_NCA_CD6F6524_30 = "file")
load("images/logos/nca-cd6f6524-32.png", LOGO_NCA_CD6F6524_32 = "file")
load("images/logos/ned-4a928c9b-16.png", LOGO_NED_4A928C9B_16 = "file")
load("images/logos/ned-4a928c9b-30.png", LOGO_NED_4A928C9B_30 = "file")
load("images/logos/ned-4a928c9b-32.png", LOGO_NED_4A928C9B_32 = "file")
load("images/logos/pan-d5a16dc9-16.png", LOGO_PAN_D5A16DC9_16 = "file")
load("images/logos/pan-d5a16dc9-30.png", LOGO_PAN_D5A16DC9_30 = "file")
load("images/logos/pan-d5a16dc9-32.png", LOGO_PAN_D5A16DC9_32 = "file")
load("images/logos/pur-ad015fa9-16.png", LOGO_PUR_AD015FA9_16 = "file")
load("images/logos/pur-ad015fa9-30.png", LOGO_PUR_AD015FA9_30 = "file")
load("images/logos/pur-ad015fa9-32.png", LOGO_PUR_AD015FA9_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/tpo-b60a79b9-16.png", LOGO_TPO_B60A79B9_16 = "file")
load("images/logos/tpo-b60a79b9-30.png", LOGO_TPO_B60A79B9_30 = "file")
load("images/logos/tpo-b60a79b9-32.png", LOGO_TPO_B60A79B9_32 = "file")
load("images/logos/usa-3542d3ca-16.png", LOGO_USA_3542D3CA_16 = "file")
load("images/logos/usa-3542d3ca-30.png", LOGO_USA_3542D3CA_30 = "file")
load("images/logos/usa-3542d3ca-32.png", LOGO_USA_3542D3CA_32 = "file")
load("images/logos/ven-88b2ef32-16.png", LOGO_VEN_88B2EF32_16 = "file")
load("images/logos/ven-88b2ef32-30.png", LOGO_VEN_88B2EF32_30 = "file")
load("images/logos/ven-88b2ef32-32.png", LOGO_VEN_88B2EF32_32 = "file")

BUNDLED_LOGOS = {
    # AUS; source sha256 63660a47a998b48c85a8aec893836db24dee0d0bdbce2f69ed0b4664631ef89c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/aus.png&h=50&w=50": {
        16: LOGO_AUS_8C5950F2_16,
        30: LOGO_AUS_8C5950F2_30,
        32: LOGO_AUS_8C5950F2_32,
    },
    # BRA; source sha256 e2c3fb67cf394cbc979e47cd21925db89259f3794985d07648396d8dcc328e84
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/bra.png&h=50&w=50": {
        16: LOGO_BRA_DD388B30_16,
        30: LOGO_BRA_DD388B30_30,
        32: LOGO_BRA_DD388B30_32,
    },
    # CAN; source sha256 28b86cd99b179d3e018d69f21e78a698d2ac75bcdf6b63ed28c29819098402f2
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/can.png&h=50&w=50": {
        16: LOGO_CAN_7E649DE5_16,
        30: LOGO_CAN_7E649DE5_30,
        32: LOGO_CAN_7E649DE5_32,
    },
    # COL; source sha256 1891dd91d696a7335d3a7241e656a961c6399dd4cb3608317cf8ff93f72a343c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/col.png&h=50&w=50": {
        16: LOGO_COL_93A69C7C_16,
        30: LOGO_COL_93A69C7C_30,
        32: LOGO_COL_93A69C7C_32,
    },
    # CUB; source sha256 c8c377df7721fa06220e81fbb35c2b8a4d1dd6cae9539b9a22bcb0d597072813
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/cub.png&h=50&w=50": {
        16: LOGO_CUB_1B8EDC01_16,
        30: LOGO_CUB_1B8EDC01_30,
        32: LOGO_CUB_1B8EDC01_32,
    },
    # CZE; source sha256 623c165cc2f487bac9e29d49add65d2ab15f8d00a61db4cea30b28451a69146e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/cze.png&h=50&w=50": {
        16: LOGO_CZE_B6E5041D_16,
        30: LOGO_CZE_B6E5041D_30,
        32: LOGO_CZE_B6E5041D_32,
    },
    # DOM; source sha256 78fdf4b2be921ed52f1fbecfc9ee4fc49e95701792a4de47d4a9b08688afafb0
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/dom.png&h=50&w=50": {
        16: LOGO_DOM_035236FB_16,
        30: LOGO_DOM_035236FB_30,
        32: LOGO_DOM_035236FB_32,
    },
    # GBR; source sha256 663be78506fe2107df3dcf46fa3982a40d1e21780f3c57be531b423f2e2d0532
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/gbr.png&h=50&w=50": {
        16: LOGO_GBR_A2C96D20_16,
        30: LOGO_GBR_A2C96D20_30,
        32: LOGO_GBR_A2C96D20_32,
    },
    # ISR; source sha256 694b0829d83c984cfff3d0a74f0c3e99600af581b03aa9a9f467a34cf961ab7c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/isr.png&h=50&w=50": {
        16: LOGO_ISR_043E4C4E_16,
        30: LOGO_ISR_043E4C4E_30,
        32: LOGO_ISR_043E4C4E_32,
    },
    # ITA; source sha256 c9afbffbbfb4c1e9af0b932f78f7d67109f6dea79b331bc5616a337526c73fab
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/ita.png&h=50&w=50": {
        16: LOGO_ITA_4709DAEA_16,
        30: LOGO_ITA_4709DAEA_30,
        32: LOGO_ITA_4709DAEA_32,
    },
    # JPN; source sha256 87eb673a5bf585eed262b164655e8419dfc57ee6f5201b61e03b44b564160ca4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/jpn.png&h=50&w=50": {
        16: LOGO_JPN_46CEE9E1_16,
        30: LOGO_JPN_46CEE9E1_30,
        32: LOGO_JPN_46CEE9E1_32,
    },
    # KOR; source sha256 9949f067d2fe5251de224ab2dafd5eed9372405d96eb7b46e6712b5f0752abad
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/kor.png&h=50&w=50": {
        16: LOGO_KOR_90CFD592_16,
        30: LOGO_KOR_90CFD592_30,
        32: LOGO_KOR_90CFD592_32,
    },
    # MEX; source sha256 941b0e5e1b5e5f1b9596c59eeedb7e67c149d07ca3541fb42efa761d0ab8271c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/mex.png&h=50&w=50": {
        16: LOGO_MEX_65101ACD_16,
        30: LOGO_MEX_65101ACD_30,
        32: LOGO_MEX_65101ACD_32,
    },
    # NCA; source sha256 66274ec57040fd91ce6df0f48dbe4f1ec33cf0c8c37f0feff81869e622bc64f2
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/nca.png&h=50&w=50": {
        16: LOGO_NCA_CD6F6524_16,
        30: LOGO_NCA_CD6F6524_30,
        32: LOGO_NCA_CD6F6524_32,
    },
    # NED; source sha256 1a6c67bd3e467c66fcb40e6588211a143053d8738331ab8c4194d5a30c6d5696
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/ned.png&h=50&w=50": {
        16: LOGO_NED_4A928C9B_16,
        30: LOGO_NED_4A928C9B_30,
        32: LOGO_NED_4A928C9B_32,
    },
    # PAN; source sha256 71b114593d4853aad1090f20b5be8f8793117f4091a25250be39cb411435d915
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/pan.png&h=50&w=50": {
        16: LOGO_PAN_D5A16DC9_16,
        30: LOGO_PAN_D5A16DC9_30,
        32: LOGO_PAN_D5A16DC9_32,
    },
    # PUR; source sha256 72053f6ae9f1fd6a713349b233206b17b085a3d8760589b4259d89dcf0800659
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/pur.png&h=50&w=50": {
        16: LOGO_PUR_AD015FA9_16,
        30: LOGO_PUR_AD015FA9_30,
        32: LOGO_PUR_AD015FA9_32,
    },
    # TPO; source sha256 9cba965de2f958571a1c265d3501058454294c6bf16824ef45bedd548dbb558a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/tpo.png&h=50&w=50": {
        16: LOGO_TPO_B60A79B9_16,
        30: LOGO_TPO_B60A79B9_30,
        32: LOGO_TPO_B60A79B9_32,
    },
    # USA; source sha256 d9b7b3a81d2a9a13e634c8e2ad469d07a89f3f0e11e63150539d2b486f58fae6
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/usa.png&h=50&w=50": {
        16: LOGO_USA_3542D3CA_16,
        30: LOGO_USA_3542D3CA_30,
        32: LOGO_USA_3542D3CA_32,
    },
    # VEN; source sha256 e94fad437a379b1f807eba76cd956963d13ed0c7294a77f94d7282fec4c80b32
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/countries/500/ven.png&h=50&w=50": {
        16: LOGO_VEN_88B2EF32_16,
        30: LOGO_VEN_88B2EF32_30,
        32: LOGO_VEN_88B2EF32_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
