"""
Bundled team logos for wnbascores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/atl-892a0acf-16.png", LOGO_ATL_892A0ACF_16 = "file")
load("images/logos/atl-892a0acf-30.png", LOGO_ATL_892A0ACF_30 = "file")
load("images/logos/atl-892a0acf-32.png", LOGO_ATL_892A0ACF_32 = "file")
load("images/logos/chi-b88ad982-16.png", LOGO_CHI_B88AD982_16 = "file")
load("images/logos/chi-b88ad982-30.png", LOGO_CHI_B88AD982_30 = "file")
load("images/logos/chi-b88ad982-32.png", LOGO_CHI_B88AD982_32 = "file")
load("images/logos/con-7e3f11c9-16.png", LOGO_CON_7E3F11C9_16 = "file")
load("images/logos/con-7e3f11c9-30.png", LOGO_CON_7E3F11C9_30 = "file")
load("images/logos/con-7e3f11c9-32.png", LOGO_CON_7E3F11C9_32 = "file")
load("images/logos/dal-a7270933-16.png", LOGO_DAL_A7270933_16 = "file")
load("images/logos/dal-a7270933-30.png", LOGO_DAL_A7270933_30 = "file")
load("images/logos/dal-a7270933-32.png", LOGO_DAL_A7270933_32 = "file")
load("images/logos/gs-0e78b16d-16.png", LOGO_GS_0E78B16D_16 = "file")
load("images/logos/gs-0e78b16d-30.png", LOGO_GS_0E78B16D_30 = "file")
load("images/logos/gs-0e78b16d-32.png", LOGO_GS_0E78B16D_32 = "file")
load("images/logos/ind-37a9ab7b-16.png", LOGO_IND_37A9AB7B_16 = "file")
load("images/logos/ind-37a9ab7b-30.png", LOGO_IND_37A9AB7B_30 = "file")
load("images/logos/ind-37a9ab7b-32.png", LOGO_IND_37A9AB7B_32 = "file")
load("images/logos/la-bfae7cab-16.png", LOGO_LA_BFAE7CAB_16 = "file")
load("images/logos/la-bfae7cab-30.png", LOGO_LA_BFAE7CAB_30 = "file")
load("images/logos/la-bfae7cab-32.png", LOGO_LA_BFAE7CAB_32 = "file")
load("images/logos/lv-02a99c2f-16.png", LOGO_LV_02A99C2F_16 = "file")
load("images/logos/lv-02a99c2f-30.png", LOGO_LV_02A99C2F_30 = "file")
load("images/logos/lv-02a99c2f-32.png", LOGO_LV_02A99C2F_32 = "file")
load("images/logos/min-d8e227b3-16.png", LOGO_MIN_D8E227B3_16 = "file")
load("images/logos/min-d8e227b3-30.png", LOGO_MIN_D8E227B3_30 = "file")
load("images/logos/min-d8e227b3-32.png", LOGO_MIN_D8E227B3_32 = "file")
load("images/logos/ny-d7701465-16.png", LOGO_NY_D7701465_16 = "file")
load("images/logos/ny-d7701465-30.png", LOGO_NY_D7701465_30 = "file")
load("images/logos/ny-d7701465-32.png", LOGO_NY_D7701465_32 = "file")
load("images/logos/phx-8ccfebae-16.png", LOGO_PHX_8CCFEBAE_16 = "file")
load("images/logos/phx-8ccfebae-30.png", LOGO_PHX_8CCFEBAE_30 = "file")
load("images/logos/phx-8ccfebae-32.png", LOGO_PHX_8CCFEBAE_32 = "file")
load("images/logos/por-f8459251-16.png", LOGO_POR_F8459251_16 = "file")
load("images/logos/por-f8459251-30.png", LOGO_POR_F8459251_30 = "file")
load("images/logos/por-f8459251-32.png", LOGO_POR_F8459251_32 = "file")
load("images/logos/sea-cee8a738-16.png", LOGO_SEA_CEE8A738_16 = "file")
load("images/logos/sea-cee8a738-30.png", LOGO_SEA_CEE8A738_30 = "file")
load("images/logos/sea-cee8a738-32.png", LOGO_SEA_CEE8A738_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/tor-2080fe74-16.png", LOGO_TOR_2080FE74_16 = "file")
load("images/logos/tor-2080fe74-30.png", LOGO_TOR_2080FE74_30 = "file")
load("images/logos/tor-2080fe74-32.png", LOGO_TOR_2080FE74_32 = "file")
load("images/logos/wsh-0277bdca-16.png", LOGO_WSH_0277BDCA_16 = "file")
load("images/logos/wsh-0277bdca-30.png", LOGO_WSH_0277BDCA_30 = "file")
load("images/logos/wsh-0277bdca-32.png", LOGO_WSH_0277BDCA_32 = "file")

BUNDLED_LOGOS = {
    # ATL; source sha256 5fb14b49077f727d59361eb66db387df326e03201ce1eeb72aafcf5b22e4c441
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/atl.png&h=50&w=50": {
        16: LOGO_ATL_892A0ACF_16,
        30: LOGO_ATL_892A0ACF_30,
        32: LOGO_ATL_892A0ACF_32,
    },
    # CHI; source sha256 92a86cc508061cbc72bd13883c353b518ad35ba9247ba24994116b724722a94e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/chi.png&h=50&w=50": {
        16: LOGO_CHI_B88AD982_16,
        30: LOGO_CHI_B88AD982_30,
        32: LOGO_CHI_B88AD982_32,
    },
    # CON; source sha256 ee7d65d5dd692a9d098dbf386d06c6d2d3402c05c8228e3941a4f94bde1e1f12
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/con.png&h=50&w=50": {
        16: LOGO_CON_7E3F11C9_16,
        30: LOGO_CON_7E3F11C9_30,
        32: LOGO_CON_7E3F11C9_32,
    },
    # DAL; source sha256 14962ca9c55d5097eefe0a398c92cc9c99d00964aad8ce2a67cccecf9f9eea36
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/dal.png&h=50&w=50": {
        16: LOGO_DAL_A7270933_16,
        30: LOGO_DAL_A7270933_30,
        32: LOGO_DAL_A7270933_32,
    },
    # GS; source sha256 1d09c93af0ac56b7b0dfdbf0699ccf0b678875953830effdb46a5c80a2d69b56
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/gs.png&h=50&w=50": {
        16: LOGO_GS_0E78B16D_16,
        30: LOGO_GS_0E78B16D_30,
        32: LOGO_GS_0E78B16D_32,
    },
    # IND; source sha256 d480117f40cf854abf5078462404d167b38767462b1d01c5b820a86ca33df090
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/ind.png&h=50&w=50": {
        16: LOGO_IND_37A9AB7B_16,
        30: LOGO_IND_37A9AB7B_30,
        32: LOGO_IND_37A9AB7B_32,
    },
    # LA; source sha256 9997e8b989d4d6c3a77a4293efee34b68ff5f12eef6f80339933ce54eb6abdd0
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/la.png&h=50&w=50": {
        16: LOGO_LA_BFAE7CAB_16,
        30: LOGO_LA_BFAE7CAB_30,
        32: LOGO_LA_BFAE7CAB_32,
    },
    # LV; source sha256 f71f9f5e98b762bb77e5836becf25443c665314bfcaed40e7ca5daa1f435d9a9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/lv.png&h=50&w=50": {
        16: LOGO_LV_02A99C2F_16,
        30: LOGO_LV_02A99C2F_30,
        32: LOGO_LV_02A99C2F_32,
    },
    # MIN; source sha256 b4d64700fc5f23b3ab5b6f6813ec0d899a548396fb15909866077f2b957bd6b8
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/min.png&h=50&w=50": {
        16: LOGO_MIN_D8E227B3_16,
        30: LOGO_MIN_D8E227B3_30,
        32: LOGO_MIN_D8E227B3_32,
    },
    # NY; source sha256 bcc3540de3de7500f0b6e3143b60b5a69a6d5cc55a3f456286aa85b5cc2b2532
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/ny.png&h=50&w=50": {
        16: LOGO_NY_D7701465_16,
        30: LOGO_NY_D7701465_30,
        32: LOGO_NY_D7701465_32,
    },
    # PHX; source sha256 e97459e1df4137eadf0c2c38a18aa306ca692f6f705fe33dddc02cd200d0b738
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/phx.png&h=50&w=50": {
        16: LOGO_PHX_8CCFEBAE_16,
        30: LOGO_PHX_8CCFEBAE_30,
        32: LOGO_PHX_8CCFEBAE_32,
    },
    # POR; source sha256 bcd370527f5d5e7139539193ce5fc0724893817ba513f6e97d7b3154b292e4eb
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/por.png&h=50&w=50": {
        16: LOGO_POR_F8459251_16,
        30: LOGO_POR_F8459251_30,
        32: LOGO_POR_F8459251_32,
    },
    # SEA; source sha256 29e78eea0207a02c43e0ce6db263f2457b01223b875076002e496e8c357030e1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/sea.png&h=50&w=50": {
        16: LOGO_SEA_CEE8A738_16,
        30: LOGO_SEA_CEE8A738_30,
        32: LOGO_SEA_CEE8A738_32,
    },
    # TOR; source sha256 3284325b25e83b0623c578bcc0cae74325afc7aa1450cc5715d312d6f8075630
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/tor.png&h=50&w=50": {
        16: LOGO_TOR_2080FE74_16,
        30: LOGO_TOR_2080FE74_30,
        32: LOGO_TOR_2080FE74_32,
    },
    # WSH; source sha256 38abc09dcdd9ac6d164f5d24114fe19388d9575cf6653ab4e6698fdb70aff966
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/wnba/500-dark/wsh.png&h=50&w=50": {
        16: LOGO_WSH_0277BDCA_16,
        30: LOGO_WSH_0277BDCA_30,
        32: LOGO_WSH_0277BDCA_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
