"""
Bundled team logos for mlsscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/atl-a4b3cd5d-16.png", LOGO_ATL_A4B3CD5D_16 = "file")
load("images/logos/atl-a4b3cd5d-30.png", LOGO_ATL_A4B3CD5D_30 = "file")
load("images/logos/atl-a4b3cd5d-32.png", LOGO_ATL_A4B3CD5D_32 = "file")
load("images/logos/atx-8bf537a7-18.png", LOGO_ATX_8BF537A7_18 = "file")
load("images/logos/atx-8bf537a7-30.png", LOGO_ATX_8BF537A7_30 = "file")
load("images/logos/atx-8bf537a7-32.png", LOGO_ATX_8BF537A7_32 = "file")
load("images/logos/chi-85c2c3a9-16.png", LOGO_CHI_85C2C3A9_16 = "file")
load("images/logos/chi-85c2c3a9-30.png", LOGO_CHI_85C2C3A9_30 = "file")
load("images/logos/chi-85c2c3a9-32.png", LOGO_CHI_85C2C3A9_32 = "file")
load("images/logos/cin-dcff47b5-16.png", LOGO_CIN_DCFF47B5_16 = "file")
load("images/logos/cin-dcff47b5-30.png", LOGO_CIN_DCFF47B5_30 = "file")
load("images/logos/cin-dcff47b5-32.png", LOGO_CIN_DCFF47B5_32 = "file")
load("images/logos/clb-ea54a82d-18.png", LOGO_CLB_EA54A82D_18 = "file")
load("images/logos/clb-ea54a82d-30.png", LOGO_CLB_EA54A82D_30 = "file")
load("images/logos/clb-ea54a82d-32.png", LOGO_CLB_EA54A82D_32 = "file")
load("images/logos/clt-c2c31799-16.png", LOGO_CLT_C2C31799_16 = "file")
load("images/logos/clt-c2c31799-30.png", LOGO_CLT_C2C31799_30 = "file")
load("images/logos/clt-c2c31799-32.png", LOGO_CLT_C2C31799_32 = "file")
load("images/logos/col-d32040e8-18.png", LOGO_COL_D32040E8_18 = "file")
load("images/logos/col-d32040e8-30.png", LOGO_COL_D32040E8_30 = "file")
load("images/logos/col-d32040e8-32.png", LOGO_COL_D32040E8_32 = "file")
load("images/logos/dal-2121bb66-14.png", LOGO_DAL_2121BB66_14 = "file")
load("images/logos/dal-2121bb66-30.png", LOGO_DAL_2121BB66_30 = "file")
load("images/logos/dal-2121bb66-32.png", LOGO_DAL_2121BB66_32 = "file")
load("images/logos/dc-d38324bb-16.png", LOGO_DC_D38324BB_16 = "file")
load("images/logos/dc-d38324bb-30.png", LOGO_DC_D38324BB_30 = "file")
load("images/logos/dc-d38324bb-32.png", LOGO_DC_D38324BB_32 = "file")
load("images/logos/hou-d40ade75-16.png", LOGO_HOU_D40ADE75_16 = "file")
load("images/logos/hou-d40ade75-30.png", LOGO_HOU_D40ADE75_30 = "file")
load("images/logos/hou-d40ade75-32.png", LOGO_HOU_D40ADE75_32 = "file")
load("images/logos/la-c03001fa-18.png", LOGO_LA_C03001FA_18 = "file")
load("images/logos/la-c03001fa-30.png", LOGO_LA_C03001FA_30 = "file")
load("images/logos/la-c03001fa-32.png", LOGO_LA_C03001FA_32 = "file")
load("images/logos/lafc-a1db8088-16.png", LOGO_LAFC_A1DB8088_16 = "file")
load("images/logos/lafc-a1db8088-30.png", LOGO_LAFC_A1DB8088_30 = "file")
load("images/logos/lafc-a1db8088-32.png", LOGO_LAFC_A1DB8088_32 = "file")
load("images/logos/mia-5d1d18e7-14.png", LOGO_MIA_5D1D18E7_14 = "file")
load("images/logos/mia-5d1d18e7-30.png", LOGO_MIA_5D1D18E7_30 = "file")
load("images/logos/mia-5d1d18e7-32.png", LOGO_MIA_5D1D18E7_32 = "file")
load("images/logos/min-9f27b009-16.png", LOGO_MIN_9F27B009_16 = "file")
load("images/logos/min-9f27b009-30.png", LOGO_MIN_9F27B009_30 = "file")
load("images/logos/min-9f27b009-32.png", LOGO_MIN_9F27B009_32 = "file")
load("images/logos/mtl-c48e9498-16.png", LOGO_MTL_C48E9498_16 = "file")
load("images/logos/mtl-c48e9498-30.png", LOGO_MTL_C48E9498_30 = "file")
load("images/logos/mtl-c48e9498-32.png", LOGO_MTL_C48E9498_32 = "file")
load("images/logos/ne-9a9bf08c-16.png", LOGO_NE_9A9BF08C_16 = "file")
load("images/logos/ne-9a9bf08c-30.png", LOGO_NE_9A9BF08C_30 = "file")
load("images/logos/ne-9a9bf08c-32.png", LOGO_NE_9A9BF08C_32 = "file")
load("images/logos/nsh-1afb08e4-16.png", LOGO_NSH_1AFB08E4_16 = "file")
load("images/logos/nsh-1afb08e4-30.png", LOGO_NSH_1AFB08E4_30 = "file")
load("images/logos/nsh-1afb08e4-32.png", LOGO_NSH_1AFB08E4_32 = "file")
load("images/logos/nyc-608a3821-16.png", LOGO_NYC_608A3821_16 = "file")
load("images/logos/nyc-608a3821-30.png", LOGO_NYC_608A3821_30 = "file")
load("images/logos/nyc-608a3821-32.png", LOGO_NYC_608A3821_32 = "file")
load("images/logos/orl-9efc8ef0-16.png", LOGO_ORL_9EFC8EF0_16 = "file")
load("images/logos/orl-9efc8ef0-30.png", LOGO_ORL_9EFC8EF0_30 = "file")
load("images/logos/orl-9efc8ef0-32.png", LOGO_ORL_9EFC8EF0_32 = "file")
load("images/logos/phi-05242375-16.png", LOGO_PHI_05242375_16 = "file")
load("images/logos/phi-05242375-30.png", LOGO_PHI_05242375_30 = "file")
load("images/logos/phi-05242375-32.png", LOGO_PHI_05242375_32 = "file")
load("images/logos/por-6cde99e0-16.png", LOGO_POR_6CDE99E0_16 = "file")
load("images/logos/por-6cde99e0-30.png", LOGO_POR_6CDE99E0_30 = "file")
load("images/logos/por-6cde99e0-32.png", LOGO_POR_6CDE99E0_32 = "file")
load("images/logos/rbny-f80d7b44-16.png", LOGO_RBNY_F80D7B44_16 = "file")
load("images/logos/rbny-f80d7b44-30.png", LOGO_RBNY_F80D7B44_30 = "file")
load("images/logos/rbny-f80d7b44-32.png", LOGO_RBNY_F80D7B44_32 = "file")
load("images/logos/rsl-ac1b66cc-18.png", LOGO_RSL_AC1B66CC_18 = "file")
load("images/logos/rsl-ac1b66cc-30.png", LOGO_RSL_AC1B66CC_30 = "file")
load("images/logos/rsl-ac1b66cc-32.png", LOGO_RSL_AC1B66CC_32 = "file")
load("images/logos/sd-4c5d45ad-16.png", LOGO_SD_4C5D45AD_16 = "file")
load("images/logos/sd-4c5d45ad-30.png", LOGO_SD_4C5D45AD_30 = "file")
load("images/logos/sd-4c5d45ad-32.png", LOGO_SD_4C5D45AD_32 = "file")
load("images/logos/sea-2ed087f3-16.png", LOGO_SEA_2ED087F3_16 = "file")
load("images/logos/sea-2ed087f3-30.png", LOGO_SEA_2ED087F3_30 = "file")
load("images/logos/sea-2ed087f3-32.png", LOGO_SEA_2ED087F3_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/sj-faa51f29-18.png", LOGO_SJ_FAA51F29_18 = "file")
load("images/logos/sj-faa51f29-30.png", LOGO_SJ_FAA51F29_30 = "file")
load("images/logos/sj-faa51f29-32.png", LOGO_SJ_FAA51F29_32 = "file")
load("images/logos/skc-22cba228-16.png", LOGO_SKC_22CBA228_16 = "file")
load("images/logos/skc-22cba228-30.png", LOGO_SKC_22CBA228_30 = "file")
load("images/logos/skc-22cba228-32.png", LOGO_SKC_22CBA228_32 = "file")
load("images/logos/stl-68835500-16.png", LOGO_STL_68835500_16 = "file")
load("images/logos/stl-68835500-30.png", LOGO_STL_68835500_30 = "file")
load("images/logos/stl-68835500-32.png", LOGO_STL_68835500_32 = "file")
load("images/logos/tor-5294e9d9-16.png", LOGO_TOR_5294E9D9_16 = "file")
load("images/logos/tor-5294e9d9-30.png", LOGO_TOR_5294E9D9_30 = "file")
load("images/logos/tor-5294e9d9-32.png", LOGO_TOR_5294E9D9_32 = "file")
load("images/logos/van-ed555a16-18.png", LOGO_VAN_ED555A16_18 = "file")
load("images/logos/van-ed555a16-30.png", LOGO_VAN_ED555A16_30 = "file")
load("images/logos/van-ed555a16-32.png", LOGO_VAN_ED555A16_32 = "file")

BUNDLED_LOGOS = {
    # PHI; source sha256 a6a9ae90ec30c3d634f03f6121c6280d91cdd12fdb6e1f40f81e8c6bdbdae5ca
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/10739.png&h=50&w=50": {
        16: LOGO_PHI_05242375_16,
        30: LOGO_PHI_05242375_30,
        32: LOGO_PHI_05242375_32,
    },
    # ORL; source sha256 5996dd691f460b71404e49f1fa09777dde828c6f851d3c448cef2dce6d5fd6b1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/12011.png&h=50&w=50": {
        16: LOGO_ORL_9EFC8EF0_16,
        30: LOGO_ORL_9EFC8EF0_30,
        32: LOGO_ORL_9EFC8EF0_32,
    },
    # MIN; source sha256 f29512c8a37c403364bfec806be67caa6384f199236f79cf2fc63b538472b9f4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/17362.png&h=50&w=50": {
        16: LOGO_MIN_9F27B009_16,
        30: LOGO_MIN_9F27B009_30,
        32: LOGO_MIN_9F27B009_32,
    },
    # NYC; source sha256 3ade92078677f7482696ccc1863af6cf288927df039121d33e87e32e188fb7c2
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/17606.png&h=50&w=50": {
        16: LOGO_NYC_608A3821_16,
        30: LOGO_NYC_608A3821_30,
        32: LOGO_NYC_608A3821_32,
    },
    # CHI; source sha256 350fe9deeed9e80dfc0e1b0cb6a24cd1776416f441fc7182ffa1e35394b59e5c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/182.png&h=50&w=50": {
        16: LOGO_CHI_85C2C3A9_16,
        30: LOGO_CHI_85C2C3A9_30,
        32: LOGO_CHI_85C2C3A9_32,
    },
    # CIN; source sha256 c4586906cdcff699e8969d14900aca8a8975d2db85785bfc69681e99becfff36
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/18267.png&h=50&w=50": {
        16: LOGO_CIN_DCFF47B5_16,
        30: LOGO_CIN_DCFF47B5_30,
        32: LOGO_CIN_DCFF47B5_32,
    },
    # CLB; source sha256 936dbc862106b821f22689feda81beac137615e86f4208b47b91ef76f7635de9
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/183.png&h=50&w=50": {
        18: LOGO_CLB_EA54A82D_18,
        30: LOGO_CLB_EA54A82D_30,
        32: LOGO_CLB_EA54A82D_32,
    },
    # COL; source sha256 e7ea8044614a53cb423830b1ab6102d7ae4d61a18a223f53cd66437ae378aaae
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/184.png&h=50&w=50": {
        18: LOGO_COL_D32040E8_18,
        30: LOGO_COL_D32040E8_30,
        32: LOGO_COL_D32040E8_32,
    },
    # ATL; source sha256 24b30dd302bbfc35ea2860b11d3661b895e68182b13175ee3c600b1580740a1a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/18418.png&h=50&w=50": {
        16: LOGO_ATL_A4B3CD5D_16,
        30: LOGO_ATL_A4B3CD5D_30,
        32: LOGO_ATL_A4B3CD5D_32,
    },
    # DAL; source sha256 e3d0ec37afca9000be8b041e0a4e5e32d735b9ebf33235e0702312cffddda6be
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/185.png&h=50&w=50": {
        14: LOGO_DAL_2121BB66_14,
        30: LOGO_DAL_2121BB66_30,
        32: LOGO_DAL_2121BB66_32,
    },
    # SKC; source sha256 1f6ffcb0a02d550bf1fd0392c3cf4d162580c22e5d986ad2c6f2eaf7cc9f6714
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/186.png&h=50&w=50": {
        16: LOGO_SKC_22CBA228_16,
        30: LOGO_SKC_22CBA228_30,
        32: LOGO_SKC_22CBA228_32,
    },
    # LA; source sha256 4fd6eb968df2f8b6ebd96562b2c6bcc0def0e8844c159b442ac081c53d715906
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/187.png&h=50&w=50": {
        18: LOGO_LA_C03001FA_18,
        30: LOGO_LA_C03001FA_30,
        32: LOGO_LA_C03001FA_32,
    },
    # NE; source sha256 e5c664a273506e314ceaa0cbb351283b2e4c37fcb61a3b96af90dbf1729b878c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/189.png&h=50&w=50": {
        16: LOGO_NE_9A9BF08C_16,
        30: LOGO_NE_9A9BF08C_30,
        32: LOGO_NE_9A9BF08C_32,
    },
    # LAFC; source sha256 8407cdcba992aa15747220ac3c46163399f1df12e0a9cb83803d63c73502d65c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/18966.png&h=50&w=50": {
        16: LOGO_LAFC_A1DB8088_16,
        30: LOGO_LAFC_A1DB8088_30,
        32: LOGO_LAFC_A1DB8088_32,
    },
    # NSH; source sha256 6a3f35259743c84ad530463ef11e8aea6c8f185def7a9413839f3f0c16e8e679
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/18986.png&h=50&w=50": {
        16: LOGO_NSH_1AFB08E4_16,
        30: LOGO_NSH_1AFB08E4_30,
        32: LOGO_NSH_1AFB08E4_32,
    },
    # RBNY; source sha256 e70113e38ec451a811da6f0e1c7db5b36ca2f1c475e5f44d43ea015061abb6d4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/190.png&h=50&w=50": {
        16: LOGO_RBNY_F80D7B44_16,
        30: LOGO_RBNY_F80D7B44_30,
        32: LOGO_RBNY_F80D7B44_32,
    },
    # SJ; source sha256 b9b9c43059e3e99500c6154be0098339215e1efd57456fc47da1ee4a17aaaa1d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/191.png&h=50&w=50": {
        18: LOGO_SJ_FAA51F29_18,
        30: LOGO_SJ_FAA51F29_30,
        32: LOGO_SJ_FAA51F29_32,
    },
    # DC; source sha256 84b1fd6cd6c2f126d8a130a4e5045090ad005b0facfe3a645db2d6724dce740e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/193.png&h=50&w=50": {
        16: LOGO_DC_D38324BB_16,
        30: LOGO_DC_D38324BB_30,
        32: LOGO_DC_D38324BB_32,
    },
    # MIA; source sha256 6ae6ca25449abe8542a026a3f66fc31b43fa9d67e46f26f591f5d302c34b9de5
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/20232.png&h=50&w=50": {
        14: LOGO_MIA_5D1D18E7_14,
        30: LOGO_MIA_5D1D18E7_30,
        32: LOGO_MIA_5D1D18E7_32,
    },
    # ATX; source sha256 e32ce2fc93718cf850ef12349a344642a5ff2a072a6d44a57572885d5e5abe40
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/20906.png&h=50&w=50": {
        18: LOGO_ATX_8BF537A7_18,
        30: LOGO_ATX_8BF537A7_30,
        32: LOGO_ATX_8BF537A7_32,
    },
    # CLT; source sha256 73cd9cd354b87ddad2b01ca9dab7f2d27003f167965bf1ee0c6d5ab2f7502bf1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/21300.png&h=50&w=50": {
        16: LOGO_CLT_C2C31799_16,
        30: LOGO_CLT_C2C31799_30,
        32: LOGO_CLT_C2C31799_32,
    },
    # STL; source sha256 d9e3409e22fdfee0bbd4a17cd27bc454a7aaf6b9bcacbd101458b7c2f441e82a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/21812.png&h=50&w=50": {
        16: LOGO_STL_68835500_16,
        30: LOGO_STL_68835500_30,
        32: LOGO_STL_68835500_32,
    },
    # SD; source sha256 9334fda5de95775cade74a2a4795435de32687a75e413e7f7ca84686d3c260dc
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/22529.png&h=50&w=50": {
        16: LOGO_SD_4C5D45AD_16,
        30: LOGO_SD_4C5D45AD_30,
        32: LOGO_SD_4C5D45AD_32,
    },
    # RSL; source sha256 62014a3dd404f319e48dbe79a1ed9fff5a768e5c0cdcd57a09ae551bdaf9800d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/4771.png&h=50&w=50": {
        18: LOGO_RSL_AC1B66CC_18,
        30: LOGO_RSL_AC1B66CC_30,
        32: LOGO_RSL_AC1B66CC_32,
    },
    # HOU; source sha256 9c1bbc74270aed4125de62f33f879d15e90f6e50a4ba0d02d2cf9fde67ca6871
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/6077.png&h=50&w=50": {
        16: LOGO_HOU_D40ADE75_16,
        30: LOGO_HOU_D40ADE75_30,
        32: LOGO_HOU_D40ADE75_32,
    },
    # TOR; source sha256 e110094f02284201d73d990dcc8abbfa5a7aeb06f9dc8f8fddc1ea33a9f9f2f7
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/7318.png&h=50&w=50": {
        16: LOGO_TOR_5294E9D9_16,
        30: LOGO_TOR_5294E9D9_30,
        32: LOGO_TOR_5294E9D9_32,
    },
    # MTL; source sha256 65537ad10ced1121e7dfb0b6b99dde408eeb8305c609c64e38bc51f7875cb483
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/9720.png&h=50&w=50": {
        16: LOGO_MTL_C48E9498_16,
        30: LOGO_MTL_C48E9498_30,
        32: LOGO_MTL_C48E9498_32,
    },
    # POR; source sha256 cff719bc5f6223dad62a4fab53fb92c65fb5f847ff268f7436cb3cd243d45951
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/9723.png&h=50&w=50": {
        16: LOGO_POR_6CDE99E0_16,
        30: LOGO_POR_6CDE99E0_30,
        32: LOGO_POR_6CDE99E0_32,
    },
    # SEA; source sha256 d7473411d469e8484e815a5dc024aeaf0bfbce03927dd0d1414db52f766b5b6f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/9726.png&h=50&w=50": {
        16: LOGO_SEA_2ED087F3_16,
        30: LOGO_SEA_2ED087F3_30,
        32: LOGO_SEA_2ED087F3_32,
    },
    # VAN; source sha256 ccb0f3c4c7b30af552d7d0ebb18541b0ffe6081b62dd140b6cc4c624dbc090a4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/soccer/500/9727.png&h=50&w=50": {
        18: LOGO_VAN_ED555A16_18,
        30: LOGO_VAN_ED555A16_30,
        32: LOGO_VAN_ED555A16_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        14: LOGO_SHARED_3FDF1951_SOURCE,
        16: LOGO_SHARED_3FDF1951_SOURCE,
        18: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
