"""
Bundled team logos for mhkyscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/afa-756317b6-16.png", LOGO_AFA_756317B6_16 = "file")
load("images/logos/afa-756317b6-30.png", LOGO_AFA_756317B6_30 = "file")
load("images/logos/afa-756317b6-32.png", LOGO_AFA_756317B6_32 = "file")
load("images/logos/akfb-04f62eac-16.png", LOGO_AKFB_04F62EAC_16 = "file")
load("images/logos/akfb-04f62eac-30.png", LOGO_AKFB_04F62EAC_30 = "file")
load("images/logos/akfb-04f62eac-32.png", LOGO_AKFB_04F62EAC_32 = "file")
load("images/logos/army-f119d7a8-16.png", LOGO_ARMY_F119D7A8_16 = "file")
load("images/logos/army-f119d7a8-30.png", LOGO_ARMY_F119D7A8_30 = "file")
load("images/logos/army-f119d7a8-32.png", LOGO_ARMY_F119D7A8_32 = "file")
load("images/logos/asu-e507907c-16.png", LOGO_ASU_E507907C_16 = "file")
load("images/logos/asu-e507907c-30.png", LOGO_ASU_E507907C_30 = "file")
load("images/logos/asu-e507907c-32.png", LOGO_ASU_E507907C_32 = "file")
load("images/logos/ausd-d3a571af-16.png", LOGO_AUSD_D3A571AF_16 = "file")
load("images/logos/ausd-d3a571af-30.png", LOGO_AUSD_D3A571AF_30 = "file")
load("images/logos/ausd-d3a571af-32.png", LOGO_AUSD_D3A571AF_32 = "file")
load("images/logos/bc-1c250706-16.png", LOGO_BC_1C250706_16 = "file")
load("images/logos/bc-1c250706-30.png", LOGO_BC_1C250706_30 = "file")
load("images/logos/bc-1c250706-32.png", LOGO_BC_1C250706_32 = "file")
load("images/logos/bent-88caf26c-16.png", LOGO_BENT_88CAF26C_16 = "file")
load("images/logos/bent-88caf26c-30.png", LOGO_BENT_88CAF26C_30 = "file")
load("images/logos/bent-88caf26c-32.png", LOGO_BENT_88CAF26C_32 = "file")
load("images/logos/bgsu-0624502b-16.png", LOGO_BGSU_0624502B_16 = "file")
load("images/logos/bgsu-0624502b-30.png", LOGO_BGSU_0624502B_30 = "file")
load("images/logos/bgsu-0624502b-32.png", LOGO_BGSU_0624502B_32 = "file")
load("images/logos/brwn-75f5e894-16.png", LOGO_BRWN_75F5E894_16 = "file")
load("images/logos/brwn-75f5e894-30.png", LOGO_BRWN_75F5E894_30 = "file")
load("images/logos/brwn-75f5e894-32.png", LOGO_BRWN_75F5E894_32 = "file")
load("images/logos/bst-3c1d82b7-16.png", LOGO_BST_3C1D82B7_16 = "file")
load("images/logos/bst-3c1d82b7-30.png", LOGO_BST_3C1D82B7_30 = "file")
load("images/logos/bst-3c1d82b7-32.png", LOGO_BST_3C1D82B7_32 = "file")
load("images/logos/bu-62db6e60-16.png", LOGO_BU_62DB6E60_16 = "file")
load("images/logos/bu-62db6e60-30.png", LOGO_BU_62DB6E60_30 = "file")
load("images/logos/bu-62db6e60-32.png", LOGO_BU_62DB6E60_32 = "file")
load("images/logos/can-440ab5e7-16.png", LOGO_CAN_440AB5E7_16 = "file")
load("images/logos/can-440ab5e7-30.png", LOGO_CAN_440AB5E7_30 = "file")
load("images/logos/can-440ab5e7-32.png", LOGO_CAN_440AB5E7_32 = "file")
load("images/logos/clar-021d4168-16.png", LOGO_CLAR_021D4168_16 = "file")
load("images/logos/clar-021d4168-30.png", LOGO_CLAR_021D4168_30 = "file")
load("images/logos/clar-021d4168-32.png", LOGO_CLAR_021D4168_32 = "file")
load("images/logos/colc-65a1c8a1-16.png", LOGO_COLC_65A1C8A1_16 = "file")
load("images/logos/colc-65a1c8a1-30.png", LOGO_COLC_65A1C8A1_30 = "file")
load("images/logos/colc-65a1c8a1-32.png", LOGO_COLC_65A1C8A1_32 = "file")
load("images/logos/colg-caa2de38-source.png", LOGO_COLG_CAA2DE38_SOURCE = "file")
load("images/logos/conn-0eae01db-16.png", LOGO_CONN_0EAE01DB_16 = "file")
load("images/logos/conn-0eae01db-30.png", LOGO_CONN_0EAE01DB_30 = "file")
load("images/logos/conn-0eae01db-32.png", LOGO_CONN_0EAE01DB_32 = "file")
load("images/logos/cor-cc002d79-16.png", LOGO_COR_CC002D79_16 = "file")
load("images/logos/cor-cc002d79-30.png", LOGO_COR_CC002D79_30 = "file")
load("images/logos/cor-cc002d79-32.png", LOGO_COR_CC002D79_32 = "file")
load("images/logos/dart-8e344e71-16.png", LOGO_DART_8E344E71_16 = "file")
load("images/logos/dart-8e344e71-30.png", LOGO_DART_8E344E71_30 = "file")
load("images/logos/dart-8e344e71-32.png", LOGO_DART_8E344E71_32 = "file")
load("images/logos/den-89ddb894-16.png", LOGO_DEN_89DDB894_16 = "file")
load("images/logos/den-89ddb894-30.png", LOGO_DEN_89DDB894_30 = "file")
load("images/logos/den-89ddb894-32.png", LOGO_DEN_89DDB894_32 = "file")
load("images/logos/frst-60f524f7-16.png", LOGO_FRST_60F524F7_16 = "file")
load("images/logos/frst-60f524f7-30.png", LOGO_FRST_60F524F7_30 = "file")
load("images/logos/frst-60f524f7-32.png", LOGO_FRST_60F524F7_32 = "file")
load("images/logos/harv-9b4a1647-16.png", LOGO_HARV_9B4A1647_16 = "file")
load("images/logos/harv-9b4a1647-30.png", LOGO_HARV_9B4A1647_30 = "file")
load("images/logos/harv-9b4a1647-32.png", LOGO_HARV_9B4A1647_32 = "file")
load("images/logos/hc-62b145e5-16.png", LOGO_HC_62B145E5_16 = "file")
load("images/logos/hc-62b145e5-30.png", LOGO_HC_62B145E5_30 = "file")
load("images/logos/hc-62b145e5-32.png", LOGO_HC_62B145E5_32 = "file")
load("images/logos/lin-21c048c3-16.png", LOGO_LIN_21C048C3_16 = "file")
load("images/logos/lin-21c048c3-30.png", LOGO_LIN_21C048C3_30 = "file")
load("images/logos/lin-21c048c3-32.png", LOGO_LIN_21C048C3_32 = "file")
load("images/logos/liu-49479765-16.png", LOGO_LIU_49479765_16 = "file")
load("images/logos/liu-49479765-30.png", LOGO_LIU_49479765_30 = "file")
load("images/logos/liu-49479765-32.png", LOGO_LIU_49479765_32 = "file")
load("images/logos/lss-6f9d6332-16.png", LOGO_LSS_6F9D6332_16 = "file")
load("images/logos/lss-6f9d6332-30.png", LOGO_LSS_6F9D6332_30 = "file")
load("images/logos/lss-6f9d6332-32.png", LOGO_LSS_6F9D6332_32 = "file")
load("images/logos/m-oh-7df29cf1-16.png", LOGO_M_OH_7DF29CF1_16 = "file")
load("images/logos/m-oh-7df29cf1-30.png", LOGO_M_OH_7DF29CF1_30 = "file")
load("images/logos/m-oh-7df29cf1-32.png", LOGO_M_OH_7DF29CF1_32 = "file")
load("images/logos/mass-45b8266b-16.png", LOGO_MASS_45B8266B_16 = "file")
load("images/logos/mass-45b8266b-30.png", LOGO_MASS_45B8266B_30 = "file")
load("images/logos/mass-45b8266b-32.png", LOGO_MASS_45B8266B_32 = "file")
load("images/logos/me-17d8d8de-16.png", LOGO_ME_17D8D8DE_16 = "file")
load("images/logos/me-17d8d8de-30.png", LOGO_ME_17D8D8DE_30 = "file")
load("images/logos/me-17d8d8de-32.png", LOGO_ME_17D8D8DE_32 = "file")
load("images/logos/merc-c45157ba-16.png", LOGO_MERC_C45157BA_16 = "file")
load("images/logos/merc-c45157ba-30.png", LOGO_MERC_C45157BA_30 = "file")
load("images/logos/merc-c45157ba-32.png", LOGO_MERC_C45157BA_32 = "file")
load("images/logos/mich-15b6d788-16.png", LOGO_MICH_15B6D788_16 = "file")
load("images/logos/mich-15b6d788-30.png", LOGO_MICH_15B6D788_30 = "file")
load("images/logos/mich-15b6d788-32.png", LOGO_MICH_15B6D788_32 = "file")
load("images/logos/minn-53b35682-16.png", LOGO_MINN_53B35682_16 = "file")
load("images/logos/minn-53b35682-30.png", LOGO_MINN_53B35682_30 = "file")
load("images/logos/minn-53b35682-32.png", LOGO_MINN_53B35682_32 = "file")
load("images/logos/mnst-74e0260f-16.png", LOGO_MNST_74E0260F_16 = "file")
load("images/logos/mnst-74e0260f-30.png", LOGO_MNST_74E0260F_30 = "file")
load("images/logos/mnst-74e0260f-32.png", LOGO_MNST_74E0260F_32 = "file")
load("images/logos/mrmk-92c4a2d8-16.png", LOGO_MRMK_92C4A2D8_16 = "file")
load("images/logos/mrmk-92c4a2d8-30.png", LOGO_MRMK_92C4A2D8_30 = "file")
load("images/logos/mrmk-92c4a2d8-32.png", LOGO_MRMK_92C4A2D8_32 = "file")
load("images/logos/msu-46fcbc50-16.png", LOGO_MSU_46FCBC50_16 = "file")
load("images/logos/msu-46fcbc50-30.png", LOGO_MSU_46FCBC50_30 = "file")
load("images/logos/msu-46fcbc50-32.png", LOGO_MSU_46FCBC50_32 = "file")
load("images/logos/mtu-a7a4f8eb-16.png", LOGO_MTU_A7A4F8EB_16 = "file")
load("images/logos/mtu-a7a4f8eb-30.png", LOGO_MTU_A7A4F8EB_30 = "file")
load("images/logos/mtu-a7a4f8eb-32.png", LOGO_MTU_A7A4F8EB_32 = "file")
load("images/logos/nd-9b1d2931-16.png", LOGO_ND_9B1D2931_16 = "file")
load("images/logos/nd-9b1d2931-30.png", LOGO_ND_9B1D2931_30 = "file")
load("images/logos/nd-9b1d2931-32.png", LOGO_ND_9B1D2931_32 = "file")
load("images/logos/ne-f5ac8a6f-16.png", LOGO_NE_F5AC8A6F_16 = "file")
load("images/logos/ne-f5ac8a6f-30.png", LOGO_NE_F5AC8A6F_30 = "file")
load("images/logos/ne-f5ac8a6f-32.png", LOGO_NE_F5AC8A6F_32 = "file")
load("images/logos/nia-f4980f2c-16.png", LOGO_NIA_F4980F2C_16 = "file")
load("images/logos/nia-f4980f2c-30.png", LOGO_NIA_F4980F2C_30 = "file")
load("images/logos/nia-f4980f2c-32.png", LOGO_NIA_F4980F2C_32 = "file")
load("images/logos/nmi-6fead4fe-16.png", LOGO_NMI_6FEAD4FE_16 = "file")
load("images/logos/nmi-6fead4fe-30.png", LOGO_NMI_6FEAD4FE_30 = "file")
load("images/logos/nmi-6fead4fe-32.png", LOGO_NMI_6FEAD4FE_32 = "file")
load("images/logos/oma-98c20d25-16.png", LOGO_OMA_98C20D25_16 = "file")
load("images/logos/oma-98c20d25-30.png", LOGO_OMA_98C20D25_30 = "file")
load("images/logos/oma-98c20d25-32.png", LOGO_OMA_98C20D25_32 = "file")
load("images/logos/osu-1741a62a-16.png", LOGO_OSU_1741A62A_16 = "file")
load("images/logos/osu-1741a62a-30.png", LOGO_OSU_1741A62A_30 = "file")
load("images/logos/osu-1741a62a-32.png", LOGO_OSU_1741A62A_32 = "file")
load("images/logos/prin-2246b4fb-16.png", LOGO_PRIN_2246B4FB_16 = "file")
load("images/logos/prin-2246b4fb-30.png", LOGO_PRIN_2246B4FB_30 = "file")
load("images/logos/prin-2246b4fb-32.png", LOGO_PRIN_2246B4FB_32 = "file")
load("images/logos/prov-98b5f47c-16.png", LOGO_PROV_98B5F47C_16 = "file")
load("images/logos/prov-98b5f47c-30.png", LOGO_PROV_98B5F47C_30 = "file")
load("images/logos/prov-98b5f47c-32.png", LOGO_PROV_98B5F47C_32 = "file")
load("images/logos/psu-2f806c30-16.png", LOGO_PSU_2F806C30_16 = "file")
load("images/logos/psu-2f806c30-30.png", LOGO_PSU_2F806C30_30 = "file")
load("images/logos/psu-2f806c30-32.png", LOGO_PSU_2F806C30_32 = "file")
load("images/logos/quin-ffdacf90-16.png", LOGO_QUIN_FFDACF90_16 = "file")
load("images/logos/quin-ffdacf90-30.png", LOGO_QUIN_FFDACF90_30 = "file")
load("images/logos/quin-ffdacf90-32.png", LOGO_QUIN_FFDACF90_32 = "file")
load("images/logos/rit-c8abce1d-16.png", LOGO_RIT_C8ABCE1D_16 = "file")
load("images/logos/rit-c8abce1d-30.png", LOGO_RIT_C8ABCE1D_30 = "file")
load("images/logos/rit-c8abce1d-32.png", LOGO_RIT_C8ABCE1D_32 = "file")
load("images/logos/rmu-6e877051-16.png", LOGO_RMU_6E877051_16 = "file")
load("images/logos/rmu-6e877051-30.png", LOGO_RMU_6E877051_30 = "file")
load("images/logos/rmu-6e877051-32.png", LOGO_RMU_6E877051_32 = "file")
load("images/logos/rpi-14a04469-16.png", LOGO_RPI_14A04469_16 = "file")
load("images/logos/rpi-14a04469-30.png", LOGO_RPI_14A04469_30 = "file")
load("images/logos/rpi-14a04469-32.png", LOGO_RPI_14A04469_32 = "file")
load("images/logos/scsu-61e963a6-16.png", LOGO_SCSU_61E963A6_16 = "file")
load("images/logos/scsu-61e963a6-30.png", LOGO_SCSU_61E963A6_30 = "file")
load("images/logos/scsu-61e963a6-32.png", LOGO_SCSU_61E963A6_32 = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/shu-b4d359a7-16.png", LOGO_SHU_B4D359A7_16 = "file")
load("images/logos/shu-b4d359a7-30.png", LOGO_SHU_B4D359A7_30 = "file")
load("images/logos/shu-b4d359a7-32.png", LOGO_SHU_B4D359A7_32 = "file")
load("images/logos/stmn-12757a99-16.png", LOGO_STMN_12757A99_16 = "file")
load("images/logos/stmn-12757a99-30.png", LOGO_STMN_12757A99_30 = "file")
load("images/logos/stmn-12757a99-32.png", LOGO_STMN_12757A99_32 = "file")
load("images/logos/stonehill-41235083-16.png", LOGO_STONEHILL_41235083_16 = "file")
load("images/logos/stonehill-41235083-30.png", LOGO_STONEHILL_41235083_30 = "file")
load("images/logos/stonehill-41235083-32.png", LOGO_STONEHILL_41235083_32 = "file")
load("images/logos/uaa-359ea8e3-16.png", LOGO_UAA_359EA8E3_16 = "file")
load("images/logos/uaa-359ea8e3-30.png", LOGO_UAA_359EA8E3_30 = "file")
load("images/logos/uaa-359ea8e3-32.png", LOGO_UAA_359EA8E3_32 = "file")
load("images/logos/umd-9a149162-16.png", LOGO_UMD_9A149162_16 = "file")
load("images/logos/umd-9a149162-30.png", LOGO_UMD_9A149162_30 = "file")
load("images/logos/umd-9a149162-32.png", LOGO_UMD_9A149162_32 = "file")
load("images/logos/uml-3d6c23f7-16.png", LOGO_UML_3D6C23F7_16 = "file")
load("images/logos/uml-3d6c23f7-30.png", LOGO_UML_3D6C23F7_30 = "file")
load("images/logos/uml-3d6c23f7-32.png", LOGO_UML_3D6C23F7_32 = "file")
load("images/logos/und-de6298f6-16.png", LOGO_UND_DE6298F6_16 = "file")
load("images/logos/und-de6298f6-30.png", LOGO_UND_DE6298F6_30 = "file")
load("images/logos/und-de6298f6-32.png", LOGO_UND_DE6298F6_32 = "file")
load("images/logos/unh-17a01ede-16.png", LOGO_UNH_17A01EDE_16 = "file")
load("images/logos/unh-17a01ede-30.png", LOGO_UNH_17A01EDE_30 = "file")
load("images/logos/unh-17a01ede-32.png", LOGO_UNH_17A01EDE_32 = "file")
load("images/logos/unny-d9ba8a46-16.png", LOGO_UNNY_D9BA8A46_16 = "file")
load("images/logos/unny-d9ba8a46-30.png", LOGO_UNNY_D9BA8A46_30 = "file")
load("images/logos/unny-d9ba8a46-32.png", LOGO_UNNY_D9BA8A46_32 = "file")
load("images/logos/usl-47dde792-16.png", LOGO_USL_47DDE792_16 = "file")
load("images/logos/usl-47dde792-30.png", LOGO_USL_47DDE792_30 = "file")
load("images/logos/usl-47dde792-32.png", LOGO_USL_47DDE792_32 = "file")
load("images/logos/uvm-30577d4a-16.png", LOGO_UVM_30577D4A_16 = "file")
load("images/logos/uvm-30577d4a-30.png", LOGO_UVM_30577D4A_30 = "file")
load("images/logos/uvm-30577d4a-32.png", LOGO_UVM_30577D4A_32 = "file")
load("images/logos/wisc-99398fab-16.png", LOGO_WISC_99398FAB_16 = "file")
load("images/logos/wisc-99398fab-30.png", LOGO_WISC_99398FAB_30 = "file")
load("images/logos/wisc-99398fab-32.png", LOGO_WISC_99398FAB_32 = "file")
load("images/logos/wmu-30cab258-16.png", LOGO_WMU_30CAB258_16 = "file")
load("images/logos/wmu-30cab258-30.png", LOGO_WMU_30CAB258_30 = "file")
load("images/logos/wmu-30cab258-32.png", LOGO_WMU_30CAB258_32 = "file")
load("images/logos/yale-6184fba5-16.png", LOGO_YALE_6184FBA5_16 = "file")
load("images/logos/yale-6184fba5-30.png", LOGO_YALE_6184FBA5_30 = "file")
load("images/logos/yale-6184fba5-32.png", LOGO_YALE_6184FBA5_32 = "file")

BUNDLED_LOGOS = {
    # UAA; source sha256 c222b601b5442c34fa47dd431a606c5c5f5ee3c6dbd4285999561a57625ac429
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/1.png": {
        16: LOGO_UAA_359EA8E3_16,
        30: LOGO_UAA_359EA8E3_30,
        32: LOGO_UAA_359EA8E3_32,
    },
    # BC; source sha256 50367573fe1930fb83ac09db4b8ff4ef012bf531fab3027c2b1b6cfd013b975d
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/103.png": {
        16: LOGO_BC_1C250706_16,
        30: LOGO_BC_1C250706_30,
        32: LOGO_BC_1C250706_32,
    },
    # BU; source sha256 2d94917986379265b51b65dab2f96bd759acd006c819cbb33d57a863f105cd91
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/104.png": {
        16: LOGO_BU_62DB6E60_16,
        30: LOGO_BU_62DB6E60_30,
        32: LOGO_BU_62DB6E60_32,
    },
    # HC; source sha256 027c38dcc223cca09181ac4b0e56e1a84573a6f121d080b3bac8eea614776d9a
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/107.png": {
        16: LOGO_HC_62B145E5_16,
        30: LOGO_HC_62B145E5_30,
        32: LOGO_HC_62B145E5_32,
    },
    # HARV; source sha256 4018648beaa1f1f51c97abb92ccf3d658dc976de28a27d069a28f1127e99c1d3
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/108.png": {
        16: LOGO_HARV_9B4A1647_16,
        30: LOGO_HARV_9B4A1647_30,
        32: LOGO_HARV_9B4A1647_32,
    },
    # LIU; source sha256 4becedf6261bd38251eded6a221de154d79dd54b20ef123a6c15dd78ae66d9be
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/110133.png": {
        16: LOGO_LIU_49479765_16,
        30: LOGO_LIU_49479765_30,
        32: LOGO_LIU_49479765_32,
    },
    # NE; source sha256 ed4f66035766590085072c968f69b8064ad6cfdbf7f69e6fd85e0f3c5d2b5ab3
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/111.png": {
        16: LOGO_NE_F5AC8A6F_16,
        30: LOGO_NE_F5AC8A6F_30,
        32: LOGO_NE_F5AC8A6F_32,
    },
    # MASS; source sha256 5e38fbbec958b15d5ff82a8f5f52646216b9a4cc1d53ece8bc72322365f0e5c0
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/113.png": {
        16: LOGO_MASS_45B8266B_16,
        30: LOGO_MASS_45B8266B_30,
        32: LOGO_MASS_45B8266B_32,
    },
    # NMI; source sha256 134cd5ad910aa076e66eb05cdb9d3aa2ea60e146603a1f6f662ab3a1f0422eb1
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/128.png": {
        16: LOGO_NMI_6FEAD4FE_16,
        30: LOGO_NMI_6FEAD4FE_30,
        32: LOGO_NMI_6FEAD4FE_32,
    },
    # MICH; source sha256 f6f492cd2b0f6855912d909852ee6fe5e71094a94518c1b38273e680a27d4236
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/130.png": {
        16: LOGO_MICH_15B6D788_16,
        30: LOGO_MICH_15B6D788_30,
        32: LOGO_MICH_15B6D788_32,
    },
    # BST; source sha256 cbc0c4d49fa2c92a32e0890b92c7ab1d6ff4562bd6cbaf9d64611e739b534b8e
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/132.png": {
        16: LOGO_BST_3C1D82B7_16,
        30: LOGO_BST_3C1D82B7_30,
        32: LOGO_BST_3C1D82B7_32,
    },
    # UMD; source sha256 c4b60aabdf0fea84d6d2d93528c6aa4384f0bbe38d15467e7ba240fb97a556f1
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/134.png": {
        16: LOGO_UMD_9A149162_16,
        30: LOGO_UMD_9A149162_30,
        32: LOGO_UMD_9A149162_32,
    },
    # UND; source sha256 aa01210973a92384cd39a795dabfede0997369872207fb7c86293f9a2679b8de
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/155.png": {
        16: LOGO_UND_DE6298F6_16,
        30: LOGO_UND_DE6298F6_30,
        32: LOGO_UND_DE6298F6_32,
    },
    # DART; source sha256 66a6b917e25b486a32a645f3973e86e0b8a9350ddfe6efb41f59b3e5f5f58372
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/159.png": {
        16: LOGO_DART_8E344E71_16,
        30: LOGO_DART_8E344E71_30,
        32: LOGO_DART_8E344E71_32,
    },
    # UNH; source sha256 d1d979df65ec167158c59cc5f359111c4fcc883beeadc3532c9d82e577f603c2
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/160.png": {
        16: LOGO_UNH_17A01EDE_16,
        30: LOGO_UNH_17A01EDE_30,
        32: LOGO_UNH_17A01EDE_32,
    },
    # PRIN; source sha256 1ba19c1ecc721cb6fd92327b967c54d2efc4181f77fc6f18afd84e4a2f3c644b
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/163.png": {
        16: LOGO_PRIN_2246B4FB_16,
        30: LOGO_PRIN_2246B4FB_30,
        32: LOGO_PRIN_2246B4FB_32,
    },
    # COR; source sha256 7388cfee9a0bbe5dfa237159b6a56a52869815edfa72a2878b9823709ff02a19
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/172.png": {
        16: LOGO_COR_CC002D79_16,
        30: LOGO_COR_CC002D79_30,
        32: LOGO_COR_CC002D79_32,
    },
    # RIT; source sha256 1a490b84f2adb85e0fc705696b48d4b3687325e93bca1b810b07494b2bb09b55
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/178.png": {
        16: LOGO_RIT_C8ABCE1D_16,
        30: LOGO_RIT_C8ABCE1D_30,
        32: LOGO_RIT_C8ABCE1D_32,
    },
    # BGSU; source sha256 43ad73ad7d55ec0b7c83a68d958bed6d7436dd89e25e949d46491411a9d3ab97
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/189.png": {
        16: LOGO_BGSU_0624502B_16,
        30: LOGO_BGSU_0624502B_30,
        32: LOGO_BGSU_0624502B_32,
    },
    # M-OH; source sha256 34189530de64ad02b71f20552b907b1f587f892010b2023d01b975e4c1fee534
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/193.png": {
        16: LOGO_M_OH_7DF29CF1_16,
        30: LOGO_M_OH_7DF29CF1_30,
        32: LOGO_M_OH_7DF29CF1_32,
    },
    # OSU; source sha256 115e02541d5b6ce4c747022570def5dcb2d6b4cd3d3e1cad948fde567ca16d87
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/194.png": {
        16: LOGO_OSU_1741A62A_16,
        30: LOGO_OSU_1741A62A_30,
        32: LOGO_OSU_1741A62A_32,
    },
    # AFA; source sha256 a557fd15811866fbc4ea950d4d96ad9f35e96c2991162d1b073067535b2d589d
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2005.png": {
        16: LOGO_AFA_756317B6_16,
        30: LOGO_AFA_756317B6_30,
        32: LOGO_AFA_756317B6_32,
    },
    # AUSD; source sha256 67cf336820bb28048245377e4d12bde02d0ff9873cff0139fa680a6f7e491a44
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2043.png": {
        16: LOGO_AUSD_D3A571AF_16,
        30: LOGO_AUSD_D3A571AF_30,
        32: LOGO_AUSD_D3A571AF_32,
    },
    # BENT; source sha256 96a95da545d30dd57f377b71fff3b8c77d68204ed13a9be3c74cdfae68e5074f
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2060.png": {
        16: LOGO_BENT_88CAF26C_16,
        30: LOGO_BENT_88CAF26C_30,
        32: LOGO_BENT_88CAF26C_32,
    },
    # CAN; source sha256 aee47a103aadbbd258fb724a439eb06536cf3ade006d408e246c6fd1e961510e
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2099.png": {
        16: LOGO_CAN_440AB5E7_16,
        30: LOGO_CAN_440AB5E7_30,
        32: LOGO_CAN_440AB5E7_32,
    },
    # PSU; source sha256 f51046e458919e56b196f075d9b7224c7f4f4eb9451f71dd0f861977b6e29f4e
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/213.png": {
        16: LOGO_PSU_2F806C30_16,
        30: LOGO_PSU_2F806C30_30,
        32: LOGO_PSU_2F806C30_32,
    },
    # CLAR; source sha256 6c76c1dfbcf747d3270b6d0805c4895b021a2e250a64683540461008f7cce589
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2137.png": {
        16: LOGO_CLAR_021D4168_16,
        30: LOGO_CLAR_021D4168_30,
        32: LOGO_CLAR_021D4168_32,
    },
    # COLC; source sha256 e56de03706796ca3e1c411a75732b1a9ec91452f7b1221c6deb550d7f0291902
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2144.png": {
        16: LOGO_COLC_65A1C8A1_16,
        30: LOGO_COLC_65A1C8A1_30,
        32: LOGO_COLC_65A1C8A1_32,
    },
    # DEN; source sha256 829a0380cd154d1fdafbbdb1adbe4fcce93559ea8813f56228b779253f9579f3
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2172.png": {
        16: LOGO_DEN_89DDB894_16,
        30: LOGO_DEN_89DDB894_30,
        32: LOGO_DEN_89DDB894_32,
    },
    # FRST; source sha256 fdb15284bd42aad949fe4165406aad07a981201ffebd4bad19ce5177bb870452
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2222.png": {
        16: LOGO_FRST_60F524F7_16,
        30: LOGO_FRST_60F524F7_30,
        32: LOGO_FRST_60F524F7_32,
    },
    # BRWN; source sha256 e77048fdc059fa47441bc03ca6cf2ac8e66bf0e0d817ff6c1c7d82f4bc47a0cb
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/225.png": {
        16: LOGO_BRWN_75F5E894_16,
        30: LOGO_BRWN_75F5E894_30,
        32: LOGO_BRWN_75F5E894_32,
    },
    # UML; source sha256 da5b82d033923244a2d6ca0033e31bf35c2badc8ac006be907fc19a9cd4a6d97
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2349.png": {
        16: LOGO_UML_3D6C23F7_16,
        30: LOGO_UML_3D6C23F7_30,
        32: LOGO_UML_3D6C23F7_32,
    },
    # MNST; source sha256 410fd63d6498474eba6b7ee9f820000139a74840104c01097a39a8b12798e2ba
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2364.png": {
        16: LOGO_MNST_74E0260F_16,
        30: LOGO_MNST_74E0260F_30,
        32: LOGO_MNST_74E0260F_32,
    },
    # MERC; source sha256 4012419ebceecc2d19813038e331a1bb3b97c6976b4f48d1a670cf38e53b60e4
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2385.png": {
        16: LOGO_MERC_C45157BA_16,
        30: LOGO_MERC_C45157BA_30,
        32: LOGO_MERC_C45157BA_32,
    },
    # MTU; source sha256 3f8d84bed1ec64e276de7aef373d9a458d7e261499acefd761292549e87ec915
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2392.png": {
        16: LOGO_MTU_A7A4F8EB_16,
        30: LOGO_MTU_A7A4F8EB_30,
        32: LOGO_MTU_A7A4F8EB_32,
    },
    # OMA; source sha256 3a6f092732988937e8ec930343afc66e82258defdc32879960518ba3b6d2e9a3
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2437.png": {
        16: LOGO_OMA_98C20D25_16,
        30: LOGO_OMA_98C20D25_30,
        32: LOGO_OMA_98C20D25_32,
    },
    # PROV; source sha256 d7de204b905fe9b67f982c2b9ffb4bd0a7224ee5b60c36e4a07a7ec741080149
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2507.png": {
        16: LOGO_PROV_98B5F47C_16,
        30: LOGO_PROV_98B5F47C_30,
        32: LOGO_PROV_98B5F47C_32,
    },
    # QUIN; source sha256 05602aa11ffd7ebf21bf2830a6216475b512e6bcad6222b7db02a573accd43a0
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2514.png": {
        16: LOGO_QUIN_FFDACF90_16,
        30: LOGO_QUIN_FFDACF90_30,
        32: LOGO_QUIN_FFDACF90_32,
    },
    # RMU; source sha256 6a0c84b7020b728e347680adbc87daf7435c2767cb803d89a81353a17d650c14
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2523.png": {
        16: LOGO_RMU_6E877051_16,
        30: LOGO_RMU_6E877051_30,
        32: LOGO_RMU_6E877051_32,
    },
    # RPI; source sha256 2d7875adfa044daa3b762650870e169c60eeb2e1dd5a5efb53a140ce956e0509
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2528.png": {
        16: LOGO_RPI_14A04469_16,
        30: LOGO_RPI_14A04469_30,
        32: LOGO_RPI_14A04469_32,
    },
    # SHU; source sha256 71dd8f23377d56fa5a95e8c3ab4ccd6230d005d32691090b74d44d66e0be4b97
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2529.png": {
        16: LOGO_SHU_B4D359A7_16,
        30: LOGO_SHU_B4D359A7_30,
        32: LOGO_SHU_B4D359A7_32,
    },
    # SCSU; source sha256 9be513a2696ca53956339e2f859c2fc4b678c067ccebe59494d546e26ec3c725
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2594.png": {
        16: LOGO_SCSU_61E963A6_16,
        30: LOGO_SCSU_61E963A6_30,
        32: LOGO_SCSU_61E963A6_32,
    },
    # UVM; source sha256 128bba7eef54187f01c6a6d0b6ec33c3ea2d16cfc789b9636cd8ba2022c996fa
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/261.png": {
        16: LOGO_UVM_30577D4A_16,
        30: LOGO_UVM_30577D4A_30,
        32: LOGO_UVM_30577D4A_32,
    },
    # WMU; source sha256 ba9730e850e04c72cacbbd74c84b53cde7cc1134be55a05e050c2fcc62beebd9
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2711.png": {
        16: LOGO_WMU_30CAB258_16,
        30: LOGO_WMU_30CAB258_30,
        32: LOGO_WMU_30CAB258_32,
    },
    # MRMK; source sha256 50145f8c623bddbaa1e5890b49a12dc4cdbf078467aa459e23c1be2afc517f3c
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2771.png": {
        16: LOGO_MRMK_92C4A2D8_16,
        30: LOGO_MRMK_92C4A2D8_30,
        32: LOGO_MRMK_92C4A2D8_32,
    },
    # USL; source sha256 42c7210529ba11477cd206b8545cc2ee60f1bc345682102ad492814206c2e981
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2779.png": {
        16: LOGO_USL_47DDE792_16,
        30: LOGO_USL_47DDE792_30,
        32: LOGO_USL_47DDE792_32,
    },
    # UNNY; source sha256 e5706afb1d78ba51d00d04bf9d2010569ebcd16d4711a6b1be3df2745f9f9aa0
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2785.png": {
        16: LOGO_UNNY_D9BA8A46_16,
        30: LOGO_UNNY_D9BA8A46_30,
        32: LOGO_UNNY_D9BA8A46_32,
    },
    # LIN; source sha256 e563c230bae64bcdc7e899c221f1a851a97a8b2fb863439d17e6e501bf98a187
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2815.png": {
        16: LOGO_LIN_21C048C3_16,
        30: LOGO_LIN_21C048C3_30,
        32: LOGO_LIN_21C048C3_32,
    },
    # STONEHILL; source sha256 db01008fd8577b962aa597f7a64ed7e2f863b6d9e488ffe814f71091eaa54ca6
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/284.png": {
        16: LOGO_STONEHILL_41235083_16,
        30: LOGO_STONEHILL_41235083_30,
        32: LOGO_STONEHILL_41235083_32,
    },
    # LSS; source sha256 b9b450b1d94e70e472f606a18bee3ecb53f77f628c4b4037c2131f8123ff840b
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/285.png": {
        16: LOGO_LSS_6F9D6332_16,
        30: LOGO_LSS_6F9D6332_30,
        32: LOGO_LSS_6F9D6332_32,
    },
    # STMN; source sha256 0919ae81afb2cb501fd2eb65c9ed9a2006b5d75b489a3e46916c4925567b7424
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/2900.png": {
        16: LOGO_STMN_12757A99_16,
        30: LOGO_STMN_12757A99_30,
        32: LOGO_STMN_12757A99_32,
    },
    # AKFB; source sha256 08e2add4644c5470a492e755b939c5e3f37295c13c8b827151abae4bf5a28b6c
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/298.png": {
        16: LOGO_AKFB_04F62EAC_16,
        30: LOGO_AKFB_04F62EAC_30,
        32: LOGO_AKFB_04F62EAC_32,
    },
    # ME; source sha256 7de3ab29e9a6a7cbeab35fa14383b643539c9f52b804785981ccec095e4cfeef
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/311.png": {
        16: LOGO_ME_17D8D8DE_16,
        30: LOGO_ME_17D8D8DE_30,
        32: LOGO_ME_17D8D8DE_32,
    },
    # NIA; source sha256 c3409a112061c6cffe4d5b86b52431703acad3cad7cad569a117eb45ed024a15
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/315.png": {
        16: LOGO_NIA_F4980F2C_16,
        30: LOGO_NIA_F4980F2C_30,
        32: LOGO_NIA_F4980F2C_32,
    },
    # ARMY; source sha256 1e25e17ed044105f8f6160e5a468852cc75e3c1214c07640186ac8b4e1981c64
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/349.png": {
        16: LOGO_ARMY_F119D7A8_16,
        30: LOGO_ARMY_F119D7A8_30,
        32: LOGO_ARMY_F119D7A8_32,
    },
    # CONN; source sha256 b8ac9cc183445a81ac20a561807c8e95610435f28eb075b7e35fa162543af052
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/41.png": {
        16: LOGO_CONN_0EAE01DB_16,
        30: LOGO_CONN_0EAE01DB_30,
        32: LOGO_CONN_0EAE01DB_32,
    },
    # YALE; source sha256 38a3a325babea1036d6849eb7c87d6d63dbed97aa1c0bd5a03aa2d4b9bf86b07
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/43.png": {
        16: LOGO_YALE_6184FBA5_16,
        30: LOGO_YALE_6184FBA5_30,
        32: LOGO_YALE_6184FBA5_32,
    },
    # ND; source sha256 6cc8ee869ed89a9ccaacf94b5655fa6c7603e3760c210d32048a3c1b84818fcd
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/87.png": {
        16: LOGO_ND_9B1D2931_16,
        30: LOGO_ND_9B1D2931_30,
        32: LOGO_ND_9B1D2931_32,
    },
    # ASU; source sha256 ec7d7d875ad15454aca3b852c85a96ea4678a5e00fb51699da8280904d15d9e0
    "https://a.espncdn.com/i/teamlogos/ncaa/500-dark/9.png": {
        16: LOGO_ASU_E507907C_16,
        30: LOGO_ASU_E507907C_30,
        32: LOGO_ASU_E507907C_32,
    },
    # COLG; source sha256 de276bc042942b44523cd1237f327208653dadc5cb3d8237b51c97ad94a6e370
    "https://b.fssta.com/uploads/application/college/team-logos/Colgate-alternate.png": {
        16: LOGO_COLG_CAA2DE38_SOURCE,
        30: LOGO_COLG_CAA2DE38_SOURCE,
        32: LOGO_COLG_CAA2DE38_SOURCE,
    },
    # MSU; source sha256 aa18c78f63e4a9fe437f3c85960050c4560c950c639efe3a19ba78f969030b02
    "https://b.fssta.com/uploads/application/college/team-logos/MichiganState-alternate.vresize.50.50.medium.1.png": {
        16: LOGO_MSU_46FCBC50_16,
        30: LOGO_MSU_46FCBC50_30,
        32: LOGO_MSU_46FCBC50_32,
    },
    # MINN; source sha256 a53b46426afae39cd16ffde9de987c8050c9ae2e0e37b6873a23e0a44060c440
    "https://b.fssta.com/uploads/application/college/team-logos/Minnesota-alternate.vresize.50.50.medium.0.png": {
        16: LOGO_MINN_53B35682_16,
        30: LOGO_MINN_53B35682_30,
        32: LOGO_MINN_53B35682_32,
    },
    # WISC; source sha256 a83400af9ed912da7e6909bdf2c3ed3310e616a0f90fa54c5bd997ba4a022439
    "https://b.fssta.com/uploads/application/college/team-logos/Wisconsin-alternate.vresize.50.50.medium.1.png": {
        16: LOGO_WISC_99398FAB_16,
        30: LOGO_WISC_99398FAB_30,
        32: LOGO_WISC_99398FAB_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
}
