"""
Bundled team logos for cflscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/bcl-6164390f-16.png", LOGO_BCL_6164390F_16 = "file")
load("images/logos/bcl-6164390f-30.png", LOGO_BCL_6164390F_30 = "file")
load("images/logos/bcl-6164390f-32.png", LOGO_BCL_6164390F_32 = "file")
load("images/logos/csp-fddb8098-16.png", LOGO_CSP_FDDB8098_16 = "file")
load("images/logos/csp-fddb8098-30.png", LOGO_CSP_FDDB8098_30 = "file")
load("images/logos/csp-fddb8098-32.png", LOGO_CSP_FDDB8098_32 = "file")
load("images/logos/htc-e711813d-16.png", LOGO_HTC_E711813D_16 = "file")
load("images/logos/htc-e711813d-30.png", LOGO_HTC_E711813D_30 = "file")
load("images/logos/htc-e711813d-32.png", LOGO_HTC_E711813D_32 = "file")
load("images/logos/mta-9b8f5754-16.png", LOGO_MTA_9B8F5754_16 = "file")
load("images/logos/mta-9b8f5754-30.png", LOGO_MTA_9B8F5754_30 = "file")
load("images/logos/mta-9b8f5754-32.png", LOGO_MTA_9B8F5754_32 = "file")
load("images/logos/orb-aa3e6adb-16.png", LOGO_ORB_AA3E6ADB_16 = "file")
load("images/logos/orb-aa3e6adb-30.png", LOGO_ORB_AA3E6ADB_30 = "file")
load("images/logos/orb-aa3e6adb-32.png", LOGO_ORB_AA3E6ADB_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/srr-c2a13989-16.png", LOGO_SRR_C2A13989_16 = "file")
load("images/logos/srr-c2a13989-30.png", LOGO_SRR_C2A13989_30 = "file")
load("images/logos/srr-c2a13989-32.png", LOGO_SRR_C2A13989_32 = "file")
load("images/logos/tat-f4bd2b4a-16.png", LOGO_TAT_F4BD2B4A_16 = "file")
load("images/logos/tat-f4bd2b4a-30.png", LOGO_TAT_F4BD2B4A_30 = "file")
load("images/logos/tat-f4bd2b4a-32.png", LOGO_TAT_F4BD2B4A_32 = "file")
load("images/logos/wbb-18204270-16.png", LOGO_WBB_18204270_16 = "file")
load("images/logos/wbb-18204270-30.png", LOGO_WBB_18204270_30 = "file")
load("images/logos/wbb-18204270-32.png", LOGO_WBB_18204270_32 = "file")

BUNDLED_LOGOS = {
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
    # BCL; source sha256 3dd6ab99b75c8073ae1bddee886e88d9bf797e5798db7778300e8f90b05d83fd
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=bc-lions&width=40&height=40": {
        16: LOGO_BCL_6164390F_16,
        30: LOGO_BCL_6164390F_30,
        32: LOGO_BCL_6164390F_32,
    },
    # CSP; source sha256 4d0d014baf0b701f21281c8aa4cb27f9561148f404d4163d0ac2adb5818c0f16
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=calgary-stampeders&width=40&height=40": {
        16: LOGO_CSP_FDDB8098_16,
        30: LOGO_CSP_FDDB8098_30,
        32: LOGO_CSP_FDDB8098_32,
    },
    # HTC; source sha256 71ee1f4cd6c970e9864552edb53610ac97f3e9efa965931aa93417d291983921
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=hamilton-tiger-cats&width=40&height=40": {
        16: LOGO_HTC_E711813D_16,
        30: LOGO_HTC_E711813D_30,
        32: LOGO_HTC_E711813D_32,
    },
    # MTA; source sha256 d5e51c760b25723d7c684b5817482cb40fd0a064430ddff61c5735adeb4e7805
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=montreal-alouettes&width=40&height=40": {
        16: LOGO_MTA_9B8F5754_16,
        30: LOGO_MTA_9B8F5754_30,
        32: LOGO_MTA_9B8F5754_32,
    },
    # ORB; source sha256 66a49dd28acd726678fe769c28f7b6042816a2e7f7cb3a5eb79ea771387bdf63
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=ottawa-redblacks&width=40&height=40": {
        16: LOGO_ORB_AA3E6ADB_16,
        30: LOGO_ORB_AA3E6ADB_30,
        32: LOGO_ORB_AA3E6ADB_32,
    },
    # SRR; source sha256 9acddb026b5cf793e9d37f10dd5234274d0484c298c95f0543d867e712f1d651
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=saskatchewan-roughriders&width=40&height=40": {
        16: LOGO_SRR_C2A13989_16,
        30: LOGO_SRR_C2A13989_30,
        32: LOGO_SRR_C2A13989_32,
    },
    # TAT; source sha256 dbc7fb5c2db257c7e02328a2be4a9dda1b980a714705e6c42f5b969a76f7434b
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=toronto-argonauts&width=40&height=40": {
        16: LOGO_TAT_F4BD2B4A_16,
        30: LOGO_TAT_F4BD2B4A_30,
        32: LOGO_TAT_F4BD2B4A_32,
    },
    # WBB; source sha256 fe115a75228eb6aa1d03c3985877db6dcb5aa18cfa1e9761ae13d8999273508d
    "https://tsnimages.tsn.ca/ImageProvider/TeamLogo?seoId=winnipeg-blue-bombers&width=40&height=40": {
        16: LOGO_WBB_18204270_16,
        30: LOGO_WBB_18204270_30,
        32: LOGO_WBB_18204270_32,
    },
}
