"""
Bundled team logos for mlbscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/ari-0bb25cac-18.png", LOGO_ARI_0BB25CAC_18 = "file")
load("images/logos/ari-0bb25cac-30.png", LOGO_ARI_0BB25CAC_30 = "file")
load("images/logos/ari-0bb25cac-32.png", LOGO_ARI_0BB25CAC_32 = "file")
load("images/logos/ath-0fb3d2c2-16.png", LOGO_ATH_0FB3D2C2_16 = "file")
load("images/logos/ath-0fb3d2c2-30.png", LOGO_ATH_0FB3D2C2_30 = "file")
load("images/logos/ath-0fb3d2c2-32.png", LOGO_ATH_0FB3D2C2_32 = "file")
load("images/logos/atl-ca11f462-18.png", LOGO_ATL_CA11F462_18 = "file")
load("images/logos/atl-ca11f462-30.png", LOGO_ATL_CA11F462_30 = "file")
load("images/logos/atl-ca11f462-32.png", LOGO_ATL_CA11F462_32 = "file")
load("images/logos/bal-ea036e7c-16.png", LOGO_BAL_EA036E7C_16 = "file")
load("images/logos/bal-ea036e7c-30.png", LOGO_BAL_EA036E7C_30 = "file")
load("images/logos/bal-ea036e7c-32.png", LOGO_BAL_EA036E7C_32 = "file")
load("images/logos/bos-b6c728cf-16.png", LOGO_BOS_B6C728CF_16 = "file")
load("images/logos/bos-b6c728cf-30.png", LOGO_BOS_B6C728CF_30 = "file")
load("images/logos/bos-b6c728cf-32.png", LOGO_BOS_B6C728CF_32 = "file")
load("images/logos/chc-4c4db8d0-16.png", LOGO_CHC_4C4DB8D0_16 = "file")
load("images/logos/chc-4c4db8d0-30.png", LOGO_CHC_4C4DB8D0_30 = "file")
load("images/logos/chc-4c4db8d0-32.png", LOGO_CHC_4C4DB8D0_32 = "file")
load("images/logos/chw-d6adca4d-22.png", LOGO_CHW_D6ADCA4D_22 = "file")
load("images/logos/chw-d6adca4d-30.png", LOGO_CHW_D6ADCA4D_30 = "file")
load("images/logos/chw-d6adca4d-32.png", LOGO_CHW_D6ADCA4D_32 = "file")
load("images/logos/cin-33593cc6-16.png", LOGO_CIN_33593CC6_16 = "file")
load("images/logos/cin-33593cc6-30.png", LOGO_CIN_33593CC6_30 = "file")
load("images/logos/cin-33593cc6-32.png", LOGO_CIN_33593CC6_32 = "file")
load("images/logos/cle-ccd66038-16.png", LOGO_CLE_CCD66038_16 = "file")
load("images/logos/cle-ccd66038-30.png", LOGO_CLE_CCD66038_30 = "file")
load("images/logos/cle-ccd66038-32.png", LOGO_CLE_CCD66038_32 = "file")
load("images/logos/col-516b86e3-16.png", LOGO_COL_516B86E3_16 = "file")
load("images/logos/col-516b86e3-30.png", LOGO_COL_516B86E3_30 = "file")
load("images/logos/col-516b86e3-32.png", LOGO_COL_516B86E3_32 = "file")
load("images/logos/det-742b0516-18.png", LOGO_DET_742B0516_18 = "file")
load("images/logos/det-742b0516-30.png", LOGO_DET_742B0516_30 = "file")
load("images/logos/det-742b0516-32.png", LOGO_DET_742B0516_32 = "file")
load("images/logos/hou-0db78273-18.png", LOGO_HOU_0DB78273_18 = "file")
load("images/logos/hou-0db78273-30.png", LOGO_HOU_0DB78273_30 = "file")
load("images/logos/hou-0db78273-32.png", LOGO_HOU_0DB78273_32 = "file")
load("images/logos/kc-1b0ad778-16.png", LOGO_KC_1B0AD778_16 = "file")
load("images/logos/kc-1b0ad778-30.png", LOGO_KC_1B0AD778_30 = "file")
load("images/logos/kc-1b0ad778-32.png", LOGO_KC_1B0AD778_32 = "file")
load("images/logos/laa-fd3c664a-22.png", LOGO_LAA_FD3C664A_22 = "file")
load("images/logos/laa-fd3c664a-30.png", LOGO_LAA_FD3C664A_30 = "file")
load("images/logos/laa-fd3c664a-32.png", LOGO_LAA_FD3C664A_32 = "file")
load("images/logos/lad-4e8070d4-18.png", LOGO_LAD_4E8070D4_18 = "file")
load("images/logos/lad-4e8070d4-30.png", LOGO_LAD_4E8070D4_30 = "file")
load("images/logos/lad-4e8070d4-32.png", LOGO_LAD_4E8070D4_32 = "file")
load("images/logos/mia-e2dbcfbb-18.png", LOGO_MIA_E2DBCFBB_18 = "file")
load("images/logos/mia-e2dbcfbb-30.png", LOGO_MIA_E2DBCFBB_30 = "file")
load("images/logos/mia-e2dbcfbb-32.png", LOGO_MIA_E2DBCFBB_32 = "file")
load("images/logos/mil-bf8635ec-16.png", LOGO_MIL_BF8635EC_16 = "file")
load("images/logos/mil-bf8635ec-30.png", LOGO_MIL_BF8635EC_30 = "file")
load("images/logos/mil-bf8635ec-32.png", LOGO_MIL_BF8635EC_32 = "file")
load("images/logos/min-9adb31fa-16.png", LOGO_MIN_9ADB31FA_16 = "file")
load("images/logos/min-9adb31fa-30.png", LOGO_MIN_9ADB31FA_30 = "file")
load("images/logos/min-9adb31fa-32.png", LOGO_MIN_9ADB31FA_32 = "file")
load("images/logos/nym-9988dfd6-18.png", LOGO_NYM_9988DFD6_18 = "file")
load("images/logos/nym-9988dfd6-30.png", LOGO_NYM_9988DFD6_30 = "file")
load("images/logos/nym-9988dfd6-32.png", LOGO_NYM_9988DFD6_32 = "file")
load("images/logos/nyy-259da3c2-16.png", LOGO_NYY_259DA3C2_16 = "file")
load("images/logos/nyy-259da3c2-30.png", LOGO_NYY_259DA3C2_30 = "file")
load("images/logos/nyy-259da3c2-32.png", LOGO_NYY_259DA3C2_32 = "file")
load("images/logos/phi-ba36ad1e-16.png", LOGO_PHI_BA36AD1E_16 = "file")
load("images/logos/phi-ba36ad1e-30.png", LOGO_PHI_BA36AD1E_30 = "file")
load("images/logos/phi-ba36ad1e-32.png", LOGO_PHI_BA36AD1E_32 = "file")
load("images/logos/pit-b7bceca4-16.png", LOGO_PIT_B7BCECA4_16 = "file")
load("images/logos/pit-b7bceca4-30.png", LOGO_PIT_B7BCECA4_30 = "file")
load("images/logos/pit-b7bceca4-32.png", LOGO_PIT_B7BCECA4_32 = "file")
load("images/logos/sd-c64e8816-16.png", LOGO_SD_C64E8816_16 = "file")
load("images/logos/sd-c64e8816-30.png", LOGO_SD_C64E8816_30 = "file")
load("images/logos/sd-c64e8816-32.png", LOGO_SD_C64E8816_32 = "file")
load("images/logos/sea-ded8a131-18.png", LOGO_SEA_DED8A131_18 = "file")
load("images/logos/sea-ded8a131-30.png", LOGO_SEA_DED8A131_30 = "file")
load("images/logos/sea-ded8a131-32.png", LOGO_SEA_DED8A131_32 = "file")
load("images/logos/sf-3d319469-18.png", LOGO_SF_3D319469_18 = "file")
load("images/logos/sf-3d319469-30.png", LOGO_SF_3D319469_30 = "file")
load("images/logos/sf-3d319469-32.png", LOGO_SF_3D319469_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/shared-be6d5aac-source.png", LOGO_SHARED_BE6D5AAC_SOURCE = "file")
load("images/logos/stl-b606dffd-16.png", LOGO_STL_B606DFFD_16 = "file")
load("images/logos/stl-b606dffd-30.png", LOGO_STL_B606DFFD_30 = "file")
load("images/logos/stl-b606dffd-32.png", LOGO_STL_B606DFFD_32 = "file")
load("images/logos/tb-6ebf08a9-16.png", LOGO_TB_6EBF08A9_16 = "file")
load("images/logos/tb-6ebf08a9-30.png", LOGO_TB_6EBF08A9_30 = "file")
load("images/logos/tb-6ebf08a9-32.png", LOGO_TB_6EBF08A9_32 = "file")
load("images/logos/tex-48b3ffac-16.png", LOGO_TEX_48B3FFAC_16 = "file")
load("images/logos/tex-48b3ffac-30.png", LOGO_TEX_48B3FFAC_30 = "file")
load("images/logos/tex-48b3ffac-32.png", LOGO_TEX_48B3FFAC_32 = "file")
load("images/logos/tor-b8d796a5-18.png", LOGO_TOR_B8D796A5_18 = "file")
load("images/logos/tor-b8d796a5-30.png", LOGO_TOR_B8D796A5_30 = "file")
load("images/logos/tor-b8d796a5-32.png", LOGO_TOR_B8D796A5_32 = "file")
load("images/logos/wsh-243a6939-16.png", LOGO_WSH_243A6939_16 = "file")
load("images/logos/wsh-243a6939-30.png", LOGO_WSH_243A6939_30 = "file")
load("images/logos/wsh-243a6939-32.png", LOGO_WSH_243A6939_32 = "file")

BUNDLED_LOGOS = {
    # ARI; source sha256 a8cea1cfdca6f698f89c7da3760dc197b781eae67599212b4f4ae3e451bcabf7
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/ari.png&h=50&w=50": {
        18: LOGO_ARI_0BB25CAC_18,
        30: LOGO_ARI_0BB25CAC_30,
        32: LOGO_ARI_0BB25CAC_32,
    },
    # ATH; source sha256 29d5ec07d0321c3819309beda98fc7980c7251218c99df1255c3199ffabf51aa
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/ath.png&h=50&w=50": {
        16: LOGO_ATH_0FB3D2C2_16,
        30: LOGO_ATH_0FB3D2C2_30,
        32: LOGO_ATH_0FB3D2C2_32,
    },
    # ATL; source sha256 9376b59a11265f1260412736beb8bcba59164a71ce37141b199537d15451e869
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/atl.png&h=50&w=50": {
        18: LOGO_ATL_CA11F462_18,
        30: LOGO_ATL_CA11F462_30,
        32: LOGO_ATL_CA11F462_32,
    },
    # BAL; source sha256 43a311e36812005501499e7b3c4716befcaa8e66ae37784417c8ed2e916c2f61
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/bal.png&h=50&w=50": {
        16: LOGO_BAL_EA036E7C_16,
        30: LOGO_BAL_EA036E7C_30,
        32: LOGO_BAL_EA036E7C_32,
    },
    # BOS; source sha256 5658216589c81fff3a1e05eadaa4876f2f07a7264a438fb735337a5aeff35e1c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/bos.png&h=50&w=50": {
        16: LOGO_BOS_B6C728CF_16,
        30: LOGO_BOS_B6C728CF_30,
        32: LOGO_BOS_B6C728CF_32,
    },
    # CHC; source sha256 df9605877616a04338d605481b912c69c2d8a5b6c0bd92ffc76f81076e43f6a4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/chc.png&h=50&w=50": {
        16: LOGO_CHC_4C4DB8D0_16,
        30: LOGO_CHC_4C4DB8D0_30,
        32: LOGO_CHC_4C4DB8D0_32,
    },
    # CHW; source sha256 f5f9711c9c788cc6e3f0ca6d66c0c56bb54452a7265a24a40cfcff7455e3cd9e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/chw.png&h=50&w=50": {
        22: LOGO_CHW_D6ADCA4D_22,
        30: LOGO_CHW_D6ADCA4D_30,
        32: LOGO_CHW_D6ADCA4D_32,
    },
    # CLE; source sha256 a26317fc524669fea9849705f01f4ace7a7dcb42199efee52cccdc0bf5ceb73c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/cle.png&h=50&w=50": {
        16: LOGO_CLE_CCD66038_16,
        30: LOGO_CLE_CCD66038_30,
        32: LOGO_CLE_CCD66038_32,
    },
    # COL; source sha256 48195a6f4787bb6b46c44fdc1ee62512ef4a87d1163e244eecdf52d06d52049e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/col.png&h=50&w=50": {
        16: LOGO_COL_516B86E3_16,
        30: LOGO_COL_516B86E3_30,
        32: LOGO_COL_516B86E3_32,
    },
    # DET; source sha256 adfb32e8948e5303888d3b880d6402f25dacf1001718ef6ebbb5ab757b667237
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/det.png&h=50&w=50": {
        18: LOGO_DET_742B0516_18,
        30: LOGO_DET_742B0516_30,
        32: LOGO_DET_742B0516_32,
    },
    # HOU; source sha256 7695a7c9b03f8d2925abed6805b19e802113280e10bd6dfb6021972a25e4120d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/hou.png&h=50&w=50": {
        18: LOGO_HOU_0DB78273_18,
        30: LOGO_HOU_0DB78273_30,
        32: LOGO_HOU_0DB78273_32,
    },
    # KC; source sha256 b9368c2b039bed489eebc750a5fa199449ad3bfe75264d32721bbce93d5ab778
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/kc.png&h=50&w=50": {
        16: LOGO_KC_1B0AD778_16,
        30: LOGO_KC_1B0AD778_30,
        32: LOGO_KC_1B0AD778_32,
    },
    # LAA; source sha256 42df7c9811518fa5e0a0db838122a175c5cba0e1627668434fd616fe61fd0be4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/laa.png&h=50&w=50": {
        22: LOGO_LAA_FD3C664A_22,
        30: LOGO_LAA_FD3C664A_30,
        32: LOGO_LAA_FD3C664A_32,
    },
    # LAD; source sha256 4ab71eaf313c89371c50011b965fea7e33487488cde718b01c093ead01b5ddea
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/lad.png&h=50&w=50": {
        18: LOGO_LAD_4E8070D4_18,
        30: LOGO_LAD_4E8070D4_30,
        32: LOGO_LAD_4E8070D4_32,
    },
    # MIA; source sha256 ddf908757c1a67f694355c15f5678ad57c011cd22406b6241f62ad6383105c7f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/mia.png&h=50&w=50": {
        18: LOGO_MIA_E2DBCFBB_18,
        30: LOGO_MIA_E2DBCFBB_30,
        32: LOGO_MIA_E2DBCFBB_32,
    },
    # MIL; source sha256 87d191b303951eaf4d003f865a76f55815dbfdc614e7c280708984a588d25913
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/mil.png&h=50&w=50": {
        16: LOGO_MIL_BF8635EC_16,
        30: LOGO_MIL_BF8635EC_30,
        32: LOGO_MIL_BF8635EC_32,
    },
    # MIN; source sha256 3519c430e2bd8502675f1b5b06bf44cc21bab77daaa11b24e5eeb72ddbe19e14
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/min.png&h=50&w=50": {
        16: LOGO_MIN_9ADB31FA_16,
        30: LOGO_MIN_9ADB31FA_30,
        32: LOGO_MIN_9ADB31FA_32,
    },
    # NYY; source sha256 3ff71b76e167084f23bd3bb63050347573f78f8b108e268866b85eabf6425c7c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/nyy.png&h=50&w=50": {
        16: LOGO_NYY_259DA3C2_16,
        30: LOGO_NYY_259DA3C2_30,
        32: LOGO_NYY_259DA3C2_32,
    },
    # PHI; source sha256 8540927c05d673e38e0be76a016ce0def7226fb04caa791404ac5fe1404abbce
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/phi.png&h=50&w=50": {
        16: LOGO_PHI_BA36AD1E_16,
        30: LOGO_PHI_BA36AD1E_30,
        32: LOGO_PHI_BA36AD1E_32,
    },
    # PIT; source sha256 f5b4fab6d0f9b92f1755816f5395e297c345a1b26671ae33a4f8ce4556307ef7
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/pit.png&h=50&w=50": {
        16: LOGO_PIT_B7BCECA4_16,
        30: LOGO_PIT_B7BCECA4_30,
        32: LOGO_PIT_B7BCECA4_32,
    },
    # SD; source sha256 beca13327ac8938e50a1c04dbaa519a304380baa513550d135a40dc34346ad3f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sd.png&h=50&w=50": {
        16: LOGO_SD_C64E8816_16,
        30: LOGO_SD_C64E8816_30,
        32: LOGO_SD_C64E8816_32,
    },
    # SEA; source sha256 0d93fb9e10a989fa2484850f5510733c07b031e72def35b74a506afca87db166
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sea.png&h=50&w=50": {
        18: LOGO_SEA_DED8A131_18,
        30: LOGO_SEA_DED8A131_30,
        32: LOGO_SEA_DED8A131_32,
    },
    # SF; source sha256 499a83ed5c385d76dc299eb0f73fd01e5b625180e0be34158c533a0183a7e356
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sf.png&h=50&w=50": {
        18: LOGO_SF_3D319469_18,
        30: LOGO_SF_3D319469_30,
        32: LOGO_SF_3D319469_32,
    },
    # TB; source sha256 9cc570862c0ad913d543c54f13aab64d83a3fdc7527557dcb7e1f7358850b2f4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tb.png&h=50&w=50": {
        16: LOGO_TB_6EBF08A9_16,
        30: LOGO_TB_6EBF08A9_30,
        32: LOGO_TB_6EBF08A9_32,
    },
    # TEX; source sha256 35de8568a6dbd9f0b947da09190a38a10b865c502cb6008c3e4e2ff28491c500
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tex.png&h=50&w=50": {
        16: LOGO_TEX_48B3FFAC_16,
        30: LOGO_TEX_48B3FFAC_30,
        32: LOGO_TEX_48B3FFAC_32,
    },
    # TOR; source sha256 6a59c88b90fcaef87d41f77851b153bce2575c5ec82b7f8b103ed4788380e48c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tor.png&h=50&w=50": {
        18: LOGO_TOR_B8D796A5_18,
        30: LOGO_TOR_B8D796A5_30,
        32: LOGO_TOR_B8D796A5_32,
    },
    # WSH; source sha256 a5b336ecd6329711db14f83d116f7a139edff20e06bd78beefc3ecec32e765af
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/wsh.png&h=50&w=50": {
        16: LOGO_WSH_243A6939_16,
        30: LOGO_WSH_243A6939_30,
        32: LOGO_WSH_243A6939_32,
    },
    # STL; source sha256 7c296c57ba263c01179f2236733182cb59a1106f0945c44d0adf662093fd8db0
    "https://b.fssta.com/uploads/application/mlb/team-logos/Cardinals-alternate.png": {
        16: LOGO_STL_B606DFFD_16,
        30: LOGO_STL_B606DFFD_30,
        32: LOGO_STL_B606DFFD_32,
    },
    # NYM; source sha256 df5a1a376e05e7ccfb15103e05c1954409d88e9fadeaf2f857b79f3e3d44166d
    "https://b.fssta.com/uploads/application/mlb/team-logos/Mets.png": {
        18: LOGO_NYM_9988DFD6_18,
        30: LOGO_NYM_9988DFD6_30,
        32: LOGO_NYM_9988DFD6_32,
    },
    # CIN; source sha256 4801b18fdc3b49931626e280852b9edec6cb8ba6338dd085977e21841b15d74e
    "https://b.fssta.com/uploads/application/mlb/team-logos/Reds-alternate.png": {
        16: LOGO_CIN_33593CC6_16,
        30: LOGO_CIN_33593CC6_30,
        32: LOGO_CIN_33593CC6_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        16: LOGO_SHARED_BE6D5AAC_SOURCE,
        18: LOGO_SHARED_BE6D5AAC_SOURCE,
        22: LOGO_SHARED_BE6D5AAC_SOURCE,
        30: LOGO_SHARED_BE6D5AAC_SOURCE,
        32: LOGO_SHARED_BE6D5AAC_SOURCE,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        18: LOGO_SHARED_3FDF1951_SOURCE,
        22: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
