"""
Bundled team logos for xflscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/arl-72f06e0c-16.png", LOGO_ARL_72F06E0C_16 = "file")
load("images/logos/arl-72f06e0c-30.png", LOGO_ARL_72F06E0C_30 = "file")
load("images/logos/arl-72f06e0c-32.png", LOGO_ARL_72F06E0C_32 = "file")
load("images/logos/dc-b55a918b-16.png", LOGO_DC_B55A918B_16 = "file")
load("images/logos/dc-b55a918b-30.png", LOGO_DC_B55A918B_30 = "file")
load("images/logos/dc-b55a918b-32.png", LOGO_DC_B55A918B_32 = "file")
load("images/logos/hou-754bd9d4-16.png", LOGO_HOU_754BD9D4_16 = "file")
load("images/logos/hou-754bd9d4-30.png", LOGO_HOU_754BD9D4_30 = "file")
load("images/logos/hou-754bd9d4-32.png", LOGO_HOU_754BD9D4_32 = "file")
load("images/logos/orl-eaf7ce2d-16.png", LOGO_ORL_EAF7CE2D_16 = "file")
load("images/logos/orl-eaf7ce2d-30.png", LOGO_ORL_EAF7CE2D_30 = "file")
load("images/logos/orl-eaf7ce2d-32.png", LOGO_ORL_EAF7CE2D_32 = "file")
load("images/logos/sa-be6d5aac-source.png", LOGO_SA_BE6D5AAC_SOURCE = "file")
load("images/logos/sea-c9581dfd-16.png", LOGO_SEA_C9581DFD_16 = "file")
load("images/logos/sea-c9581dfd-30.png", LOGO_SEA_C9581DFD_30 = "file")
load("images/logos/sea-c9581dfd-32.png", LOGO_SEA_C9581DFD_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/stl-80abf1ab-16.png", LOGO_STL_80ABF1AB_16 = "file")
load("images/logos/stl-80abf1ab-30.png", LOGO_STL_80ABF1AB_30 = "file")
load("images/logos/stl-80abf1ab-32.png", LOGO_STL_80ABF1AB_32 = "file")
load("images/logos/vgs-09200dee-16.png", LOGO_VGS_09200DEE_16 = "file")
load("images/logos/vgs-09200dee-30.png", LOGO_VGS_09200DEE_30 = "file")
load("images/logos/vgs-09200dee-32.png", LOGO_VGS_09200DEE_32 = "file")

BUNDLED_LOGOS = {
    # DC; source sha256 5e89aad2cef3929fd9d1e6d7fb19e20128e8dd1c760040cb19658b2108f5aeb4
    "https://a.espncdn.com/combiner/i?img=guid/48f48fbd-8277-3d4f-898a-34d05d873124/logos/default.png&h=50&w=50": {
        16: LOGO_DC_B55A918B_16,
        30: LOGO_DC_B55A918B_30,
        32: LOGO_DC_B55A918B_32,
    },
    # ARL; source sha256 7a4f8372b10901f0731896fc63b5ae673bd484556d204428b8c104a58d117c69
    "https://a.espncdn.com/combiner/i?img=guid/75b95e05-b1d5-35ab-a06f-abb3901a77dc/logos/default.png&h=50&w=50": {
        16: LOGO_ARL_72F06E0C_16,
        30: LOGO_ARL_72F06E0C_30,
        32: LOGO_ARL_72F06E0C_32,
    },
    # STL; source sha256 519d0c6def95b1e39c58ee8d09db576837685092cc80b1253d9719a28ec7f0c3
    "https://a.espncdn.com/combiner/i?img=guid/e23de40c-98de-336d-aaa0-732532465fab/logos/default.png&h=50&w=50": {
        16: LOGO_STL_80ABF1AB_16,
        30: LOGO_STL_80ABF1AB_30,
        32: LOGO_STL_80ABF1AB_32,
    },
    # HOU; source sha256 83369765c46e73d258570ade24e44c8e6ed834fdd50db60e381c843bd1ca6410
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/xfl/500/hou.png&h=50&w=50": {
        16: LOGO_HOU_754BD9D4_16,
        30: LOGO_HOU_754BD9D4_30,
        32: LOGO_HOU_754BD9D4_32,
    },
    # ORL; source sha256 bb87ac2ca3a68002e45631e61f25f59c7a5ec626f06a150c9726a7940f83da7a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/xfl/500/orl.png&h=50&w=50": {
        16: LOGO_ORL_EAF7CE2D_16,
        30: LOGO_ORL_EAF7CE2D_30,
        32: LOGO_ORL_EAF7CE2D_32,
    },
    # SEA; source sha256 424908acf3b6abcf03fb93cc4dc7d77170f1989ab8eb04c8fd01b55ed2aedf2a
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/xfl/500/sea.png&h=50&w=50": {
        16: LOGO_SEA_C9581DFD_16,
        30: LOGO_SEA_C9581DFD_30,
        32: LOGO_SEA_C9581DFD_32,
    },
    # VGS; source sha256 71d87f8a6c089680bef09259a29a6e8ce88588d6c26e6aad710f0475b686efc1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/xfl/500/vgs.png&h=50&w=50": {
        16: LOGO_VGS_09200DEE_16,
        30: LOGO_VGS_09200DEE_30,
        32: LOGO_VGS_09200DEE_32,
    },
    # SA; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png": {
        16: LOGO_SA_BE6D5AAC_SOURCE,
        20: LOGO_SA_BE6D5AAC_SOURCE,
        30: LOGO_SA_BE6D5AAC_SOURCE,
        32: LOGO_SA_BE6D5AAC_SOURCE,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        20: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
