"""
Applet: German WOTD
Summary: German word of the day
Description: Pick a random german word for each day and display definition in English.
Author: pej289
"""

load("hash.star", "hash")
load("math.star", "math")
load("render.star", "render")
load("time.star", "time")

# regex to convert tsv to array
# ^([^\t]*)\t(.*$)
# ["$1","$2"],

word_array = [
    ["hallo", "hello"],
    ["tschüss", "bye"],
    ["auf Wiedersehen", "goodbye"],
    ["guten Morgen", "good morning"],
    ["guten Tag", "good day"],
    ["guten Abend", "good evening"],
    ["gute Nacht", "good night"],
    ["bitte", "please"],
    ["danke", "thank you"],
    ["danke schön", "thank you very much"],
    ["bitte schön", "you're welcome"],
    ["entschuldigung", "excuse me / sorry"],
    ["es tut mir leid", "I'm sorry"],
    ["ja", "yes"],
    ["nein", "no"],
    ["vielleicht", "maybe"],
    ["wie geht's", "how's it going"],
    ["mir geht es gut", "I'm doing well"],
    ["freut mich", "nice to meet you"],
    ["willkommen", "welcome"],
    ["prost", "cheers"],
    ["viel Glück", "good luck"],
    ["alles Gute", "all the best"],
    ["herzlichen Glückwunsch", "congratulations"],
    ["natürlich", "of course"],
    ["kein Problem", "no problem"],
    ["macht nichts", "never mind"],
    ["gerne", "gladly"],
    ["genau", "exactly"],
    ["stimmt", "that's right"],
    ["null", "zero"],
    ["eins", "one"],
    ["zwei", "two"],
    ["drei", "three"],
    ["vier", "four"],
    ["fünf", "five"],
    ["sechs", "six"],
    ["sieben", "seven"],
    ["acht", "eight"],
    ["neun", "nine"],
    ["zehn", "ten"],
    ["elf", "eleven"],
    ["zwölf", "twelve"],
    ["dreizehn", "thirteen"],
    ["vierzehn", "fourteen"],
    ["fünfzehn", "fifteen"],
    ["sechzehn", "sixteen"],
    ["siebzehn", "seventeen"],
    ["achtzehn", "eighteen"],
    ["neunzehn", "nineteen"],
    ["zwanzig", "twenty"],
    ["dreißig", "thirty"],
    ["vierzig", "forty"],
    ["fünfzig", "fifty"],
    ["sechzig", "sixty"],
    ["siebzig", "seventy"],
    ["achtzig", "eighty"],
    ["neunzig", "ninety"],
    ["hundert", "a hundred"],
    ["tausend", "a thousand"],
    ["eine Million", "a million"],
    ["erste", "first"],
    ["zweite", "second"],
    ["dritte", "third"],
    ["letzte", "last"],
    ["nächste", "next"],
    ["die Hälfte", "half"],
    ["das Viertel", "quarter"],
    ["das Dutzend", "dozen"],
    ["die Zahl", "number"],
    ["die Menge", "amount"],
    ["rot", "red"],
    ["blau", "blue"],
    ["gelb", "yellow"],
    ["grün", "green"],
    ["schwarz", "black"],
    ["weiß", "white"],
    ["orange", "orange"],
    ["lila", "purple"],
    ["rosa", "pink"],
    ["braun", "brown"],
    ["grau", "gray"],
    ["golden", "golden"],
    ["silbern", "silver"],
    ["bunt", "colorful"],
    ["hell", "light (color)"],
    ["die Familie", "family"],
    ["die Mutter", "mother"],
    ["der Vater", "father"],
    ["die Eltern", "parents"],
    ["der Sohn", "son"],
    ["die Tochter", "daughter"],
    ["der Bruder", "brother"],
    ["die Schwester", "sister"],
    ["die Geschwister", "siblings"],
    ["die Großmutter", "grandmother"],
    ["der Großvater", "grandfather"],
    ["die Großeltern", "grandparents"],
    ["die Tante", "aunt"],
    ["der Onkel", "uncle"],
    ["der Cousin", "male cousin"],
    ["die Cousine", "female cousin"],
    ["der Ehemann", "husband"],
    ["die Ehefrau", "wife"],
    ["der Freund", "friend / boyfriend"],
    ["die Freundin", "friend / girlfriend"],
    ["das Baby", "baby"],
    ["das Kind", "child"],
    ["die Kinder", "children"],
    ["der Enkel", "grandson"],
    ["die Enkelin", "granddaughter"],
    ["der Montag", "Monday"],
    ["der Dienstag", "Tuesday"],
    ["der Mittwoch", "Wednesday"],
    ["der Donnerstag", "Thursday"],
    ["der Freitag", "Friday"],
    ["der Samstag", "Saturday"],
    ["der Sonntag", "Sunday"],
    ["der Januar", "January"],
    ["der Februar", "February"],
    ["der März", "March"],
    ["der April", "April"],
    ["der Mai", "May"],
    ["der Juni", "June"],
    ["der Juli", "July"],
    ["der August", "August"],
    ["der September", "September"],
    ["der Oktober", "October"],
    ["der November", "November"],
    ["der Dezember", "December"],
    ["heute", "today"],
    ["morgen", "tomorrow"],
    ["gestern", "yesterday"],
    ["die Woche", "week"],
    ["der Monat", "month"],
    ["das Jahr", "year"],
    ["die Stunde", "hour"],
    ["die Minute", "minute"],
    ["die Sekunde", "second (time)"],
    ["der Tag", "day"],
    ["die Nacht", "night"],
    ["das Wetter", "weather"],
    ["die Sonne", "sun"],
    ["der Regen", "rain"],
    ["der Schnee", "snow"],
    ["der Wind", "wind"],
    ["die Wolke", "cloud"],
    ["das Gewitter", "thunderstorm"],
    ["der Nebel", "fog"],
    ["heiß", "hot"],
    ["kalt", "cold"],
    ["warm", "warm"],
    ["kühl", "cool"],
    ["sonnig", "sunny"],
    ["regnerisch", "rainy"],
    ["windig", "windy"],
    ["die Temperatur", "temperature"],
    ["der Himmel", "sky"],
    ["das Eis", "ice"],
    ["der Blitz", "lightning"],
    ["der Donner", "thunder"],
    ["der Kopf", "head"],
    ["das Haar", "hair"],
    ["das Gesicht", "face"],
    ["das Auge", "eye"],
    ["die Nase", "nose"],
    ["der Mund", "mouth"],
    ["das Ohr", "ear"],
    ["der Hals", "neck"],
    ["die Schulter", "shoulder"],
    ["der Arm", "arm"],
    ["die Hand", "hand"],
    ["der Finger", "finger"],
    ["der Bauch", "belly"],
    ["der Rücken", "back"],
    ["das Bein", "leg"],
    ["das Knie", "knee"],
    ["der Fuß", "foot"],
    ["der Zeh", "toe"],
    ["das Herz", "heart"],
    ["die Haut", "skin"],
    ["der Zahn", "tooth"],
    ["die Zunge", "tongue"],
    ["die Lippe", "lip"],
    ["das Kinn", "chin"],
    ["die Stirn", "forehead"],
    ["die Wange", "cheek"],
    ["der Nagel", "nail"],
    ["der Ellbogen", "elbow"],
    ["der Knöchel", "ankle"],
    ["die Brust", "chest"],
    ["das Essen", "food"],
    ["das Brot", "bread"],
    ["die Butter", "butter"],
    ["der Käse", "cheese"],
    ["die Milch", "milk"],
    ["das Ei", "egg"],
    ["das Fleisch", "meat"],
    ["das Hähnchen", "chicken"],
    ["der Fisch", "fish"],
    ["das Gemüse", "vegetable"],
    ["das Obst", "fruit"],
    ["der Apfel", "apple"],
    ["die Banane", "banana"],
    ["die Orange", "orange (fruit)"],
    ["die Traube", "grape"],
    ["die Erdbeere", "strawberry"],
    ["die Zitrone", "lemon"],
    ["die Kartoffel", "potato"],
    ["die Tomate", "tomato"],
    ["die Zwiebel", "onion"],
    ["die Karotte", "carrot"],
    ["der Salat", "salad / lettuce"],
    ["der Reis", "rice"],
    ["die Nudel", "noodle / pasta"],
    ["die Suppe", "soup"],
    ["der Zucker", "sugar"],
    ["das Salz", "salt"],
    ["der Pfeffer", "pepper"],
    ["das Öl", "oil"],
    ["der Kuchen", "cake"],
    ["die Schokolade", "chocolate"],
    ["der Honig", "honey"],
    ["die Marmelade", "jam"],
    ["das Wasser", "water"],
    ["der Kaffee", "coffee"],
    ["der Tee", "tea"],
    ["der Saft", "juice"],
    ["der Wein", "wine"],
    ["das Bier", "beer"],
    ["das Frühstück", "breakfast"],
    ["das Mittagessen", "lunch"],
    ["das Abendessen", "dinner"],
    ["der Hunger", "hunger"],
    ["der Durst", "thirst"],
    ["das Restaurant", "restaurant"],
    ["die Küche", "kitchen"],
    ["das Rezept", "recipe"],
    ["kochen", "to cook"],
    ["essen", "to eat"],
    ["trinken", "to drink"],
    ["die Gabel", "fork"],
    ["das Messer", "knife"],
    ["der Löffel", "spoon"],
    ["der Teller", "plate"],
    ["die Tasse", "cup"],
    ["das Glas", "glass"],
    ["die Schüssel", "bowl"],
    ["die Serviette", "napkin"],
    ["das Mehl", "flour"],
    ["der Teig", "dough"],
    ["backen", "to bake"],
    ["braten", "to fry / roast"],
    ["schneiden", "to cut"],
    ["die Wurst", "sausage"],
    ["der Schinken", "ham"],
    ["das Sandwich", "sandwich"],
    ["die Pizza", "pizza"],
    ["das Getränk", "beverage"],
    ["süß", "sweet"],
    ["sauer", "sour"],
    ["bitter", "bitter"],
    ["scharf", "spicy"],
    ["lecker", "tasty"],
    ["satt", "full (not hungry)"],
    ["der Pilz", "mushroom"],
    ["die Gurke", "cucumber"],
    ["der Pfirsich", "peach"],
    ["die Kirsche", "cherry"],
    ["die Ananas", "pineapple"],
    ["die Nuss", "nut"],
    ["die Bohne", "bean"],
    ["der Kohl", "cabbage"],
    ["das Tier", "animal"],
    ["der Hund", "dog"],
    ["die Katze", "cat"],
    ["der Vogel", "bird"],
    ["die Maus", "mouse"],
    ["das Pferd", "horse"],
    ["die Kuh", "cow"],
    ["das Schwein", "pig"],
    ["das Schaf", "sheep"],
    ["die Ziege", "goat"],
    ["das Huhn", "chicken (animal)"],
    ["die Ente", "duck"],
    ["die Gans", "goose"],
    ["die Schildkröte", "turtle"],
    ["der Frosch", "frog"],
    ["die Schlange", "snake"],
    ["die Spinne", "spider"],
    ["die Biene", "bee"],
    ["der Schmetterling", "butterfly"],
    ["die Fliege", "fly"],
    ["die Ameise", "ant"],
    ["der Löwe", "lion"],
    ["der Tiger", "tiger"],
    ["der Bär", "bear"],
    ["der Elefant", "elephant"],
    ["die Giraffe", "giraffe"],
    ["der Affe", "monkey"],
    ["der Wolf", "wolf"],
    ["der Fuchs", "fox"],
    ["das Reh", "deer"],
    ["das Kaninchen", "rabbit"],
    ["die Eule", "owl"],
    ["der Adler", "eagle"],
    ["der Hai", "shark"],
    ["der Wal", "whale"],
    ["der Delfin", "dolphin"],
    ["die Krabbe", "crab"],
    ["die Muschel", "shell / mussel"],
    ["der Käfer", "beetle"],
    ["die Mücke", "mosquito"],
    ["die Kröte", "toad"],
    ["das Eichhörnchen", "squirrel"],
    ["der Igel", "hedgehog"],
    ["die Fledermaus", "bat"],
    ["der Papagei", "parrot"],
    ["der Pinguin", "penguin"],
    ["das Kamel", "camel"],
    ["das Krokodil", "crocodile"],
    ["die Eidechse", "lizard"],
    ["das Haus", "house"],
    ["die Wohnung", "apartment"],
    ["das Zimmer", "room"],
    ["das Schlafzimmer", "bedroom"],
    ["das Wohnzimmer", "living room"],
    ["das Badezimmer", "bathroom"],
    ["die Tür", "door"],
    ["das Fenster", "window"],
    ["die Wand", "wall"],
    ["der Boden", "floor"],
    ["das Dach", "roof"],
    ["der Tisch", "table"],
    ["der Stuhl", "chair"],
    ["das Bett", "bed"],
    ["das Sofa", "sofa"],
    ["der Schrank", "cupboard / closet"],
    ["das Regal", "shelf"],
    ["die Lampe", "lamp"],
    ["der Spiegel", "mirror"],
    ["der Teppich", "carpet"],
    ["die Uhr", "clock"],
    ["das Bild", "picture"],
    ["das Kissen", "pillow"],
    ["die Decke", "blanket / ceiling"],
    ["der Schlüssel", "key"],
    ["die Treppe", "stairs"],
    ["der Keller", "basement"],
    ["der Garten", "garden"],
    ["der Balkon", "balcony"],
    ["die Dusche", "shower"],
    ["die Badewanne", "bathtub"],
    ["die Toilette", "toilet"],
    ["das Waschbecken", "sink"],
    ["der Herd", "stove"],
    ["der Kühlschrank", "refrigerator"],
    ["die Spülmaschine", "dishwasher"],
    ["die Waschmaschine", "washing machine"],
    ["der Fernseher", "television"],
    ["der Computer", "computer"],
    ["das Telefon", "telephone"],
    ["die Kerze", "candle"],
    ["der Besen", "broom"],
    ["der Müll", "trash"],
    ["die Seife", "soap"],
    ["das Handtuch", "towel"],
    ["die Bürste", "brush"],
    ["die Vase", "vase"],
    ["der Vorhang", "curtain"],
    ["die Steckdose", "electrical outlet"],
    ["der Schalter", "switch"],
    ["die Kleidung", "clothing"],
    ["das Hemd", "shirt"],
    ["die Hose", "pants"],
    ["das Kleid", "dress"],
    ["der Rock", "skirt"],
    ["die Jacke", "jacket"],
    ["der Mantel", "coat"],
    ["der Pullover", "sweater"],
    ["die Socke", "sock"],
    ["der Schuh", "shoe"],
    ["der Stiefel", "boot"],
    ["der Hut", "hat"],
    ["die Mütze", "cap / beanie"],
    ["der Schal", "scarf"],
    ["der Handschuh", "glove"],
    ["der Gürtel", "belt"],
    ["die Krawatte", "tie"],
    ["die Brille", "glasses"],
    ["die Tasche", "bag"],
    ["der Anzug", "suit"],
    ["das T-Shirt", "T-shirt"],
    ["die Jeans", "jeans"],
    ["der Schmuck", "jewelry"],
    ["der Ring", "ring"],
    ["die Kette", "necklace"],
    ["der Knopf", "button"],
    ["der Reißverschluss", "zipper"],
    ["die Größe", "size"],
    ["anziehen", "to put on / dress"],
    ["ausziehen", "to take off / undress"],
    ["der Beruf", "profession"],
    ["der Lehrer", "teacher (male)"],
    ["die Lehrerin", "teacher (female)"],
    ["der Arzt", "doctor (male)"],
    ["die Ärztin", "doctor (female)"],
    ["die Krankenschwester", "nurse"],
    ["der Polizist", "police officer"],
    ["der Feuerwehrmann", "firefighter"],
    ["der Koch", "cook / chef"],
    ["der Kellner", "waiter"],
    ["die Kellnerin", "waitress"],
    ["der Ingenieur", "engineer"],
    ["der Anwalt", "lawyer"],
    ["der Bauer", "farmer"],
    ["der Verkäufer", "salesperson"],
    ["der Fahrer", "driver"],
    ["der Künstler", "artist"],
    ["der Musiker", "musician"],
    ["der Schauspieler", "actor"],
    ["der Journalist", "journalist"],
    ["der Wissenschaftler", "scientist"],
    ["der Student", "student"],
    ["der Professor", "professor"],
    ["der Manager", "manager"],
    ["der Sekretär", "secretary"],
    ["der Zahnarzt", "dentist"],
    ["der Friseur", "hairdresser"],
    ["der Bäcker", "baker"],
    ["der Metzger", "butcher"],
    ["der Elektriker", "electrician"],
    ["die Stadt", "city"],
    ["das Dorf", "village"],
    ["das Land", "country"],
    ["die Straße", "street"],
    ["der Platz", "square / place"],
    ["die Schule", "school"],
    ["die Universität", "university"],
    ["das Krankenhaus", "hospital"],
    ["der Bahnhof", "train station"],
    ["der Flughafen", "airport"],
    ["das Geschäft", "shop"],
    ["der Markt", "market"],
    ["die Bibliothek", "library"],
    ["das Museum", "museum"],
    ["das Kino", "cinema"],
    ["das Theater", "theater"],
    ["die Kirche", "church"],
    ["das Rathaus", "town hall"],
    ["die Bank", "bank"],
    ["das Büro", "office"],
    ["der Park", "park"],
    ["der Wald", "forest"],
    ["der Berg", "mountain"],
    ["der Fluss", "river"],
    ["der See", "lake"],
    ["das Meer", "sea"],
    ["der Strand", "beach"],
    ["die Insel", "island"],
    ["die Brücke", "bridge"],
    ["der Hafen", "harbor"],
    ["die Fabrik", "factory"],
    ["das Hotel", "hotel"],
    ["die Post", "post office"],
    ["die Apotheke", "pharmacy"],
    ["der Supermarkt", "supermarket"],
    ["die Bäckerei", "bakery"],
    ["das Stadion", "stadium"],
    ["der Zoo", "zoo"],
    ["der Friedhof", "cemetery"],
    ["die Grenze", "border"],
    ["das Auto", "car"],
    ["der Bus", "bus"],
    ["der Zug", "train"],
    ["das Flugzeug", "airplane"],
    ["das Fahrrad", "bicycle"],
    ["das Motorrad", "motorcycle"],
    ["das Schiff", "ship"],
    ["das Boot", "boat"],
    ["das Taxi", "taxi"],
    ["die U-Bahn", "subway"],
    ["die Straßenbahn", "tram"],
    ["der LKW", "truck"],
    ["die Ampel", "traffic light"],
    ["die Kreuzung", "intersection"],
    ["der Parkplatz", "parking lot"],
    ["der Führerschein", "driver's license"],
    ["das Ticket", "ticket"],
    ["die Fahrkarte", "ticket (transport)"],
    ["fahren", "to drive / ride"],
    ["fliegen", "to fly"],
    ["gehen", "to walk / go"],
    ["laufen", "to run / walk"],
    ["ankommen", "to arrive"],
    ["abfahren", "to depart"],
    ["einsteigen", "to board / get in"],
    ["sein", "to be"],
    ["haben", "to have"],
    ["werden", "to become"],
    ["können", "to be able to / can"],
    ["müssen", "to have to / must"],
    ["wollen", "to want"],
    ["sollen", "should"],
    ["dürfen", "to be allowed to"],
    ["mögen", "to like"],
    ["machen", "to do / make"],
    ["kommen", "to come"],
    ["sehen", "to see"],
    ["hören", "to hear"],
    ["sprechen", "to speak"],
    ["sagen", "to say"],
    ["fragen", "to ask"],
    ["antworten", "to answer"],
    ["wissen", "to know (fact)"],
    ["kennen", "to know (person/place)"],
    ["denken", "to think"],
    ["glauben", "to believe"],
    ["verstehen", "to understand"],
    ["lernen", "to learn"],
    ["lesen", "to read"],
    ["schreiben", "to write"],
    ["arbeiten", "to work"],
    ["spielen", "to play"],
    ["kaufen", "to buy"],
    ["verkaufen", "to sell"],
    ["geben", "to give"],
    ["nehmen", "to take"],
    ["bringen", "to bring"],
    ["finden", "to find"],
    ["suchen", "to search"],
    ["helfen", "to help"],
    ["brauchen", "to need"],
    ["lieben", "to love"],
    ["hassen", "to hate"],
    ["leben", "to live"],
    ["wohnen", "to reside"],
    ["bleiben", "to stay"],
    ["warten", "to wait"],
    ["beginnen", "to begin"],
    ["enden", "to end"],
    ["öffnen", "to open"],
    ["schließen", "to close"],
    ["stehen", "to stand"],
    ["sitzen", "to sit"],
    ["liegen", "to lie down"],
    ["schlafen", "to sleep"],
    ["aufwachen", "to wake up"],
    ["aufstehen", "to get up"],
    ["duschen", "to shower"],
    ["waschen", "to wash"],
    ["putzen", "to clean"],
    ["singen", "to sing"],
    ["tanzen", "to dance"],
    ["lachen", "to laugh"],
    ["weinen", "to cry"],
    ["lächeln", "to smile"],
    ["rufen", "to call out"],
    ["telefonieren", "to phone"],
    ["schicken", "to send"],
    ["bekommen", "to receive"],
    ["zeigen", "to show"],
    ["erklären", "to explain"],
    ["vergessen", "to forget"],
    ["erinnern", "to remember"],
    ["planen", "to plan"],
    ["reisen", "to travel"],
    ["besuchen", "to visit"],
    ["treffen", "to meet"],
    ["kennenlernen", "to get to know"],
    ["heiraten", "to marry"],
    ["feiern", "to celebrate"],
    ["gewinnen", "to win"],
    ["verlieren", "to lose"],
    ["versuchen", "to try"],
    ["schaffen", "to manage / create"],
    ["ändern", "to change"],
    ["wechseln", "to switch / exchange"],
    ["bezahlen", "to pay"],
    ["kosten", "to cost"],
    ["sparen", "to save (money)"],
    ["ausgeben", "to spend (money)"],
    ["tragen", "to carry / wear"],
    ["fallen", "to fall"],
    ["springen", "to jump"],
    ["fangen", "to catch"],
    ["werfen", "to throw"],
    ["ziehen", "to pull"],
    ["drücken", "to push / press"],
    ["reparieren", "to repair"],
    ["bauen", "to build"],
    ["zerstören", "to destroy"],
    ["wachsen", "to grow"],
    ["sterben", "to die"],
    ["riechen", "to smell"],
    ["schmecken", "to taste"],
    ["fühlen", "to feel"],
    ["berühren", "to touch"],
    ["groß", "big"],
    ["klein", "small"],
    ["lang", "long"],
    ["kurz", "short"],
    ["hoch", "high / tall"],
    ["niedrig", "low"],
    ["breit", "wide"],
    ["schmal", "narrow"],
    ["dick", "thick / fat"],
    ["dünn", "thin"],
    ["schwer", "heavy / difficult"],
    ["leicht", "light / easy"],
    ["schnell", "fast"],
    ["langsam", "slow"],
    ["alt", "old"],
    ["neu", "new"],
    ["jung", "young"],
    ["gut", "good"],
    ["schlecht", "bad"],
    ["schön", "beautiful"],
    ["hässlich", "ugly"],
    ["glücklich", "happy"],
    ["traurig", "sad"],
    ["wütend", "angry"],
    ["müde", "tired"],
    ["hungrig", "hungry"],
    ["durstig", "thirsty"],
    ["krank", "sick"],
    ["gesund", "healthy"],
    ["stark", "strong"],
    ["schwach", "weak"],
    ["laut", "loud"],
    ["leise", "quiet"],
    ["sauber", "clean"],
    ["schmutzig", "dirty"],
    ["voll", "full"],
    ["leer", "empty"],
    ["offen", "open"],
    ["geschlossen", "closed"],
    ["richtig", "correct"],
    ["falsch", "wrong"],
    ["einfach", "simple"],
    ["schwierig", "difficult"],
    ["wichtig", "important"],
    ["interessant", "interesting"],
    ["langweilig", "boring"],
    ["freundlich", "friendly"],
    ["unfreundlich", "unfriendly"],
    ["nett", "nice"],
    ["höflich", "polite"],
    ["klug", "smart"],
    ["dumm", "stupid"],
    ["mutig", "brave"],
    ["ängstlich", "fearful"],
    ["ruhig", "calm"],
    ["nervös", "nervous"],
    ["reich", "rich"],
    ["arm", "poor"],
    ["teuer", "expensive"],
    ["billig", "cheap"],
    ["nah", "near"],
    ["fern", "far"],
    ["nass", "wet"],
    ["trocken", "dry"],
    ["hart", "hard"],
    ["weich", "soft"],
    ["stumpf", "dull"],
    ["dunkel", "dark"],
    ["frisch", "fresh"],
    ["fertig", "finished / ready"],
    ["bereit", "ready"],
    ["frei", "free"],
    ["besetzt", "occupied"],
    ["sicher", "safe / sure"],
    ["gefährlich", "dangerous"],
    ["ähnlich", "similar"],
    ["gleich", "same"],
    ["anders", "different"],
    ["besonders", "special"],
    ["das Buch", "book"],
    ["der Stift", "pen"],
    ["der Bleistift", "pencil"],
    ["das Papier", "paper"],
    ["das Heft", "notebook"],
    ["die Tafel", "blackboard"],
    ["der Rucksack", "backpack"],
    ["die Klasse", "class"],
    ["die Prüfung", "exam"],
    ["die Hausaufgabe", "homework"],
    ["der Unterricht", "lesson"],
    ["die Frage", "question"],
    ["die Antwort", "answer"],
    ["die Sprache", "language"],
    ["das Wort", "word"],
    ["der Satz", "sentence"],
    ["die Geschichte", "story / history"],
    ["die Mathematik", "mathematics"],
    ["die Wissenschaft", "science"],
    ["die Kunst", "art"],
    ["die Musik", "music"],
    ["der Sport", "sport"],
    ["das Spiel", "game"],
    ["der Ball", "ball"],
    ["das Spielzeug", "toy"],
    ["die Puppe", "doll"],
    ["der Baum", "tree"],
    ["die Blume", "flower"],
    ["das Gras", "grass"],
    ["das Blatt", "leaf"],
    ["die Wurzel", "root"],
    ["der Stein", "stone"],
    ["der Sand", "sand"],
    ["die Erde", "earth / soil"],
    ["die Luft", "air"],
    ["das Feuer", "fire"],
    ["der Rauch", "smoke"],
    ["der Mond", "moon"],
    ["der Stern", "star"],
    ["die Welt", "world"],
    ["das Universum", "universe"],
    ["die Natur", "nature"],
    ["das Tal", "valley"],
    ["die Wüste", "desert"],
    ["der Regenbogen", "rainbow"],
    ["die Jahreszeit", "season"],
    ["das Licht", "light"],
    ["der Schatten", "shadow"],
    ["die Farbe", "color"],
    ["die Form", "shape"],
    ["das Lied", "song"],
    ["der Tanz", "dance"],
    ["der Film", "film"],
    ["die Zeitung", "newspaper"],
    ["die Nachricht", "news / message"],
    ["der Brief", "letter"],
    ["das Geschenk", "gift"],
    ["die Party", "party"],
    ["der Geburtstag", "birthday"],
    ["die Reise", "trip"],
    ["der Urlaub", "vacation"],
    ["das Gepäck", "luggage"],
    ["der Koffer", "suitcase"],
    ["der Pass", "passport"],
    ["das Geld", "money"],
    ["die Münze", "coin"],
    ["der Preis", "price"],
    ["die Rechnung", "bill"],
    ["das Konto", "account"],
    ["die Kreditkarte", "credit card"],
    ["die Arbeit", "work"],
    ["der Job", "job"],
    ["das Team", "team"],
    ["der Chef", "boss"],
    ["der Kollege", "colleague"],
    ["die Firma", "company"],
    ["das Projekt", "project"],
    ["der Plan", "plan"],
    ["die Idee", "idea"],
    ["das Problem", "problem"],
    ["die Lösung", "solution"],
    ["der Grund", "reason"],
    ["das Ergebnis", "result"],
    ["und", "and"],
    ["oder", "or"],
    ["aber", "but"],
    ["weil", "because"],
    ["wenn", "if / when"],
    ["dass", "that"],
    ["obwohl", "although"],
    ["denn", "because / for"],
    ["also", "so / thus"],
    ["dann", "then"],
    ["auch", "also"],
    ["nicht", "not"],
    ["nur", "only"],
    ["schon", "already"],
    ["noch", "still / yet"],
    ["immer", "always"],
    ["nie", "never"],
    ["manchmal", "sometimes"],
    ["oft", "often"],
    ["selten", "rarely"],
    ["in", "in"],
    ["auf", "on"],
    ["unter", "under"],
    ["über", "over / above"],
    ["neben", "next to"],
    ["zwischen", "between"],
    ["vor", "before / in front of"],
    ["nach", "after / to"],
    ["mit", "with"],
    ["ohne", "without"],
    ["für", "for"],
    ["gegen", "against"],
    ["durch", "through"],
    ["um", "around / at (time)"],
    ["zu", "to"],
    ["von", "from / of"],
    ["bei", "at / near"],
    ["seit", "since"],
    ["bis", "until"],
    ["ich", "I"],
    ["du", "you (informal)"],
    ["er", "he"],
    ["sie", "she / they"],
    ["es", "it"],
    ["wir", "we"],
    ["ihr", "you all (informal)"],
    ["Sie", "you (formal)"],
    ["mein", "my"],
    ["dein", "your (informal)"],
    ["unser", "our"],
    ["euer", "your (plural informal)"],
    ["dieser", "this"],
    ["jener", "that"],
    ["jeder", "every"],
    ["alle", "all"],
    ["einige", "some"],
    ["viele", "many"],
    ["wenige", "few"],
    ["etwas", "something"],
    ["nichts", "nothing"],
    ["jemand", "someone"],
    ["niemand", "no one"],
    ["wer", "who"],
    ["was", "what"],
    ["wann", "when"],
    ["wo", "where"],
    ["warum", "why"],
    ["wie", "how"],
    ["welche", "which"],
    ["wieviel", "how much"],
    ["wie viele", "how many"],
    ["woher", "from where"],
    ["wohin", "to where"],
    ["wozu", "for what"],
    ["womit", "with what"],
    ["wessen", "whose"],
    ["wie lange", "how long"],
    ["Wie heißt du?", "What is your name?"],
    ["Ich heiße...", "My name is..."],
    ["Wie alt bist du?", "How old are you?"],
    ["Ich bin... Jahre alt", "I am... years old"],
    ["Woher kommst du?", "Where are you from?"],
    ["Ich komme aus...", "I come from..."],
    ["Sprichst du Deutsch?", "Do you speak German?"],
    ["Ich spreche ein bisschen Deutsch", "I speak a little German"],
    ["Ich verstehe nicht", "I don't understand"],
    ["Können Sie das wiederholen?", "Can you repeat that?"],
    ["Wie sagt man das auf Deutsch?", "How do you say that in German?"],
    ["Was bedeutet das?", "What does that mean?"],
    ["Ich weiß nicht", "I don't know"],
    ["Kein Problem", "No problem"],
    ["Wie spät ist es?", "What time is it?"],
    ["Es tut mir leid", "I am sorry"],
    ["Alles klar", "All clear / okay"],
    ["Bis später", "See you later"],
    ["Bis bald", "See you soon"],
    ["Schönen Tag noch", "Have a nice day"],
    ["Wie bitte?", "Pardon?"],
    ["Was ist los?", "What's wrong?"],
    ["Keine Ahnung", "No idea"],
    ["Ich hätte gern...", "I would like..."],
    ["Wie viel kostet das?", "How much does that cost?"],
    ["Wo ist die Toilette?", "Where is the bathroom?"],
    ["Ich brauche Hilfe", "I need help"],
    ["Können Sie mir helfen?", "Can you help me?"],
    ["Herzlich willkommen", "Warm welcome"],
    ["Guten Appetit", "Enjoy your meal"],
    ["die Liebe", "love"],
    ["der Hass", "hate"],
    ["die Freude", "joy"],
    ["die Angst", "fear"],
    ["die Wut", "anger"],
    ["die Überraschung", "surprise"],
    ["die Scham", "shame"],
    ["der Stolz", "pride"],
    ["die Eifersucht", "jealousy"],
    ["die Hoffnung", "hope"],
    ["die Sorge", "worry"],
    ["die Ruhe", "calm"],
    ["die Aufregung", "excitement"],
    ["die Langeweile", "boredom"],
    ["die Einsamkeit", "loneliness"],
    ["das Glück", "happiness / luck"],
    ["das Leid", "suffering"],
    ["die Erleichterung", "relief"],
    ["die Verwirrung", "confusion"],
    ["das Vertrauen", "trust"],
    ["verliebt", "in love"],
    ["eifersüchtig", "jealous"],
    ["stolz", "proud"],
    ["überrascht", "surprised"],
    ["verwirrt", "confused"],
    ["gelangweilt", "bored"],
    ["aufgeregt", "excited"],
    ["entspannt", "relaxed"],
    ["enttäuscht", "disappointed"],
    ["zufrieden", "satisfied"],
    ["die Landschaft", "landscape"],
    ["der Ozean", "ocean"],
    ["die Küste", "coast"],
]

def render_error():
    return render.Root(
        render.WrappedText("Something went wrong getting today's word!"),
    )

def main():
    print("Starting")

    date = str(time.now())[0:10]

    print(date)

    # do a weird hash thing to the date to get the randomish word
    word_index = abs(int(math.remainder(int(hash.md5(date), 16), len(word_array))))
    print(int(word_index))

    word = word_array[word_index][0]
    definition = word_array[word_index][1]

    return render.Root(
        child = render.Column(
            children = [
                render.Marquee(
                    child = render.Column(
                        children = [
                            render.WrappedText(
                                content = word,
                                color = "#00eeff",
                                font = "5x8",
                            ),
                            render.WrappedText(
                                content = definition,
                                font = "5x8",
                            ),
                        ],
                    ),
                    height = 25,
                    offset_start = 23,
                    scroll_direction = "vertical",
                ),
                render.Box(
                    height = 1,
                    color = "#fa0",
                ),
                render.Text(
                    content = "German WotD",
                    height = 6,
                    font = "CG-pixel-3x5-mono",
                ),
            ],
        ),
        delay = 140,
    )
