"""
Bundled team logos for uflscores. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/bham-7b047fea-16.png", LOGO_BHAM_7B047FEA_16 = "file")
load("images/logos/bham-7b047fea-30.png", LOGO_BHAM_7B047FEA_30 = "file")
load("images/logos/bham-7b047fea-32.png", LOGO_BHAM_7B047FEA_32 = "file")
load("images/logos/clb-3b7a12e6-16.png", LOGO_CLB_3B7A12E6_16 = "file")
load("images/logos/clb-3b7a12e6-30.png", LOGO_CLB_3B7A12E6_30 = "file")
load("images/logos/clb-3b7a12e6-32.png", LOGO_CLB_3B7A12E6_32 = "file")
load("images/logos/dal-14374fba-16.png", LOGO_DAL_14374FBA_16 = "file")
load("images/logos/dal-14374fba-30.png", LOGO_DAL_14374FBA_30 = "file")
load("images/logos/dal-14374fba-32.png", LOGO_DAL_14374FBA_32 = "file")
load("images/logos/dc-2872375a-16.png", LOGO_DC_2872375A_16 = "file")
load("images/logos/dc-2872375a-30.png", LOGO_DC_2872375A_30 = "file")
load("images/logos/dc-2872375a-32.png", LOGO_DC_2872375A_32 = "file")
load("images/logos/hou-0d0b3484-16.png", LOGO_HOU_0D0B3484_16 = "file")
load("images/logos/hou-0d0b3484-30.png", LOGO_HOU_0D0B3484_30 = "file")
load("images/logos/hou-0d0b3484-32.png", LOGO_HOU_0D0B3484_32 = "file")
load("images/logos/lou-92bc7b0d-16.png", LOGO_LOU_92BC7B0D_16 = "file")
load("images/logos/lou-92bc7b0d-30.png", LOGO_LOU_92BC7B0D_30 = "file")
load("images/logos/lou-92bc7b0d-32.png", LOGO_LOU_92BC7B0D_32 = "file")
load("images/logos/orl-5997dc7b-16.png", LOGO_ORL_5997DC7B_16 = "file")
load("images/logos/orl-5997dc7b-30.png", LOGO_ORL_5997DC7B_30 = "file")
load("images/logos/orl-5997dc7b-32.png", LOGO_ORL_5997DC7B_32 = "file")
load("images/logos/shared-3fdf1951-source.png", LOGO_SHARED_3FDF1951_SOURCE = "file")
load("images/logos/stl-3abc9d66-16.png", LOGO_STL_3ABC9D66_16 = "file")
load("images/logos/stl-3abc9d66-30.png", LOGO_STL_3ABC9D66_30 = "file")
load("images/logos/stl-3abc9d66-32.png", LOGO_STL_3ABC9D66_32 = "file")

BUNDLED_LOGOS = {
    # BHAM; source sha256 92c5dbb60a13032bc024dc3f23581eb0a11122c4ffcffa4145cf513d7bbf62a1
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/bham.png&h=50&w=50": {
        16: LOGO_BHAM_7B047FEA_16,
        30: LOGO_BHAM_7B047FEA_30,
        32: LOGO_BHAM_7B047FEA_32,
    },
    # CLB; source sha256 fe66560ccc8b4a812a85f60c0ba367010bf4ecd08ad0568ef7eaf93426a860cc
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/clb.png&h=50&w=50": {
        16: LOGO_CLB_3B7A12E6_16,
        30: LOGO_CLB_3B7A12E6_30,
        32: LOGO_CLB_3B7A12E6_32,
    },
    # DAL; source sha256 a4f27535be5a1e832fd2fe91e40e96790b0582b202696010e767d4e5955b6e74
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/dal.png&h=50&w=50": {
        16: LOGO_DAL_14374FBA_16,
        30: LOGO_DAL_14374FBA_30,
        32: LOGO_DAL_14374FBA_32,
    },
    # DC; source sha256 4bff8f32ef17fe79645775c850695a3aac55001c3460c0329911dd84dac4b9d3
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/dc.png&h=50&w=50": {
        16: LOGO_DC_2872375A_16,
        30: LOGO_DC_2872375A_30,
        32: LOGO_DC_2872375A_32,
    },
    # HOU; source sha256 1ab9342d9452f6a7bbc3e71e2e20892f71925436c82e20ecbb497ebcd6de65aa
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/hou.png&h=50&w=50": {
        16: LOGO_HOU_0D0B3484_16,
        30: LOGO_HOU_0D0B3484_30,
        32: LOGO_HOU_0D0B3484_32,
    },
    # LOU; source sha256 967bc1c6419e833970a09a20935c13152f32d094b3ae8e67d897658d57e5bc4e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/lou.png&h=50&w=50": {
        16: LOGO_LOU_92BC7B0D_16,
        30: LOGO_LOU_92BC7B0D_30,
        32: LOGO_LOU_92BC7B0D_32,
    },
    # ORL; source sha256 e68d20e633076708d3086344bdd5a3490de58e2801b5c18d4d03cffcab48857e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/orl.png&h=50&w=50": {
        16: LOGO_ORL_5997DC7B_16,
        30: LOGO_ORL_5997DC7B_30,
        32: LOGO_ORL_5997DC7B_32,
    },
    # STL; source sha256 7354e875c3916c9d37fdcfc27e097e4cceb8d4e4de326a31079a5788324d9f17
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/ufl/500-dark/scoreboard/stl.png&h=50&w=50": {
        16: LOGO_STL_3ABC9D66_16,
        30: LOGO_STL_3ABC9D66_30,
        32: LOGO_STL_3ABC9D66_32,
    },
    # placeholder; source sha256 f83aa2bf315d978c13bd5a91e729a5eac7b4616ec8b49bfdaf5e9b3262f27f30
    "https://i.ibb.co/5LMp8T1/transparent.png&h=50&w=50": {
        16: LOGO_SHARED_3FDF1951_SOURCE,
        30: LOGO_SHARED_3FDF1951_SOURCE,
        32: LOGO_SHARED_3FDF1951_SOURCE,
    },
}
