"""
Bundled team logos for mlbstandings. Generated by tools/lunchbox_logos; do not edit.

BUNDLED_LOGOS maps each URL (or bundled path) the app would read to files
already resized by the runtime's nearest-neighbour resize, keyed by drawn size.
Comments record each source's SHA-256. URLs and sizes not listed are fetched
from the network as before.
"""

load("images/logos/ari-0bb25cac-10.png", LOGO_ARI_0BB25CAC_10 = "file")
load("images/logos/ath-0fb3d2c2-10.png", LOGO_ATH_0FB3D2C2_10 = "file")
load("images/logos/atl-ca11f462-10.png", LOGO_ATL_CA11F462_10 = "file")
load("images/logos/bal-ea036e7c-10.png", LOGO_BAL_EA036E7C_10 = "file")
load("images/logos/bos-b6c728cf-10.png", LOGO_BOS_B6C728CF_10 = "file")
load("images/logos/chc-4c4db8d0-10.png", LOGO_CHC_4C4DB8D0_10 = "file")
load("images/logos/chw-d6adca4d-10.png", LOGO_CHW_D6ADCA4D_10 = "file")
load("images/logos/cin-33593cc6-10.png", LOGO_CIN_33593CC6_10 = "file")
load("images/logos/cle-0e4358e1-10.png", LOGO_CLE_0E4358E1_10 = "file")
load("images/logos/col-516b86e3-10.png", LOGO_COL_516B86E3_10 = "file")
load("images/logos/det-3c4cf148-source.png", LOGO_DET_3C4CF148_SOURCE = "file")
load("images/logos/hou-0db78273-10.png", LOGO_HOU_0DB78273_10 = "file")
load("images/logos/kc-1b0ad778-10.png", LOGO_KC_1B0AD778_10 = "file")
load("images/logos/laa-fd3c664a-10.png", LOGO_LAA_FD3C664A_10 = "file")
load("images/logos/lad-4e8070d4-10.png", LOGO_LAD_4E8070D4_10 = "file")
load("images/logos/mia-e2dbcfbb-10.png", LOGO_MIA_E2DBCFBB_10 = "file")
load("images/logos/mil-a59c7762-10.png", LOGO_MIL_A59C7762_10 = "file")
load("images/logos/min-9adb31fa-10.png", LOGO_MIN_9ADB31FA_10 = "file")
load("images/logos/nym-0aa5e709-10.png", LOGO_NYM_0AA5E709_10 = "file")
load("images/logos/nyy-259da3c2-10.png", LOGO_NYY_259DA3C2_10 = "file")
load("images/logos/phi-dd837d39-source.png", LOGO_PHI_DD837D39_SOURCE = "file")
load("images/logos/pit-b7bceca4-10.png", LOGO_PIT_B7BCECA4_10 = "file")
load("images/logos/sd-c64e8816-10.png", LOGO_SD_C64E8816_10 = "file")
load("images/logos/sea-ded8a131-10.png", LOGO_SEA_DED8A131_10 = "file")
load("images/logos/sf-3d319469-10.png", LOGO_SF_3D319469_10 = "file")
load("images/logos/stl-b606dffd-10.png", LOGO_STL_B606DFFD_10 = "file")
load("images/logos/tb-6ebf08a9-10.png", LOGO_TB_6EBF08A9_10 = "file")
load("images/logos/tex-48b3ffac-10.png", LOGO_TEX_48B3FFAC_10 = "file")
load("images/logos/tor-b8d796a5-10.png", LOGO_TOR_B8D796A5_10 = "file")
load("images/logos/wsh-243a6939-10.png", LOGO_WSH_243A6939_10 = "file")

BUNDLED_LOGOS = {
    # ARI; source sha256 a8cea1cfdca6f698f89c7da3760dc197b781eae67599212b4f4ae3e451bcabf7
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/ari.png&h=50&w=50": {
        10: LOGO_ARI_0BB25CAC_10,
    },
    # ATH; source sha256 29d5ec07d0321c3819309beda98fc7980c7251218c99df1255c3199ffabf51aa
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/ath.png&h=50&w=50": {
        10: LOGO_ATH_0FB3D2C2_10,
    },
    # ATL; source sha256 9376b59a11265f1260412736beb8bcba59164a71ce37141b199537d15451e869
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/atl.png&h=50&w=50": {
        10: LOGO_ATL_CA11F462_10,
    },
    # BAL; source sha256 43a311e36812005501499e7b3c4716befcaa8e66ae37784417c8ed2e916c2f61
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/bal.png&h=50&w=50": {
        10: LOGO_BAL_EA036E7C_10,
    },
    # BOS; source sha256 5658216589c81fff3a1e05eadaa4876f2f07a7264a438fb735337a5aeff35e1c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/bos.png&h=50&w=50": {
        10: LOGO_BOS_B6C728CF_10,
    },
    # CHC; source sha256 df9605877616a04338d605481b912c69c2d8a5b6c0bd92ffc76f81076e43f6a4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/chc.png&h=50&w=50": {
        10: LOGO_CHC_4C4DB8D0_10,
    },
    # CHW; source sha256 f5f9711c9c788cc6e3f0ca6d66c0c56bb54452a7265a24a40cfcff7455e3cd9e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/chw.png&h=50&w=50": {
        10: LOGO_CHW_D6ADCA4D_10,
    },
    # COL; source sha256 48195a6f4787bb6b46c44fdc1ee62512ef4a87d1163e244eecdf52d06d52049e
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/col.png&h=50&w=50": {
        10: LOGO_COL_516B86E3_10,
    },
    # HOU; source sha256 7695a7c9b03f8d2925abed6805b19e802113280e10bd6dfb6021972a25e4120d
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/hou.png&h=50&w=50": {
        10: LOGO_HOU_0DB78273_10,
    },
    # KC; source sha256 b9368c2b039bed489eebc750a5fa199449ad3bfe75264d32721bbce93d5ab778
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/kc.png&h=50&w=50": {
        10: LOGO_KC_1B0AD778_10,
    },
    # LAA; source sha256 42df7c9811518fa5e0a0db838122a175c5cba0e1627668434fd616fe61fd0be4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/laa.png&h=50&w=50": {
        10: LOGO_LAA_FD3C664A_10,
    },
    # LAD; source sha256 4ab71eaf313c89371c50011b965fea7e33487488cde718b01c093ead01b5ddea
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/lad.png&h=50&w=50": {
        10: LOGO_LAD_4E8070D4_10,
    },
    # MIA; source sha256 ddf908757c1a67f694355c15f5678ad57c011cd22406b6241f62ad6383105c7f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/mia.png&h=50&w=50": {
        10: LOGO_MIA_E2DBCFBB_10,
    },
    # MIN; source sha256 3519c430e2bd8502675f1b5b06bf44cc21bab77daaa11b24e5eeb72ddbe19e14
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/min.png&h=50&w=50": {
        10: LOGO_MIN_9ADB31FA_10,
    },
    # NYM; source sha256 75679c7908f96d9a199d36de655f3737796776e39faabeccc29152e4c018c231
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/nym.png&h=50&w=50": {
        10: LOGO_NYM_0AA5E709_10,
    },
    # NYY; source sha256 3ff71b76e167084f23bd3bb63050347573f78f8b108e268866b85eabf6425c7c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/nyy.png&h=50&w=50": {
        10: LOGO_NYY_259DA3C2_10,
    },
    # PIT; source sha256 f5b4fab6d0f9b92f1755816f5395e297c345a1b26671ae33a4f8ce4556307ef7
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/pit.png&h=50&w=50": {
        10: LOGO_PIT_B7BCECA4_10,
    },
    # SD; source sha256 beca13327ac8938e50a1c04dbaa519a304380baa513550d135a40dc34346ad3f
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sd.png&h=50&w=50": {
        10: LOGO_SD_C64E8816_10,
    },
    # SEA; source sha256 0d93fb9e10a989fa2484850f5510733c07b031e72def35b74a506afca87db166
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sea.png&h=50&w=50": {
        10: LOGO_SEA_DED8A131_10,
    },
    # SF; source sha256 499a83ed5c385d76dc299eb0f73fd01e5b625180e0be34158c533a0183a7e356
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/sf.png&h=50&w=50": {
        10: LOGO_SF_3D319469_10,
    },
    # TB; source sha256 9cc570862c0ad913d543c54f13aab64d83a3fdc7527557dcb7e1f7358850b2f4
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tb.png&h=50&w=50": {
        10: LOGO_TB_6EBF08A9_10,
    },
    # TEX; source sha256 35de8568a6dbd9f0b947da09190a38a10b865c502cb6008c3e4e2ff28491c500
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tex.png&h=50&w=50": {
        10: LOGO_TEX_48B3FFAC_10,
    },
    # TOR; source sha256 6a59c88b90fcaef87d41f77851b153bce2575c5ec82b7f8b103ed4788380e48c
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/tor.png&h=50&w=50": {
        10: LOGO_TOR_B8D796A5_10,
    },
    # WSH; source sha256 a5b336ecd6329711db14f83d116f7a139edff20e06bd78beefc3ecec32e765af
    "https://a.espncdn.com/combiner/i?img=i/teamlogos/mlb/500-dark/scoreboard/wsh.png&h=50&w=50": {
        10: LOGO_WSH_243A6939_10,
    },
    # CLE; source sha256 8883a4e8b7c6bb75f308f1fb27a39eb7cf81ce431ba781edbc4afe082164410f
    "https://a.espncdn.com/i/teamlogos/mlb/500/scoreboard/cle.png": {
        10: LOGO_CLE_0E4358E1_10,
    },
    # MIL; source sha256 0e6d36aa8acb57bbdab9c8b548a1f2f3448e1c0faebbdb760504548323df3f5b
    "https://b.fssta.com/uploads/application/mlb/team-logos/Brewers.png": {
        10: LOGO_MIL_A59C7762_10,
    },
    # STL; source sha256 7c296c57ba263c01179f2236733182cb59a1106f0945c44d0adf662093fd8db0
    "https://b.fssta.com/uploads/application/mlb/team-logos/Cardinals-alternate.png": {
        10: LOGO_STL_B606DFFD_10,
    },
    # PHI; source sha256 8f6970633152dddd923e7ffa10686425267acdb1bb2fc5ea67f16fc7a12ad7a4
    "https://b.fssta.com/uploads/application/mlb/team-logos/Phillies-alternate.png": {
        10: LOGO_PHI_DD837D39_SOURCE,
    },
    # CIN; source sha256 4801b18fdc3b49931626e280852b9edec6cb8ba6338dd085977e21841b15d74e
    "https://b.fssta.com/uploads/application/mlb/team-logos/Reds-alternate.png": {
        10: LOGO_CIN_33593CC6_10,
    },
    # DET; source sha256 42bc138e8a1afd941fa06c5242358aca9cfd05ac50116132d2d4a0522a983ca3
    "https://b.fssta.com/uploads/application/mlb/team-logos/Tigers-alternate.png": {
        10: LOGO_DET_3C4CF148_SOURCE,
    },
}
